#
#  ISC License
#
#  Copyright (c) 2025, Autonomous Vehicle Systems Lab, University of Colorado at Boulder
#
#  Permission to use, copy, modify, and/or distribute this software for any
#  purpose with or without fee is hereby granted, provided that the above
#  copyright notice and this permission notice appear in all copies.
#
#  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

from pathlib import Path
import hashlib

ROOT = Path("supportData")

IGNORE_PATTERNS = ("__pycache__", ".pyc", "__init__.py", "*.bsp")


def should_include(path: Path) -> bool:
    name = path.name

    for pattern in IGNORE_PATTERNS:
        if path.match(pattern):
            return False

    if name.startswith("."):
        return False

    # Skip GRAM namelist directory
    if path.is_relative_to(ROOT / "AtmosphereData" / "support"):
        return False

    return True


def md5_hex(path: Path) -> str:
    h = hashlib.md5()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def main():
    if not ROOT.exists():
        raise RuntimeError(
            "supportData directory not found. Run this script from the project root."
        )

    files = [p for p in ROOT.rglob("*") if p.is_file() and should_include(p)]

    def registry_key(p: Path) -> tuple[str, str]:
        rel_posix = p.relative_to(ROOT.parent).as_posix()
        return (rel_posix.casefold(), rel_posix)

    files.sort(key=registry_key)
    entries = []

    for path in files:
        rel = path.relative_to(ROOT.parent)
        digest = md5_hex(path)
        entries.append(f'    "{rel.as_posix()}": "md5:{digest}",')

    print("# Auto-generated registry of support data files by makeRegistry.py")
    print("# DO NOT EDIT THIS FILE BY HAND. Run makeRegistry.py to update.\n")
    print("REGISTRY = {")
    for e in entries:
        print(e)
    print("}")


if __name__ == "__main__":
    main()
