# ISC License
#
# Copyright (c) 2026, Autonomous Vehicle Systems Lab, University of Colorado at Boulder
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

"""Check compatibility and import isolation of the combined FSW layout."""

import importlib
import importlib.machinery
import importlib.util
from pathlib import Path
import subprocess
import sys
import textwrap

import pytest
from Basilisk import fswAlgorithms


PACKAGE_DIR = Path(fswAlgorithms.__file__).parent
COMBINED = importlib.util.find_spec("Basilisk.fswAlgorithms._fswCoreNative")


def test_fsw_bindings_share_library_and_keep_module_identity():
    """Every generated shim resolves to its original native module identity."""
    assert COMBINED is not None, "The core FSW native library is required"
    shims = [path for path in PACKAGE_DIR.glob("_*.py")
             if "Generated by generateFswBindings.py" in path.read_text()]
    assert len(shims) > 1
    for shim in shims:
        name = shim.stem[1:]
        proxy = importlib.import_module(f"Basilisk.fswAlgorithms.{name}")
        native = importlib.import_module(f"Basilisk.fswAlgorithms._{name}")
        assert importlib.reload(native) is native
        assert getattr(proxy, f"_{name}") is native
        assert getattr(fswAlgorithms, f"_{name}") is native
        assert native.__spec__.name == f"Basilisk.fswAlgorithms._{name}"
        assert Path(native.__file__) == Path(COMBINED.origin)
        assert isinstance(native.__loader__, importlib.machinery.ExtensionFileLoader)
        assert not any((PACKAGE_DIR / f"_{name}{suffix}").exists()
                       for suffix in importlib.machinery.EXTENSION_SUFFIXES)
    for name in ("centerRadiusCNN", "houghCircles", "limbFinding", "mrpPDRust"):
        spec = importlib.util.find_spec(f"Basilisk.fswAlgorithms._{name}")
        if spec is not None:
            assert Path(spec.origin) != Path(COMBINED.origin)


@pytest.mark.parametrize("private_first", [False, True])
def test_fsw_imports_are_on_demand_and_recorders_work(private_first):
    """Public and private imports and reloads preserve identity and recorder types.

    :param private_first: Import the private extension before its public proxy.
    """
    code = textwrap.dedent(f"""\
        import importlib
        import importlib.machinery
        import sys
        from Basilisk import fswAlgorithms
        assert 'Basilisk.fswAlgorithms._mrpFeedback' not in sys.modules
        if {private_first}:
            importlib.import_module('Basilisk.fswAlgorithms._mrpFeedback')
        from Basilisk.fswAlgorithms import mrpFeedback
        from Basilisk.architecture import messaging
        native = importlib.import_module('Basilisk.fswAlgorithms._mrpFeedback')
        assert mrpFeedback._mrpFeedback is native
        assert fswAlgorithms._mrpFeedback is native
        assert 'Basilisk.fswAlgorithms._mrpPD' not in sys.modules
        assert 'Basilisk.fswAlgorithms.mrpPD' not in sys.modules
        native_spec = native.__spec__
        sentinel = object()
        native.reload_sentinel = sentinel
        for _ in range(2):
            assert importlib.reload(native) is native
            assert importlib.import_module(native.__name__) is native
            assert mrpFeedback._mrpFeedback is native
            assert fswAlgorithms._mrpFeedback is native
            assert native.__file__ == native_spec.origin
            assert isinstance(native.__loader__, importlib.machinery.ExtensionFileLoader)
            assert native.__spec__.origin == native_spec.origin
            assert native.__package__ == native_spec.parent
            assert not hasattr(native, '__cached__')
            assert native.reload_sentinel is sentinel
        model = mrpFeedback.mrpFeedback()
        recorder = model.cmdTorqueOutMsg.recorder()
        assert isinstance(recorder, messaging.CmdTorqueBodyMsgRecorder)
        payload = messaging.CmdTorqueBodyMsgPayload()
        payload.torqueRequestBody = [1.0, 2.0, 3.0]  # [N m]
        write_time = 42  # [ns]
        model.cmdTorqueOutMsg.write(payload, write_time)
        recorder.UpdateState(write_time)
        assert recorder.times().tolist() == [write_time]
        assert recorder.torqueRequestBody.tolist() == [[1.0, 2.0, 3.0]]  # [N m]
        importlib.reload(mrpFeedback)
        assert mrpFeedback._mrpFeedback is native
        assert importlib.import_module(native.__name__) is native
        """)
    result = subprocess.run([sys.executable, "-c", code], capture_output=True, text=True)
    assert result.returncode == 0, result.stdout + result.stderr


@pytest.mark.parametrize("second_import", ["private", "public"])
@pytest.mark.parametrize("fail_first", [False, True], ids=["success", "retry"])
def test_concurrent_fsw_imports_wait_for_native_initialization(second_import, fail_first):
    """Concurrent imports wait for initialization and can retry a failed import.

    :param second_import: Import the private extension or its public proxy second.
    :param fail_first: Fail the first initialization and verify a subsequent import recovers.
    """
    code = textwrap.dedent("""\
        import importlib
        import importlib.machinery
        import sys
        import threading
        from Basilisk import fswAlgorithms

        native_name = 'Basilisk.fswAlgorithms._mrpFeedback'
        public_name = 'Basilisk.fswAlgorithms.mrpFeedback'
        second_name = native_name if sys.argv[1] == 'private' else public_name
        fail_first = sys.argv[2] == 'True'
        timeout = 10.0  # [s]
        blocking_window = 0.2  # [s]
        entered = threading.Event()
        release = threading.Event()
        second_started = threading.Event()
        second_done = threading.Event()
        modules = {}
        errors = {}
        attempts = []
        original_exec = importlib.machinery.ExtensionFileLoader.exec_module

        def paused_exec(loader, module):
            if loader.name == native_name:
                attempts.append(module)
                if len(attempts) == 1:
                    entered.set()
                    assert release.wait(timeout), 'Native initialization was never released'
                    if fail_first:
                        raise RuntimeError('Injected native initialization failure')
            return original_exec(loader, module)

        def import_module(label, name):
            if label == 'second':
                second_started.set()
            try:
                modules[label] = importlib.import_module(name)
            except BaseException as error:
                errors[label] = error
            finally:
                if label == 'second':
                    second_done.set()

        importlib.machinery.ExtensionFileLoader.exec_module = paused_exec
        first = threading.Thread(target=import_module, args=('first', native_name), daemon=True)
        second = threading.Thread(target=import_module, args=('second', second_name), daemon=True)
        try:
            first.start()
            assert entered.wait(timeout), 'Native initialization did not start'
            second.start()
            assert second_started.wait(timeout), 'Concurrent import did not start'
            returned_early = second_done.wait(blocking_window)
        finally:
            release.set()
            first.join(timeout)
            if second.ident is not None:
                second.join(timeout)
            importlib.machinery.ExtensionFileLoader.exec_module = original_exec

        assert not first.is_alive() and not second.is_alive(), 'Import deadlock'
        assert not returned_early, 'Concurrent import returned an unfinished native module'
        assert second_done.is_set()
        if fail_first:
            assert isinstance(errors.get('first'), RuntimeError), errors
            assert str(errors['first']) == 'Injected native initialization failure'
            if 'second' in errors:
                # Some Python versions report ImportError to a waiting public
                # import after the private import fails. Require a clean retry.
                assert second_name == public_name
                assert isinstance(errors['second'], ImportError), errors
                assert len(attempts) == 1
                assert native_name not in sys.modules
                assert public_name not in sys.modules
                importlib.machinery.ExtensionFileLoader.exec_module = paused_exec
                try:
                    modules['second'] = importlib.import_module(second_name)
                finally:
                    importlib.machinery.ExtensionFileLoader.exec_module = original_exec
                del errors['second']
            assert set(errors) == {'first'}, errors
            assert len(attempts) == 2
        else:
            assert not errors, errors
            assert len(attempts) == 1

        native = importlib.import_module(native_name)
        proxy = importlib.import_module(public_name)
        assert modules['second'] is (native if second_name == native_name else proxy)
        assert native is attempts[-1]
        if not fail_first:
            assert modules['first'] is native
        assert proxy._mrpFeedback is fswAlgorithms._mrpFeedback is native
        assert all(not getattr(module.__spec__, '_initializing', False) for module in attempts)
        assert importlib.reload(native) is native
        from Basilisk.architecture import messaging
        model = proxy.mrpFeedback()
        assert isinstance(model.cmdTorqueOutMsg.recorder(), messaging.CmdTorqueBodyMsgRecorder)
        """)
    subprocess_timeout = 60  # [s]
    result = subprocess.run(
        [sys.executable, "-c", code, second_import, str(fail_first)],
        capture_output=True, text=True, timeout=subprocess_timeout,
    )
    assert result.returncode == 0, result.stdout + result.stderr
