# ISC License
#
# Copyright (c) 2026, Autonomous Vehicle Systems Lab, University of Colorado at Boulder
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

"""Check grouped simulation and optional imports without changing their public APIs."""

import importlib
import importlib.util
from pathlib import Path
import re
import subprocess
import sys

import pytest
from Basilisk import fswAlgorithms, simulation


GROUPS = (
    ("Basilisk.simulation._simulationCoreNative", "simulation", "spacecraft", "Spacecraft"),
    ("Basilisk.simulation._mujocoNative", "simulation", "thrOnTimeToForce", "ThrOnTimeToForce"),
    ("Basilisk._opNavNative", "simulation", "camera", "Camera"),
)


@pytest.mark.parametrize("library,package,name,class_name", GROUPS)
def test_grouped_imports_preserve_proxies_and_private_modules(library, package, name, class_name):
    """Every grouped private extension retains its original Python proxy and reload identity.

    :param library: Name of the optional native container.
    :param package: Package containing the representative binding.
    :param name: Representative public module name.
    :param class_name: Representative constructor name.
    """
    spec = importlib.util.find_spec(library)
    if spec is None:
        pytest.skip("This combined binding group is disabled")
    count = 0
    for parent in (fswAlgorithms, simulation):
        directory = Path(parent.__file__).parent
        proxies = {}
        for path in directory.glob("*.py"):
            text = path.read_text(encoding="utf-8")
            match = re.search(r"^    from \. import (_[A-Za-z_][A-Za-z_0-9]*)$", text, re.MULTILINE)
            if match:
                proxies[match[1]] = path.stem
        for shim in directory.glob("_*.py"):
            text = shim.read_text(encoding="utf-8")
            if "Generated by generateGroupedBindings.py" not in text or repr(library) not in text:
                continue
            native = importlib.import_module(parent.__name__ + "." + shim.stem)
            proxy = importlib.import_module(parent.__name__ + "." + proxies[shim.stem])
            assert getattr(proxy, shim.stem) is native
            assert importlib.reload(native) is native
            assert getattr(parent, shim.stem) is native
            assert native.__file__ == spec.origin
            count += 1
    assert count > 1
    proxy = importlib.import_module("Basilisk." + package + "." + name)
    assert getattr(proxy, class_name)() is not None


@pytest.mark.parametrize("library,package,name,class_name", GROUPS)
def test_grouped_imports_initialize_only_requested_bindings(library, package, name, class_name):
    """A representative import leaves unrelated native bindings uninitialized.

    :param library: Name of the optional native container.
    :param package: Package containing the representative binding.
    :param name: Representative public module name.
    :param class_name: Representative constructor name.
    """
    if importlib.util.find_spec(library) is None:
        pytest.skip("This combined binding group is disabled")
    code = """import importlib, sys
from Basilisk import architecture
module = importlib.import_module(sys.argv[1])
assert getattr(module, sys.argv[2])() is not None
for unrelated in ('Basilisk.simulation._solarFlux', 'Basilisk.simulation._MJSystemCoM',
                  'Basilisk.fswAlgorithms._houghCircles'):
    assert unrelated not in sys.modules, unrelated
"""
    timeout = 60  # [s]
    result = subprocess.run([sys.executable, "-c", code, "Basilisk." + package + "." + name, class_name],
                            capture_output=True, text=True, timeout=timeout)
    assert result.returncode == 0, result.stdout + result.stderr


def test_group_layout_cleanup_preserves_other_groups(tmp_path):
    """Switching a cross-package group leaves adjacent native modules and loaders intact.

    :param tmp_path: Temporary directory supplied by pytest.
    """
    source = Path(__file__).resolve().parents[1]
    spec = importlib.util.spec_from_file_location("generateGroupedBindings", source / "cmake/generateGroupedBindings.py")
    generator = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(generator)
    manifest = tmp_path / "group.txt"
    package = tmp_path / "Basilisk"
    manifest.write_text("simulation.first\nfswAlgorithms.second\n")
    loader = source / "fswAlgorithms/_load_fsw.py"
    (package / "simulation").mkdir(parents=True)
    for name in ("first.lib", "_first.lib"):
        (package / "simulation" / name).touch()
    generator.generate_layout(manifest, package, loader, "_opNavNative", "_load_opnav")
    assert not list((package / "simulation").glob("*.lib"))
    first = package / "simulation/_first.py"
    stamp = first.stat().st_mtime_ns
    generator.generate_layout(manifest, package, loader, "_opNavNative", "_load_opnav")
    assert first.stat().st_mtime_ns == stamp
    unrelated = package / "simulation/_simulationCoreNative.so"
    unrelated.write_bytes(b"other group")
    native = package / "_opNavNative.so"
    native.touch()
    archive = package / "_opNavNative.lib"
    archive.touch()
    manifest.write_text("")
    generator.generate_layout(manifest, package, loader, "_opNavNative", "_load_opnav")
    assert not first.exists()
    assert not (package / "fswAlgorithms/_second.py").exists()
    assert not (package / "_load_opnav.py").exists()
    assert not native.exists()
    assert not archive.exists()
    assert unrelated.read_bytes() == b"other group"
