name: setup
description: >
  Sets up the required system dependencies to perform a Basilisk build

runs:
  using: "composite"
  steps:
    - name: Install Linux System Deps.
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-setuptools python3-tk libgtk2.0

    - name: SWIG Install (Linux)
      if: runner.os == 'Linux'
      uses: mmomtchev/setup-swig@v4
      with:
        version: v4.2.1

    - name: SWIG Install (macOS)
      if: runner.os == 'macOS'
      shell: bash
      env:
        HOMEBREW_NO_AUTO_UPDATE: 1
        HOMEBREW_NO_INSTALL_UPGRADE: 1
        HOMEBREW_NO_ANALYTICS: 1
      run: brew install swig || true

    - name: SWIG Install (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $swigDir = "C:\Program Files\SWIG"
        if (!(Test-Path $swigDir)) {New-Item -ItemType Directory -Path $swigDir | Out-Null}
        $swigZip = "$swigDir\swigwin-4.2.1.zip"
        $swigUrl = "https://sourceforge.net/projects/swig/files/swigwin/swigwin-4.2.1/swigwin-4.2.1.zip/download"
        Start-Process -NoNewWindow -Wait -FilePath "curl.exe" -ArgumentList "-L -o `"$swigZip`" `"$swigUrl`""
        if (!(Test-Path $swigZip) -or ((Get-Item $swigZip).Length -lt 500KB)) { Write-Host "Download failed or file is corrupted." }
        Expand-Archive -Path $swigZip -DestinationPath $swigDir -Force

    - name: "Add Basilisk and SWIG paths"
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $oldpath = (Get-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' -Name PATH).path
        $newPath = “C:\Program Files\SWIG\swigwin-4.2.1;$oldpath;${{ env.GITHUB_WORKSPACE }}\dist3\Basilisk”
        echo "PATH=$newPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
