/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) satellite_full_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_c5 CASADI_PREFIX(c5)
#define casadi_c6 CASADI_PREFIX(c6)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {10, 1, 1};
static const casadi_int casadi_s3[3] = {20, 1, 1};

static const casadi_real casadi_c0[9] = 
  {2.9699999999999999e-01, 0., 0., 0., 2.9699999999999999e-01, 0., 0., 0.,
  2.9699999999999999e-01};
static const casadi_real casadi_c1[18] = 
  {0., 0., 0., 1., 0., 0., 0., 0.,
  0., 0., 1., 0., 0., 0., 0., 0.,
  0., 1.};
static const casadi_real casadi_c2[24] = 
  {1., 0., 0., 1., 0., 0., 0., 1.,
  0., 0., 1., 0., 0., 0., 1., 0.,
  0., 1., 0., 0., 1., 0., 0., 1.};
static const casadi_real casadi_c3[6] = {0., 0., 0., 1., 0., 0.};
static const casadi_real casadi_c4[6] = {0., 0., 0., 0., 1., 0.};
static const casadi_real casadi_c5[6] = {0., 0., 0., 0., 0., 1.};
static const casadi_real casadi_c6[24] = 
  {0., 0., -1.2000000000000000e-01, 0., 0., 1.2000000000000000e-01, 0., 0.,
  1.2000000000000000e-01, 0., 0., -1.2000000000000000e-01, 1.2000000000000000e-01, -1.2000000000000000e-01, 0., 1.2000000000000000e-01,
  1.2000000000000000e-01, 0., -1.2000000000000000e-01, -1.2000000000000000e-01, 0., -1.2000000000000000e-01, 1.2000000000000000e-01, 0.};

static const casadi_real casadi_zeros[12] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0.};

/* satellite_full_expl_vde_adj:(i0[12],i1[12],i2[8],i3[10])->(o0[20]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w00=w+8, w01, w02, *w04=w+34, *w05=w+37, w06, w07, w08, *w09=w+43, *w10=w+49, *w11=w+52;
  casadi_real *w12=w+61, *w13=w+67, *w14=w+70, *w15=w+73, w16, w17, w18, w19, *w20=w+80, *w21=w+83, *w22=w+92, *w23=w+101;
  casadi_real *w25=w+116, *w26=w+122, *w27=w+125, *w28=w+128, w29, w30, w31, w32, w33, w34, w35, *w36=w+138;
  casadi_real w37, *w38=w+142, w39, w40, w41, w42, w43, w44, w45, w46, w47, *w49=w+172;
  casadi_real *w51=w+214, *w52=w+222, w53, w54, w55, w56, w57, w58, w59, w60, w61, w62;
  casadi_real w63, *w64=w+242, *w65=w+251, *w66=w+257, *w67=w+263, *w68=w+269, *w69=w+275, *w71=w+335, *w72=w+359;
  const casadi_real *cr, *cs, *ct, *wr03, *wr04, *wr05, *wr12, *wr15, *wr20, *wr21, *wr24, *wr48;
  const casadi_real *wr50, *wr51, *wr70;
  /* #0: @0 = zeros(12x1) */
  casadi_clear(w00, 12);
  /* #1: @1 = 1 */
  w01 = 1.;
  /* #2: @2 = 0 */
  w02 = 0.;
  /* #3: @3 = input[0][0] */
  wr03 = arg[0] ? arg[0] : casadi_zeros;
  /* #4: @4 = @3[6:9] */
  wr04 = wr03+6;
  /* #5: @5 = @4' */
  wr05 = wr04;
  /* #6: @6 = mac(@5,@4,@2) */
  casadi_copy((&w02), 1, (&w06));
  for (i=0, rr=(&w06); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=wr05+j, ct=wr04+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #7: @7 = (@1<@6) */
  w07  = (w01<w06);
  /* #8: @8 = (!@7) */
  w08 = (! w07 );
  /* #9: @9 = zeros(6x1) */
  casadi_clear(w09, 6);
  /* #10: @10 = zeros(3x1) */
  casadi_clear(w10, 3);
  /* #11: @11 = zeros(3x3) */
  casadi_clear(w11, 9);
  /* #12: @12 = @3[6:12] */
  wr12 = wr03+6;
  /* #13: @13 = (@4/@6) */
  for (i=0, rr=w13, cr=wr04; i<3; ++i) (*rr++)  = ((*cr++)/w06);
  /* #14: @14 = (-@13) */
  for (i=0, rr=w14, cs=w13; i<3; ++i) *rr++ = (- *cs++ );
  /* #15: @14 = (@7?@14:0) */
  for (i=0, rr=w14, cs=w14; i<3; ++i) (*rr++)  = (w07?cs[i]:0);
  /* #16: @15 = (@8?@4:0) */
  for (i=0, rr=w15, cs=wr04; i<3; ++i) (*rr++)  = (w08?cs[i]:0);
  /* #17: @14 = (@14+@15) */
  for (i=0, rr=w14, cs=w15; i<3; ++i) (*rr++) += (*cs++);
  /* #18: (@12[:3] = @14) */
  casadi_copy(wr12, 6, w12);
  for (rr=w12+0, cs=w14; rr!=w12+3; rr+=1) *rr = *cs++;
  /* #19: @16 = @12[5] */
  for (rr=(&w16), cs=w12+5; cs!=w12+6; cs+=1) *rr++ = *cs;
  /* #20: @17 = (-@16) */
  w17 = (- w16 );
  /* #21: @18 = @12[4] */
  for (rr=(&w18), cs=w12+4; cs!=w12+5; cs+=1) *rr++ = *cs;
  /* #22: @14 = horzcat(@2, @17, @18) */
  rr=w14;
  *rr++ = w02;
  *rr++ = w17;
  *rr++ = w18;
  /* #23: @14 = @14' */
  /* #24: @17 = @12[3] */
  for (rr=(&w17), cs=w12+3; cs!=w12+4; cs+=1) *rr++ = *cs;
  /* #25: @19 = (-@17) */
  w19 = (- w17 );
  /* #26: @15 = horzcat(@16, @2, @19) */
  rr=w15;
  *rr++ = w16;
  *rr++ = w02;
  *rr++ = w19;
  /* #27: @15 = @15' */
  /* #28: @18 = (-@18) */
  w18 = (- w18 );
  /* #29: @20 = horzcat(@18, @17, @2) */
  rr=w20;
  *rr++ = w18;
  *rr++ = w17;
  *rr++ = w02;
  /* #30: @20 = @20' */
  /* #31: @21 = horzcat(@14, @15, @20) */
  rr=w21;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<3; ++i) *rr++ = *cs++;
  /* #32: @22 = @21' */
  for (i=0, rr=w22, cs=w21; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #33: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<9; ++i) *rr++ = (- *cs++ );
  /* #34: @21 = 
  [[0.297, 0, 0], 
   [0, 0.297, 0], 
   [0, 0, 0.297]] */
  wr21 = casadi_c0;
  /* #35: @23 = mac(@22,@21,@11) */
  casadi_copy(w11, 9, w23);
  for (i=0, rr=w23; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w22+j, ct=wr21+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #36: @22 = @23' */
  for (i=0, rr=w22, cs=w23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #37: @14 = all_3.367(3x3,3nz) */
  casadi_fill(w14, 3, 3.3670033670033672e+00);
  /* #38: @14 = nonzeros(@14) */
  /* #39: @3 = input[1][0] */
  wr03 = arg[1] ? arg[1] : casadi_zeros;
  /* #40: {@24, @15, @20} = vertsplit(@3) */
  wr24 = wr03;
  wr15 = wr03+6;
  wr20 = wr03+9;
  /* #41: @14 = (@14*@20) */
  for (i=0, rr=w14, cs=wr20; i<3; ++i) (*rr++) *= (*cs++);
  /* #42: @20 = mac(@22,@14,@10) */
  casadi_copy(w10, 3, w20);
  for (i=0, rr=w20; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w22+j, ct=w14+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #43: @25 = @9; (@25[3:6] += @20) */
  casadi_copy(w09, 6, w25);
  for (rr=w25+3, cs=w20; rr!=w25+6; rr+=1) *rr += *cs++;
  /* #44: @20 = @12[3:6] */
  for (rr=w20, cs=w12+3; cs!=w12+6; cs+=1) *rr++ = *cs;
  /* #45: @20 = @20' */
  /* #46: @22 = mac(@14,@20,@11) */
  casadi_copy(w11, 9, w22);
  for (i=0, rr=w22; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w14+j, ct=w20+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #47: @23 = @21' */
  for (i=0, rr=w23, cs=wr21; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #48: @21 = mac(@22,@23,@11) */
  casadi_copy(w11, 9, w21);
  for (i=0, rr=w21; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w22+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #49: @21 = (-@21) */
  for (i=0, rr=w21, cs=w21; i<9; ++i) *rr++ = (- *cs++ );
  /* #50: @22 = @21' */
  for (i=0, rr=w22, cs=w21; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #51: {@26, @27, @28} = horzsplit(@22) */
  casadi_copy(w22, 3, w26);
  casadi_copy(w22+3, 3, w27);
  casadi_copy(w22+6, 3, w28);
  /* #52: @28 = @28' */
  /* #53: {@18, @17, NULL} = horzsplit(@28) */
  w18 = w28[0];
  w17 = w28[1];
  /* #54: @27 = @27' */
  /* #55: {@16, NULL, @19} = horzsplit(@27) */
  w16 = w27[0];
  w19 = w27[2];
  /* #56: @17 = (@17-@19) */
  w17 -= w19;
  /* #57: (@25[3] += @17) */
  for (rr=w25+3, cs=(&w17); rr!=w25+4; rr+=1) *rr += *cs++;
  /* #58: @26 = @26' */
  /* #59: {NULL, @17, @19} = horzsplit(@26) */
  w17 = w26[1];
  w19 = w26[2];
  /* #60: @19 = (@19-@18) */
  w19 -= w18;
  /* #61: (@25[4] += @19) */
  for (rr=w25+4, cs=(&w19); rr!=w25+5; rr+=1) *rr += *cs++;
  /* #62: @16 = (@16-@17) */
  w16 -= w17;
  /* #63: (@25[5] += @16) */
  for (rr=w25+5, cs=(&w16); rr!=w25+6; rr+=1) *rr += *cs++;
  /* #64: @26 = @12[:3] */
  for (rr=w26, cs=w12+0; cs!=w12+3; cs+=1) *rr++ = *cs;
  /* #65: @27 = @26' */
  casadi_copy(w26, 3, w27);
  /* #66: @16 = mac(@27,@26,@2) */
  casadi_copy((&w02), 1, (&w16));
  for (i=0, rr=(&w16); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w27+j, ct=w26+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #67: @16 = (@1-@16) */
  w16  = (w01-w16);
  /* #68: @17 = @12[0] */
  for (rr=(&w17), cs=w12+0; cs!=w12+1; cs+=1) *rr++ = *cs;
  /* #69: @19 = (2.*@17) */
  w19 = (2.* w17 );
  /* #70: @18 = (@19*@17) */
  w18  = (w19*w17);
  /* #71: @29 = (@16+@18) */
  w29  = (w16+w18);
  /* #72: @30 = @12[1] */
  for (rr=(&w30), cs=w12+1; cs!=w12+2; cs+=1) *rr++ = *cs;
  /* #73: @31 = (@17*@30) */
  w31  = (w17*w30);
  /* #74: @32 = @12[2] */
  for (rr=(&w32), cs=w12+2; cs!=w12+3; cs+=1) *rr++ = *cs;
  /* #75: @31 = (@31-@32) */
  w31 -= w32;
  /* #76: @31 = (2.*@31) */
  w31 = (2.* w31 );
  /* #77: @33 = (@17*@32) */
  w33  = (w17*w32);
  /* #78: @33 = (@33+@30) */
  w33 += w30;
  /* #79: @33 = (2.*@33) */
  w33 = (2.* w33 );
  /* #80: @28 = horzcat(@29, @31, @33) */
  rr=w28;
  *rr++ = w29;
  *rr++ = w31;
  *rr++ = w33;
  /* #81: @28 = @28' */
  /* #82: @29 = (@30*@17) */
  w29  = (w30*w17);
  /* #83: @29 = (@29+@32) */
  w29 += w32;
  /* #84: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #85: @31 = (2.*@30) */
  w31 = (2.* w30 );
  /* #86: @33 = (@31*@30) */
  w33  = (w31*w30);
  /* #87: @34 = (@16+@33) */
  w34  = (w16+w33);
  /* #88: @35 = (@30*@32) */
  w35  = (w30*w32);
  /* #89: @35 = (@35-@17) */
  w35 -= w17;
  /* #90: @35 = (2.*@35) */
  w35 = (2.* w35 );
  /* #91: @36 = horzcat(@29, @34, @35) */
  rr=w36;
  *rr++ = w29;
  *rr++ = w34;
  *rr++ = w35;
  /* #92: @36 = @36' */
  /* #93: @29 = (@32*@17) */
  w29  = (w32*w17);
  /* #94: @29 = (@29-@30) */
  w29 -= w30;
  /* #95: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #96: @34 = (@32*@30) */
  w34  = (w32*w30);
  /* #97: @34 = (@34+@17) */
  w34 += w17;
  /* #98: @34 = (2.*@34) */
  w34 = (2.* w34 );
  /* #99: @35 = (2.*@32) */
  w35 = (2.* w32 );
  /* #100: @37 = (@35*@32) */
  w37  = (w35*w32);
  /* #101: @16 = (@16+@37) */
  w16 += w37;
  /* #102: @38 = horzcat(@29, @34, @16) */
  rr=w38;
  *rr++ = w29;
  *rr++ = w34;
  *rr++ = w16;
  /* #103: @38 = @38' */
  /* #104: @22 = horzcat(@28, @36, @38) */
  rr=w22;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w36; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w38; i<3; ++i) *rr++ = *cs++;
  /* #105: @29 = 0.25 */
  w29 = 2.5000000000000000e-01;
  /* #106: @15 = (@29*@15) */
  for (i=0, rr=w15, cs=wr15; i<3; ++i) (*rr++)  = (w29*(*cs++));
  /* #107: @28 = mac(@22,@15,@10) */
  casadi_copy(w10, 3, w28);
  for (i=0, rr=w28; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w22+j, ct=w15+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #108: (@25[3:6] += @28) */
  for (rr=w25+3, cs=w28; rr!=w25+6; rr+=1) *rr += *cs++;
  /* #109: @22 = mac(@15,@20,@11) */
  casadi_copy(w11, 9, w22);
  for (i=0, rr=w22; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w15+j, ct=w20+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #110: @21 = @22' */
  for (i=0, rr=w21, cs=w22; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #111: {@15, @20, @28} = horzsplit(@21) */
  casadi_copy(w21, 3, w15);
  casadi_copy(w21+3, 3, w20);
  casadi_copy(w21+6, 3, w28);
  /* #112: @28 = @28' */
  /* #113: {@29, @34, @16} = horzsplit(@28) */
  w29 = w28[0];
  w34 = w28[1];
  w16 = w28[2];
  /* #114: @39 = (@35*@16) */
  w39  = (w35*w16);
  /* #115: (@25[2] += @39) */
  for (rr=w25+2, cs=(&w39); rr!=w25+3; rr+=1) *rr += *cs++;
  /* #116: @39 = (@32*@16) */
  w39  = (w32*w16);
  /* #117: @39 = (2.*@39) */
  w39 = (2.* w39 );
  /* #118: (@25[2] += @39) */
  for (rr=w25+2, cs=(&w39); rr!=w25+3; rr+=1) *rr += *cs++;
  /* #119: @34 = (2.*@34) */
  w34 = (2.* w34 );
  /* #120: (@25[0] += @34) */
  for (rr=w25+0, cs=(&w34); rr!=w25+1; rr+=1) *rr += *cs++;
  /* #121: @39 = (@32*@34) */
  w39  = (w32*w34);
  /* #122: (@25[1] += @39) */
  for (rr=w25+1, cs=(&w39); rr!=w25+2; rr+=1) *rr += *cs++;
  /* #123: @34 = (@30*@34) */
  w34  = (w30*w34);
  /* #124: (@25[2] += @34) */
  for (rr=w25+2, cs=(&w34); rr!=w25+3; rr+=1) *rr += *cs++;
  /* #125: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #126: @34 = (-@29) */
  w34 = (- w29 );
  /* #127: (@25[1] += @34) */
  for (rr=w25+1, cs=(&w34); rr!=w25+2; rr+=1) *rr += *cs++;
  /* #128: @34 = (@32*@29) */
  w34  = (w32*w29);
  /* #129: (@25[0] += @34) */
  for (rr=w25+0, cs=(&w34); rr!=w25+1; rr+=1) *rr += *cs++;
  /* #130: @29 = (@17*@29) */
  w29  = (w17*w29);
  /* #131: (@25[2] += @29) */
  for (rr=w25+2, cs=(&w29); rr!=w25+3; rr+=1) *rr += *cs++;
  /* #132: @20 = @20' */
  /* #133: {@29, @34, @39} = horzsplit(@20) */
  w29 = w20[0];
  w34 = w20[1];
  w39 = w20[2];
  /* #134: @39 = (2.*@39) */
  w39 = (2.* w39 );
  /* #135: @40 = (-@39) */
  w40 = (- w39 );
  /* #136: (@25[0] += @40) */
  for (rr=w25+0, cs=(&w40); rr!=w25+1; rr+=1) *rr += *cs++;
  /* #137: @40 = (@30*@39) */
  w40  = (w30*w39);
  /* #138: (@25[2] += @40) */
  for (rr=w25+2, cs=(&w40); rr!=w25+3; rr+=1) *rr += *cs++;
  /* #139: @39 = (@32*@39) */
  w39  = (w32*w39);
  /* #140: (@25[1] += @39) */
  for (rr=w25+1, cs=(&w39); rr!=w25+2; rr+=1) *rr += *cs++;
  /* #141: @39 = (@31*@34) */
  w39  = (w31*w34);
  /* #142: (@25[1] += @39) */
  for (rr=w25+1, cs=(&w39); rr!=w25+2; rr+=1) *rr += *cs++;
  /* #143: @39 = (@30*@34) */
  w39  = (w30*w34);
  /* #144: @39 = (2.*@39) */
  w39 = (2.* w39 );
  /* #145: (@25[1] += @39) */
  for (rr=w25+1, cs=(&w39); rr!=w25+2; rr+=1) *rr += *cs++;
  /* #146: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #147: (@25[2] += @29) */
  for (rr=w25+2, cs=(&w29); rr!=w25+3; rr+=1) *rr += *cs++;
  /* #148: @39 = (@30*@29) */
  w39  = (w30*w29);
  /* #149: (@25[0] += @39) */
  for (rr=w25+0, cs=(&w39); rr!=w25+1; rr+=1) *rr += *cs++;
  /* #150: @29 = (@17*@29) */
  w29  = (w17*w29);
  /* #151: (@25[1] += @29) */
  for (rr=w25+1, cs=(&w29); rr!=w25+2; rr+=1) *rr += *cs++;
  /* #152: @15 = @15' */
  /* #153: {@29, @39, @40} = horzsplit(@15) */
  w29 = w15[0];
  w39 = w15[1];
  w40 = w15[2];
  /* #154: @40 = (2.*@40) */
  w40 = (2.* w40 );
  /* #155: (@25[1] += @40) */
  for (rr=w25+1, cs=(&w40); rr!=w25+2; rr+=1) *rr += *cs++;
  /* #156: @41 = (@17*@40) */
  w41  = (w17*w40);
  /* #157: (@25[2] += @41) */
  for (rr=w25+2, cs=(&w41); rr!=w25+3; rr+=1) *rr += *cs++;
  /* #158: @40 = (@32*@40) */
  w40  = (w32*w40);
  /* #159: (@25[0] += @40) */
  for (rr=w25+0, cs=(&w40); rr!=w25+1; rr+=1) *rr += *cs++;
  /* #160: @39 = (2.*@39) */
  w39 = (2.* w39 );
  /* #161: @40 = (-@39) */
  w40 = (- w39 );
  /* #162: (@25[2] += @40) */
  for (rr=w25+2, cs=(&w40); rr!=w25+3; rr+=1) *rr += *cs++;
  /* #163: @40 = (@17*@39) */
  w40  = (w17*w39);
  /* #164: (@25[1] += @40) */
  for (rr=w25+1, cs=(&w40); rr!=w25+2; rr+=1) *rr += *cs++;
  /* #165: @39 = (@30*@39) */
  w39  = (w30*w39);
  /* #166: (@25[0] += @39) */
  for (rr=w25+0, cs=(&w39); rr!=w25+1; rr+=1) *rr += *cs++;
  /* #167: @39 = (@19*@29) */
  w39  = (w19*w29);
  /* #168: (@25[0] += @39) */
  for (rr=w25+0, cs=(&w39); rr!=w25+1; rr+=1) *rr += *cs++;
  /* #169: @39 = (@17*@29) */
  w39  = (w17*w29);
  /* #170: @39 = (2.*@39) */
  w39 = (2.* w39 );
  /* #171: (@25[0] += @39) */
  for (rr=w25+0, cs=(&w39); rr!=w25+1; rr+=1) *rr += *cs++;
  /* #172: @34 = (-@34) */
  w34 = (- w34 );
  /* #173: @34 = (@34-@16) */
  w34 -= w16;
  /* #174: @34 = (@34-@29) */
  w34 -= w29;
  /* #175: @15 = (@26*@34) */
  for (i=0, rr=w15, cr=w26; i<3; ++i) (*rr++)  = ((*cr++)*w34);
  /* #176: (@25[:3] += @15) */
  for (rr=w25+0, cs=w15; rr!=w25+3; rr+=1) *rr += *cs++;
  /* #177: @27 = (@34*@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) (*rr++)  = (w34*(*cs++));
  /* #178: @27 = @27' */
  /* #179: (@25[:3] += @27) */
  for (rr=w25+0, cs=w27; rr!=w25+3; rr+=1) *rr += *cs++;
  /* #180: @34 = 4 */
  w34 = 4.;
  /* #181: @27 = input[3][1] */
  casadi_copy(arg[3] ? arg[3]+6 : 0, 3, w27);
  /* #182: @29 = @27[0] */
  for (rr=(&w29), cs=w27+0; cs!=w27+1; cs+=1) *rr++ = *cs;
  /* #183: @16 = (2.*@29) */
  w16 = (2.* w29 );
  /* #184: @16 = (@16*@29) */
  w16 *= w29;
  /* #185: @39 = ||@27||_F */
  w39 = casadi_norm_2(3, w27);
  /* #186: @39 = sq(@39) */
  w39 = casadi_sq( w39 );
  /* #187: @16 = (@16-@39) */
  w16 -= w39;
  /* #188: @16 = (@34*@16) */
  w16  = (w34*w16);
  /* #189: @40 = (@1-@39) */
  w40  = (w01-w39);
  /* #190: @41 = sq(@40) */
  w41 = casadi_sq( w40 );
  /* #191: @16 = (@16+@41) */
  w16 += w41;
  /* #192: @21 = @11; (@21[0] = @16) */
  casadi_copy(w11, 9, w21);
  for (rr=w21+0, cs=(&w16); rr!=w21+1; rr+=1) *rr = *cs++;
  /* #193: @16 = 8 */
  w16 = 8.;
  /* #194: @42 = (@16*@29) */
  w42  = (w16*w29);
  /* #195: @43 = @27[1] */
  for (rr=(&w43), cs=w27+1; cs!=w27+2; cs+=1) *rr++ = *cs;
  /* #196: @44 = (@42*@43) */
  w44  = (w42*w43);
  /* #197: @45 = @27[2] */
  for (rr=(&w45), cs=w27+2; cs!=w27+3; cs+=1) *rr++ = *cs;
  /* #198: @46 = (@34*@45) */
  w46  = (w34*w45);
  /* #199: @46 = (@46*@40) */
  w46 *= w40;
  /* #200: @44 = (@44+@46) */
  w44 += w46;
  /* #201: (@21[3] = @44) */
  for (rr=w21+3, cs=(&w44); rr!=w21+4; rr+=1) *rr = *cs++;
  /* #202: @42 = (@42*@45) */
  w42 *= w45;
  /* #203: @44 = (@34*@43) */
  w44  = (w34*w43);
  /* #204: @44 = (@44*@40) */
  w44 *= w40;
  /* #205: @42 = (@42-@44) */
  w42 -= w44;
  /* #206: (@21[6] = @42) */
  for (rr=w21+6, cs=(&w42); rr!=w21+7; rr+=1) *rr = *cs++;
  /* #207: @42 = (@16*@43) */
  w42  = (w16*w43);
  /* #208: @47 = (@42*@29) */
  w47  = (w42*w29);
  /* #209: @47 = (@47-@46) */
  w47 -= w46;
  /* #210: (@21[1] = @47) */
  for (rr=w21+1, cs=(&w47); rr!=w21+2; rr+=1) *rr = *cs++;
  /* #211: @47 = (2.*@43) */
  w47 = (2.* w43 );
  /* #212: @47 = (@47*@43) */
  w47 *= w43;
  /* #213: @47 = (@47-@39) */
  w47 -= w39;
  /* #214: @47 = (@34*@47) */
  w47  = (w34*w47);
  /* #215: @47 = (@47+@41) */
  w47 += w41;
  /* #216: (@21[4] = @47) */
  for (rr=w21+4, cs=(&w47); rr!=w21+5; rr+=1) *rr = *cs++;
  /* #217: @42 = (@42*@45) */
  w42 *= w45;
  /* #218: @47 = (@34*@29) */
  w47  = (w34*w29);
  /* #219: @47 = (@47*@40) */
  w47 *= w40;
  /* #220: @42 = (@42+@47) */
  w42 += w47;
  /* #221: (@21[7] = @42) */
  for (rr=w21+7, cs=(&w42); rr!=w21+8; rr+=1) *rr = *cs++;
  /* #222: @42 = (@16*@45) */
  w42  = (w16*w45);
  /* #223: @29 = (@42*@29) */
  w29  = (w42*w29);
  /* #224: @29 = (@29+@44) */
  w29 += w44;
  /* #225: (@21[2] = @29) */
  for (rr=w21+2, cs=(&w29); rr!=w21+3; rr+=1) *rr = *cs++;
  /* #226: @42 = (@42*@43) */
  w42 *= w43;
  /* #227: @42 = (@42-@47) */
  w42 -= w47;
  /* #228: (@21[5] = @42) */
  for (rr=w21+5, cs=(&w42); rr!=w21+6; rr+=1) *rr = *cs++;
  /* #229: @42 = (2.*@45) */
  w42 = (2.* w45 );
  /* #230: @42 = (@42*@45) */
  w42 *= w45;
  /* #231: @42 = (@42-@39) */
  w42 -= w39;
  /* #232: @42 = (@34*@42) */
  w42  = (w34*w42);
  /* #233: @42 = (@42+@41) */
  w42 += w41;
  /* #234: (@21[8] = @42) */
  for (rr=w21+8, cs=(&w42); rr!=w21+9; rr+=1) *rr = *cs++;
  /* #235: @39 = (@1+@39) */
  w39  = (w01+w39);
  /* #236: @39 = sq(@39) */
  w39 = casadi_sq( w39 );
  /* #237: @21 = (@21/@39) */
  for (i=0, rr=w21; i<9; ++i) (*rr++) /= w39;
  /* #238: @22 = @21' */
  for (i=0, rr=w22, cs=w21; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #239: @48 = 
  [[0, 0, 0], 
   [0, 0, 0], 
   [0, 0, 0], 
   [1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  wr48 = casadi_c1;
  /* #240: @49 = @48' */
  for (i=0, rr=w49, cs=wr48; i<3; ++i) for (j=0; j<6; ++j) rr[i+j*3] = *cs++;
  /* #241: @39 = 0.0595238 */
  w39 = 5.9523809523809521e-02;
  /* #242: @12 = (@39*@24) */
  for (i=0, rr=w12, cs=wr24; i<6; ++i) (*rr++)  = (w39*(*cs++));
  /* #243: @27 = mac(@49,@12,@10) */
  casadi_copy(w10, 3, w27);
  for (i=0, rr=w27; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w49+j, ct=w12+i*6; k<6; ++k) *rr += cs[k*3]**ct++;
  /* #244: @50 = 
  [[1, 1, 0, 0, 0, 0, 0, 0], 
   [0, 0, 1, 1, 0, 0, 0, 0], 
   [0, 0, 0, 0, 1, 1, 1, 1]] */
  wr50 = casadi_c2;
  /* #245: @39 = 1.6 */
  w39 = 1.6000000000000001e+00;
  /* #246: @51 = input[2][0] */
  wr51 = arg[2] ? arg[2] : casadi_zeros;
  /* #247: @51 = (@39*@51) */
  for (i=0, rr=w51, cs=wr51; i<8; ++i) (*rr++)  = (w39*(*cs++));
  /* #248: @15 = mac(@50,@51,@10) */
  casadi_copy(w10, 3, w15);
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr50+j, ct=w51+i*8; k<8; ++k) *rr += cs[k*3]**ct++;
  /* #249: @15 = @15' */
  /* #250: @23 = mac(@27,@15,@11) */
  casadi_copy(w11, 9, w23);
  for (i=0, rr=w23; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w27+j, ct=w15+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #251: @52 = mac(@22,@23,@11) */
  casadi_copy(w11, 9, w52);
  for (i=0, rr=w52; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w22+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #252: @22 = @52' */
  for (i=0, rr=w22, cs=w52; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #253: @42 = ||@26||_F */
  w42 = casadi_norm_2(3, w26);
  /* #254: @41 = sq(@42) */
  w41 = casadi_sq( w42 );
  /* #255: @45 = (@1+@41) */
  w45  = (w01+w41);
  /* #256: @47 = sq(@45) */
  w47 = casadi_sq( w45 );
  /* #257: @52 = (@22/@47) */
  for (i=0, rr=w52, cr=w22; i<9; ++i) (*rr++)  = ((*cr++)/w47);
  /* #258: @43 = @52[8] */
  for (rr=(&w43), cs=w52+8; cs!=w52+9; cs+=1) *rr++ = *cs;
  /* #259: @29 = (@34*@43) */
  w29  = (w34*w43);
  /* #260: @35 = (@35*@29) */
  w35 *= w29;
  /* #261: @44 = (@32*@29) */
  w44  = (w32*w29);
  /* #262: @44 = (2.*@44) */
  w44 = (2.* w44 );
  /* #263: @35 = (@35+@44) */
  w35 += w44;
  /* #264: (@52[8] = @2) */
  for (rr=w52+8, cs=(&w02); rr!=w52+9; rr+=1) *rr = *cs++;
  /* #265: @44 = @52[5] */
  for (rr=(&w44), cs=w52+5; cs!=w52+6; cs+=1) *rr++ = *cs;
  /* #266: @40 = (@30*@44) */
  w40  = (w30*w44);
  /* #267: @40 = (@16*@40) */
  w40  = (w16*w40);
  /* #268: @35 = (@35+@40) */
  w35 += w40;
  /* #269: (@52[5] = @2) */
  for (rr=w52+5, cs=(&w02); rr!=w52+6; rr+=1) *rr = *cs++;
  /* #270: @40 = @52[2] */
  for (rr=(&w40), cs=w52+2; cs!=w52+3; cs+=1) *rr++ = *cs;
  /* #271: @46 = (@17*@40) */
  w46  = (w17*w40);
  /* #272: @46 = (@16*@46) */
  w46  = (w16*w46);
  /* #273: @35 = (@35+@46) */
  w35 += w46;
  /* #274: @46 = (@16*@30) */
  w46  = (w16*w30);
  /* #275: (@52[2] = @2) */
  for (rr=w52+2, cs=(&w02); rr!=w52+3; rr+=1) *rr = *cs++;
  /* #276: @53 = @52[7] */
  for (rr=(&w53), cs=w52+7; cs!=w52+8; cs+=1) *rr++ = *cs;
  /* #277: @54 = (@46*@53) */
  w54  = (w46*w53);
  /* #278: @35 = (@35+@54) */
  w35 += w54;
  /* #279: @1 = (@1-@41) */
  w01 -= w41;
  /* #280: (@52[7] = @2) */
  for (rr=w52+7, cs=(&w02); rr!=w52+8; rr+=1) *rr = *cs++;
  /* #281: @23 = @52; (@23[4] = @2) */
  casadi_copy(w52, 9, w23);
  for (rr=w23+4, cs=(&w02); rr!=w23+5; rr+=1) *rr = *cs++;
  /* #282: @54 = @23[1] */
  for (rr=(&w54), cs=w23+1; cs!=w23+2; cs+=1) *rr++ = *cs;
  /* #283: @55 = (@1*@54) */
  w55  = (w01*w54);
  /* #284: @55 = (@34*@55) */
  w55  = (w34*w55);
  /* #285: @35 = (@35-@55) */
  w35 -= w55;
  /* #286: @55 = (@16*@17) */
  w55  = (w16*w17);
  /* #287: (@23[1] = @2) */
  for (rr=w23+1, cs=(&w02); rr!=w23+2; rr+=1) *rr = *cs++;
  /* #288: @56 = @23[6] */
  for (rr=(&w56), cs=w23+6; cs!=w23+7; cs+=1) *rr++ = *cs;
  /* #289: @57 = (@55*@56) */
  w57  = (w55*w56);
  /* #290: @35 = (@35+@57) */
  w35 += w57;
  /* #291: (@23[6] = @2) */
  for (rr=w23+6, cs=(&w02); rr!=w23+7; rr+=1) *rr = *cs++;
  /* #292: @57 = @23[3] */
  for (rr=(&w57), cs=w23+3; cs!=w23+4; cs+=1) *rr++ = *cs;
  /* #293: @58 = (@1*@57) */
  w58  = (w01*w57);
  /* #294: @58 = (@34*@58) */
  w58  = (w34*w58);
  /* #295: @35 = (@35+@58) */
  w35 += w58;
  /* #296: (@25[2] += @35) */
  for (rr=w25+2, cs=(&w35); rr!=w25+3; rr+=1) *rr += *cs++;
  /* #297: @35 = (@16*@32) */
  w35  = (w16*w32);
  /* #298: @58 = (@35*@44) */
  w58  = (w35*w44);
  /* #299: @59 = (@1*@40) */
  w59  = (w01*w40);
  /* #300: @59 = (@34*@59) */
  w59  = (w34*w59);
  /* #301: @58 = (@58+@59) */
  w58 += w59;
  /* #302: @59 = (@32*@53) */
  w59  = (w32*w53);
  /* #303: @59 = (@16*@59) */
  w59  = (w16*w59);
  /* #304: @58 = (@58+@59) */
  w58 += w59;
  /* #305: @59 = @52[4] */
  for (rr=(&w59), cs=w52+4; cs!=w52+5; cs+=1) *rr++ = *cs;
  /* #306: @60 = (@34*@59) */
  w60  = (w34*w59);
  /* #307: @31 = (@31*@60) */
  w31 *= w60;
  /* #308: @58 = (@58+@31) */
  w58 += w31;
  /* #309: @31 = (@30*@60) */
  w31  = (w30*w60);
  /* #310: @31 = (2.*@31) */
  w31 = (2.* w31 );
  /* #311: @58 = (@58+@31) */
  w58 += w31;
  /* #312: @31 = (@17*@54) */
  w31  = (w17*w54);
  /* #313: @31 = (@16*@31) */
  w31  = (w16*w31);
  /* #314: @58 = (@58+@31) */
  w58 += w31;
  /* #315: @31 = (@1*@56) */
  w31  = (w01*w56);
  /* #316: @31 = (@34*@31) */
  w31  = (w34*w31);
  /* #317: @58 = (@58-@31) */
  w58 -= w31;
  /* #318: @31 = (@55*@57) */
  w31  = (w55*w57);
  /* #319: @58 = (@58+@31) */
  w58 += w31;
  /* #320: (@25[1] += @58) */
  for (rr=w25+1, cs=(&w58); rr!=w25+2; rr+=1) *rr += *cs++;
  /* #321: @58 = (2.*@42) */
  w58 = (2.* w42 );
  /* #322: @18 = (@18-@41) */
  w18 -= w41;
  /* #323: @18 = (@34*@18) */
  w18  = (w34*w18);
  /* #324: @31 = sq(@1) */
  w31 = casadi_sq( w01 );
  /* #325: @18 = (@18+@31) */
  w18 += w31;
  /* #326: @52 = @11; (@52[0] = @18) */
  casadi_copy(w11, 9, w52);
  for (rr=w52+0, cs=(&w18); rr!=w52+1; rr+=1) *rr = *cs++;
  /* #327: @18 = (@55*@30) */
  w18  = (w55*w30);
  /* #328: @61 = (@34*@32) */
  w61  = (w34*w32);
  /* #329: @62 = (@61*@1) */
  w62  = (w61*w01);
  /* #330: @18 = (@18+@62) */
  w18 += w62;
  /* #331: (@52[3] = @18) */
  for (rr=w52+3, cs=(&w18); rr!=w52+4; rr+=1) *rr = *cs++;
  /* #332: @55 = (@55*@32) */
  w55 *= w32;
  /* #333: @18 = (@34*@30) */
  w18  = (w34*w30);
  /* #334: @63 = (@18*@1) */
  w63  = (w18*w01);
  /* #335: @55 = (@55-@63) */
  w55 -= w63;
  /* #336: (@52[6] = @55) */
  for (rr=w52+6, cs=(&w55); rr!=w52+7; rr+=1) *rr = *cs++;
  /* #337: @55 = (@46*@17) */
  w55  = (w46*w17);
  /* #338: @55 = (@55-@62) */
  w55 -= w62;
  /* #339: (@52[1] = @55) */
  for (rr=w52+1, cs=(&w55); rr!=w52+2; rr+=1) *rr = *cs++;
  /* #340: @33 = (@33-@41) */
  w33 -= w41;
  /* #341: @33 = (@34*@33) */
  w33  = (w34*w33);
  /* #342: @33 = (@33+@31) */
  w33 += w31;
  /* #343: (@52[4] = @33) */
  for (rr=w52+4, cs=(&w33); rr!=w52+5; rr+=1) *rr = *cs++;
  /* #344: @33 = (@46*@32) */
  w33  = (w46*w32);
  /* #345: @55 = (@34*@17) */
  w55  = (w34*w17);
  /* #346: @62 = (@55*@1) */
  w62  = (w55*w01);
  /* #347: @33 = (@33+@62) */
  w33 += w62;
  /* #348: (@52[7] = @33) */
  for (rr=w52+7, cs=(&w33); rr!=w52+8; rr+=1) *rr = *cs++;
  /* #349: @33 = (@35*@17) */
  w33  = (w35*w17);
  /* #350: @33 = (@33+@63) */
  w33 += w63;
  /* #351: (@52[2] = @33) */
  for (rr=w52+2, cs=(&w33); rr!=w52+3; rr+=1) *rr = *cs++;
  /* #352: @33 = (@35*@30) */
  w33  = (w35*w30);
  /* #353: @33 = (@33-@62) */
  w33 -= w62;
  /* #354: (@52[5] = @33) */
  for (rr=w52+5, cs=(&w33); rr!=w52+6; rr+=1) *rr = *cs++;
  /* #355: @37 = (@37-@41) */
  w37 -= w41;
  /* #356: @37 = (@34*@37) */
  w37  = (w34*w37);
  /* #357: @37 = (@37+@31) */
  w37 += w31;
  /* #358: (@52[8] = @37) */
  for (rr=w52+8, cs=(&w37); rr!=w52+9; rr+=1) *rr = *cs++;
  /* #359: @52 = (@52/@47) */
  for (i=0, rr=w52; i<9; ++i) (*rr++) /= w47;
  /* #360: @64 = (@52/@47) */
  for (i=0, rr=w64, cr=w52; i<9; ++i) (*rr++)  = ((*cr++)/w47);
  /* #361: @64 = (-@64) */
  for (i=0, rr=w64, cs=w64; i<9; ++i) *rr++ = (- *cs++ );
  /* #362: @47 = dot(@64, @22) */
  w47 = casadi_dot(9, w64, w22);
  /* #363: @45 = (@45*@47) */
  w45 *= w47;
  /* #364: @45 = (2.*@45) */
  w45 = (2.* w45 );
  /* #365: @45 = (@45-@29) */
  w45 -= w29;
  /* #366: @45 = (@45-@60) */
  w45 -= w60;
  /* #367: @60 = (2.*@1) */
  w60 = (2.* w01 );
  /* #368: @43 = (@60*@43) */
  w43  = (w60*w43);
  /* #369: @29 = (@55*@44) */
  w29  = (w55*w44);
  /* #370: @43 = (@43-@29) */
  w43 -= w29;
  /* #371: @29 = (@18*@40) */
  w29  = (w18*w40);
  /* #372: @43 = (@43+@29) */
  w43 += w29;
  /* #373: @55 = (@55*@53) */
  w55 *= w53;
  /* #374: @43 = (@43+@55) */
  w43 += w55;
  /* #375: @59 = (@60*@59) */
  w59  = (w60*w59);
  /* #376: @43 = (@43+@59) */
  w43 += w59;
  /* #377: @59 = (@61*@54) */
  w59  = (w61*w54);
  /* #378: @43 = (@43-@59) */
  w43 -= w59;
  /* #379: @18 = (@18*@56) */
  w18 *= w56;
  /* #380: @43 = (@43-@18) */
  w43 -= w18;
  /* #381: @61 = (@61*@57) */
  w61 *= w57;
  /* #382: @43 = (@43+@61) */
  w43 += w61;
  /* #383: (@23[3] = @2) */
  for (rr=w23+3, cs=(&w02); rr!=w23+4; rr+=1) *rr = *cs++;
  /* #384: @61 = @23[0] */
  for (rr=(&w61), cs=w23+0; cs!=w23+1; cs+=1) *rr++ = *cs;
  /* #385: @60 = (@60*@61) */
  w60 *= w61;
  /* #386: @43 = (@43+@60) */
  w43 += w60;
  /* #387: @45 = (@45-@43) */
  w45 -= w43;
  /* #388: @61 = (@34*@61) */
  w61  = (w34*w61);
  /* #389: @45 = (@45-@61) */
  w45 -= w61;
  /* #390: @58 = (@58*@45) */
  w58 *= w45;
  /* #391: @58 = (@58/@42) */
  w58 /= w42;
  /* #392: @26 = (@58*@26) */
  for (i=0, rr=w26, cs=w26; i<3; ++i) (*rr++)  = (w58*(*cs++));
  /* #393: (@25[:3] += @26) */
  for (rr=w25+0, cs=w26; rr!=w25+3; rr+=1) *rr += *cs++;
  /* #394: @35 = (@35*@40) */
  w35 *= w40;
  /* #395: @44 = (@1*@44) */
  w44  = (w01*w44);
  /* #396: @44 = (@34*@44) */
  w44  = (w34*w44);
  /* #397: @35 = (@35-@44) */
  w35 -= w44;
  /* #398: @1 = (@1*@53) */
  w01 *= w53;
  /* #399: @34 = (@34*@1) */
  w34 *= w01;
  /* #400: @35 = (@35+@34) */
  w35 += w34;
  /* #401: @46 = (@46*@54) */
  w46 *= w54;
  /* #402: @35 = (@35+@46) */
  w35 += w46;
  /* #403: @32 = (@32*@56) */
  w32 *= w56;
  /* #404: @32 = (@16*@32) */
  w32  = (w16*w32);
  /* #405: @35 = (@35+@32) */
  w35 += w32;
  /* #406: @30 = (@30*@57) */
  w30 *= w57;
  /* #407: @16 = (@16*@30) */
  w16 *= w30;
  /* #408: @35 = (@35+@16) */
  w35 += w16;
  /* #409: @19 = (@19*@61) */
  w19 *= w61;
  /* #410: @35 = (@35+@19) */
  w35 += w19;
  /* #411: @17 = (@17*@61) */
  w17 *= w61;
  /* #412: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #413: @35 = (@35+@17) */
  w35 += w17;
  /* #414: (@25[0] += @35) */
  for (rr=w25+0, cs=(&w35); rr!=w25+1; rr+=1) *rr += *cs++;
  /* #415: @26 = @25[:3] */
  for (rr=w26, cs=w25+0; cs!=w25+3; cs+=1) *rr++ = *cs;
  /* #416: @15 = (@8?@26:0) */
  for (i=0, rr=w15, cs=w26; i<3; ++i) (*rr++)  = (w08?cs[i]:0);
  /* #417: @20 = (@26/@6) */
  for (i=0, rr=w20, cr=w26; i<3; ++i) (*rr++)  = ((*cr++)/w06);
  /* #418: @20 = (-@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) *rr++ = (- *cs++ );
  /* #419: @20 = (@7?@20:0) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) (*rr++)  = (w07?cs[i]:0);
  /* #420: @15 = (@15+@20) */
  for (i=0, rr=w15, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #421: @13 = (@13/@6) */
  for (i=0, rr=w13; i<3; ++i) (*rr++) /= w06;
  /* #422: @13 = (-@13) */
  for (i=0, rr=w13, cs=w13; i<3; ++i) *rr++ = (- *cs++ );
  /* #423: @26 = (-@26) */
  for (i=0, rr=w26, cs=w26; i<3; ++i) *rr++ = (- *cs++ );
  /* #424: @26 = (@7?@26:0) */
  for (i=0, rr=w26, cs=w26; i<3; ++i) (*rr++)  = (w07?cs[i]:0);
  /* #425: @7 = dot(@13, @26) */
  w07 = casadi_dot(3, w13, w26);
  /* #426: @4 = (@4*@7) */
  for (i=0, rr=w04, cr=wr04; i<3; ++i) (*rr++)  = ((*cr++)*w07);
  /* #427: @15 = (@15+@4) */
  for (i=0, rr=w15, cs=w04; i<3; ++i) (*rr++) += (*cs++);
  /* #428: @5 = (@7*@5) */
  for (i=0, rr=w05, cs=wr05; i<3; ++i) (*rr++)  = (w07*(*cs++));
  /* #429: @5 = @5' */
  /* #430: @15 = (@15+@5) */
  for (i=0, rr=w15, cs=w05; i<3; ++i) (*rr++) += (*cs++);
  /* #431: (@0[6:9] += @15) */
  for (rr=w00+6, cs=w15; rr!=w00+9; rr+=1) *rr += *cs++;
  /* #432: (@25[:3] = @10) */
  for (rr=w25+0, cs=w10; rr!=w25+3; rr+=1) *rr = *cs++;
  /* #433: (@0[6:12] += @25) */
  for (rr=w00+6, cs=w25; rr!=w00+12; rr+=1) *rr += *cs++;
  /* #434: @25 = [[0, 0, 0, 1, 0, 0]] */
  casadi_copy(casadi_c3, 6, w25);
  /* #435: @25 = @25' */
  /* #436: @12 = [[0, 0, 0, 0, 1, 0]] */
  casadi_copy(casadi_c4, 6, w12);
  /* #437: @12 = @12' */
  /* #438: @65 = [[0, 0, 0, 0, 0, 1]] */
  casadi_copy(casadi_c5, 6, w65);
  /* #439: @65 = @65' */
  /* #440: @7 = 3 */
  w07 = 3.;
  /* #441: @6 = input[3][2] */
  w06 = arg[3] ? arg[3][9] : 0;
  /* #442: @8 = sq(@6) */
  w08 = casadi_sq( w06 );
  /* #443: @7 = (@7*@8) */
  w07 *= w08;
  /* #444: @35 = (2.*@6) */
  w35 = (2.* w06 );
  /* #445: @66 = horzcat(@7, @2, @2, @2, @35, @2) */
  rr=w66;
  *rr++ = w07;
  *rr++ = w02;
  *rr++ = w02;
  *rr++ = w02;
  *rr++ = w35;
  *rr++ = w02;
  /* #446: @66 = @66' */
  /* #447: @7 = -2 */
  w07 = -2.;
  /* #448: @7 = (@7*@6) */
  w07 *= w06;
  /* #449: @67 = horzcat(@2, @2, @2, @7, @2, @2) */
  rr=w67;
  *rr++ = w02;
  *rr++ = w02;
  *rr++ = w02;
  *rr++ = w07;
  *rr++ = w02;
  *rr++ = w02;
  /* #450: @67 = @67' */
  /* #451: @8 = (-@8) */
  w08 = (- w08 );
  /* #452: @68 = horzcat(@2, @2, @8, @2, @2, @2) */
  rr=w68;
  *rr++ = w02;
  *rr++ = w02;
  *rr++ = w08;
  *rr++ = w02;
  *rr++ = w02;
  *rr++ = w02;
  /* #453: @68 = @68' */
  /* #454: @69 = horzcat(@25, @12, @65, @66, @67, @68) */
  rr=w69;
  for (i=0, cs=w25; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w65; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w66; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w67; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w68; i<6; ++i) *rr++ = *cs++;
  /* #455: @9 = mac(@69,@24,@9) */
  for (i=0, rr=w09; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, cs=w69+j, ct=wr24+i*6; k<6; ++k) *rr += cs[k*6]**ct++;
  /* #456: (@0[:6] += @9) */
  for (rr=w00+0, cs=w09; rr!=w00+6; rr+=1) *rr += *cs++;
  /* #457: output[0][0] = @0 */
  casadi_copy(w00, 12, res[0]);
  /* #458: @51 = zeros(8x1) */
  casadi_clear(w51, 8);
  /* #459: @70 = 
  [[0, -0, 0, 0, 0.12, 0.12, -0.12, -0.12], 
   [0, 0, 0, 0, -0.12, 0.12, -0.12, 0.12], 
   [-0.12, 0.12, 0.12, -0.12, 0, -0, 0, 0]] */
  wr70 = casadi_c6;
  /* #460: @71 = @70' */
  for (i=0, rr=w71, cs=wr70; i<8; ++i) for (j=0; j<3; ++j) rr[i+j*8] = *cs++;
  /* #461: @72 = mac(@71,@14,@51) */
  casadi_copy(w51, 8, w72);
  for (i=0, rr=w72; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, cs=w71+j, ct=w14+i*3; k<3; ++k) *rr += cs[k*8]**ct++;
  /* #462: @72 = (@39*@72) */
  for (i=0, rr=w72, cs=w72; i<8; ++i) (*rr++)  = (w39*(*cs++));
  /* #463: @71 = @50' */
  for (i=0, rr=w71, cs=wr50; i<8; ++i) for (j=0; j<3; ++j) rr[i+j*8] = *cs++;
  /* #464: @23 = @52' */
  for (i=0, rr=w23, cs=w52; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #465: @11 = mac(@21,@23,@11) */
  for (i=0, rr=w11; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w21+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #466: @21 = @11' */
  for (i=0, rr=w21, cs=w11; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #467: @10 = mac(@21,@27,@10) */
  for (i=0, rr=w10; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w21+j, ct=w27+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #468: @51 = mac(@71,@10,@51) */
  for (i=0, rr=w51; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, cs=w71+j, ct=w10+i*3; k<3; ++k) *rr += cs[k*8]**ct++;
  /* #469: @51 = (@39*@51) */
  for (i=0, rr=w51, cs=w51; i<8; ++i) (*rr++)  = (w39*(*cs++));
  /* #470: @72 = (@72+@51) */
  for (i=0, rr=w72, cs=w51; i<8; ++i) (*rr++) += (*cs++);
  /* #471: output[0][1] = @72 */
  if (res[0]) casadi_copy(w72, 8, res[0]+12);
  return 0;
}

CASADI_SYMBOL_EXPORT int satellite_full_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int satellite_full_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int satellite_full_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void satellite_full_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int satellite_full_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void satellite_full_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void satellite_full_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void satellite_full_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int satellite_full_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int satellite_full_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real satellite_full_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* satellite_full_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* satellite_full_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* satellite_full_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* satellite_full_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int satellite_full_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 367;
  return 0;
}

CASADI_SYMBOL_EXPORT int satellite_full_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 367*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
