MAX_WAIT_SECONDS_BEFORE_SHUTDOWN = 1

# Messaging commands
TICK = "TICK"
TOCK = "TOCK"
UNKNOWN_MSGS = "UNKNOWN_MSGS"
MATCH_MSGS = "MATCH_MSGS"
START = "START"
STARTED = "STARTED"
FINISH = "FINISH"
FINISHED = "FINISHED"
HANDSHAKE = "HANDSHAKE"
HANDSHAKEN = "HANDSHAKEN"
LOGS = "LOGS"

# Packaging types
CCSDS = "CCSDS_packet"
BSK = "BSK_packet"
VIZ = "VIZ_packet"
