/*
 ISC License

 Copyright (c) 2026, Autonomous Vehicle Systems Lab, University of Colorado at Boulder

 Permission to use, copy, modify, and/or distribute this software for any
 purpose with or without fee is hereby granted, provided that the above
 copyright notice and this permission notice appear in all copies.

 THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
*/

#include "architecture/utilities/bskAbiDescriptor.h"

#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>

#ifndef BSK_BUILD_CONFIGURATION
#define BSK_BUILD_CONFIGURATION ""
#endif

#ifndef BSK_PYTHON_SOABI
#define BSK_PYTHON_SOABI ""
#endif

#ifndef BSK_SWIG_RUNTIME_VERSION
#define BSK_SWIG_RUNTIME_VERSION ""
#endif

extern "C" const BskCAbiInfo*
bskGetCompiledCAbiInfo(void);

namespace {

std::string
pythonString(const std::string& value)
{
    std::ostringstream result;
    result << '"';
    for (const unsigned char character : value) {
        switch (character) {
            case '\\':
                result << "\\\\";
                break;
            case '"':
                result << "\\\"";
                break;
            case '\n':
                result << "\\n";
                break;
            case '\r':
                result << "\\r";
                break;
            case '\t':
                result << "\\t";
                break;
            default:
                if (character < 0x20) {
                    result << "\\x" << std::hex << std::setw(2) << std::setfill('0')
                           << static_cast<unsigned int>(character) << std::dec;
                } else {
                    result << character;
                }
        }
    }
    result << '"';
    return result.str();
}

std::string
optionalInteger(long long value)
{
    return value < 0 ? "None" : std::to_string(value);
}

bool
writeBuildAbiData(std::ostream& output)
{
    const BskCAbiInfo& cInfo = *bskGetCompiledCAbiInfo();
    const bsk::abi::CxxAbiInfo cxxInfo = bsk::abi::createCxxAbiInfo();
    const std::string eigenVersion = std::to_string(EIGEN_WORLD_VERSION) + "." + std::to_string(EIGEN_MAJOR_VERSION) +
                                     "." + std::to_string(EIGEN_MINOR_VERSION);

    output << "# Generated by the compiled Basilisk ABI probe.\n\n"
           << "buildAbiData = {\n"
           << "    \"descriptorVersion\": " << BSK_ABI_DESCRIPTOR_VERSION << ",\n"
           << "    \"capture\": \"compiled\",\n"
           << "    \"contractHeader\": \"architecture/utilities/bskAbiDescriptor.h\",\n"
           << "    \"build\": {\n"
           << "        \"configuration\": " << pythonString(BSK_BUILD_CONFIGURATION) << ",\n"
           << "        \"debugRuntime\": " << (cxxInfo.debugRuntime ? "True" : "False") << ",\n"
           << "        \"assertionsDisabled\": " << (cxxInfo.assertionsDisabled ? "True" : "False") << ",\n"
           << "    },\n"
           << "    \"target\": {\n"
           << "        \"system\": " << pythonString(cxxInfo.targetSystem) << ",\n"
           << "        \"architecture\": " << pythonString(cxxInfo.targetArchitecture) << ",\n"
           << "        \"pointerSizeBytes\": " << sizeof(void*) << ",\n"
           << "        \"endianness\": " << pythonString(cInfo.endianness) << ",\n"
           << "        \"instructionSet\": " << pythonString(cxxInfo.instructionSet) << ",\n"
           << "    },\n"
           << "    \"c\": {\n"
           << "        \"compiler\": {\n"
           << "            \"id\": " << pythonString(cInfo.compilerId) << ",\n"
           << "            \"version\": " << pythonString(cInfo.compilerVersion) << ",\n"
           << "            \"majorVersion\": " << cInfo.compilerMajorVersion << ",\n"
           << "            \"minorVersion\": " << cInfo.compilerMinorVersion << ",\n"
           << "            \"patchVersion\": " << cInfo.compilerPatchVersion << ",\n"
           << "            \"languageStandard\": " << cInfo.languageStandard << ",\n"
           << "            \"msvcVersion\": " << cInfo.msvcVersion << ",\n"
           << "        },\n"
           << "        \"runtime\": {\n"
           << "            \"family\": " << pythonString(cInfo.runtimeFamily) << ",\n"
           << "            \"majorVersion\": " << cInfo.runtimeMajorVersion << ",\n"
           << "            \"minorVersion\": " << cInfo.runtimeMinorVersion << ",\n"
           << "        },\n"
           << "        \"fundamentalTypes\": {\n"
           << "            \"charIsSigned\": " << (cInfo.charIsSigned ? "True" : "False") << ",\n"
           << "            \"shortSize\": " << cInfo.shortSize << ",\n"
           << "            \"intSize\": " << cInfo.intSize << ",\n"
           << "            \"longSize\": " << cInfo.longSize << ",\n"
           << "            \"longLongSize\": " << cInfo.longLongSize << ",\n"
           << "            \"sizeTSize\": " << cInfo.sizeTSize << ",\n"
           << "            \"pointerSize\": " << cInfo.pointerSize << ",\n"
           << "        },\n"
           << "        \"layoutCanaries\": {\n"
           << "            \"packingCanarySize\": " << cInfo.packingCanarySize << ",\n"
           << "            \"packingCanaryAlignment\": " << cInfo.packingCanaryAlignment << ",\n"
           << "            \"packingCanaryUint32Offset\": " << cInfo.packingCanaryUint32Offset << ",\n"
           << "            \"packingCanaryUint16Offset\": " << cInfo.packingCanaryUint16Offset << ",\n"
           << "            \"msgHeaderSize\": " << cInfo.msgHeaderSize << ",\n"
           << "            \"msgHeaderAlignment\": " << cInfo.msgHeaderAlignment << ",\n"
           << "            \"msgHeaderIsWrittenOffset\": " << cInfo.msgHeaderIsWrittenOffset << ",\n"
           << "            \"msgHeaderTimeWrittenOffset\": " << cInfo.msgHeaderTimeWrittenOffset << ",\n"
           << "            \"msgHeaderModuleIdOffset\": " << cInfo.msgHeaderModuleIdOffset << ",\n"
           << "        },\n"
           << "    },\n"
           << "    \"cxx\": {\n"
           << "        \"compiler\": {\n"
           << "            \"id\": " << pythonString(cxxInfo.compilerId) << ",\n"
           << "            \"version\": " << pythonString(cxxInfo.compilerVersion) << ",\n"
           << "            \"majorVersion\": " << cxxInfo.compilerMajorVersion << ",\n"
           << "            \"minorVersion\": " << cxxInfo.compilerMinorVersion << ",\n"
           << "            \"patchVersion\": " << cxxInfo.compilerPatchVersion << ",\n"
           << "            \"frontend\": " << pythonString(cxxInfo.compilerFrontend) << ",\n"
           << "            \"languageStandard\": " << cxxInfo.compilerLanguageStandard << ",\n"
           << "            \"abiFamily\": " << pythonString(cxxInfo.compilerAbiFamily) << ",\n"
           << "            \"abiVersion\": " << cxxInfo.compilerAbiVersion << ",\n"
           << "            \"msvcFullVersion\": " << cxxInfo.msvcFullVersion << ",\n"
           << "        },\n"
           << "        \"standardLibrary\": {\n"
           << "            \"family\": " << pythonString(cxxInfo.standardLibraryFamily) << ",\n"
           << "            \"version\": " << cxxInfo.standardLibraryVersion << ",\n"
           << "            \"abiVersion\": " << cxxInfo.standardLibraryAbiVersion << ",\n"
           << "            \"libstdcxxRelease\": " << cxxInfo.libstdcxxRelease << ",\n"
           << "            \"msvcStlUpdate\": " << cxxInfo.msvcStlUpdate << ",\n"
           << "            \"useCxx11Abi\": " << optionalInteger(cxxInfo.libstdcxxUseCxx11Abi) << ",\n"
           << "            \"iteratorDebugLevel\": " << optionalInteger(cxxInfo.iteratorDebugLevel) << ",\n"
           << "            \"debugMode\": " << (cxxInfo.standardLibraryDebugMode ? "True" : "False") << ",\n"
           << "            \"assertionsEnabled\": " << (cxxInfo.standardLibraryAssertions ? "True" : "False") << ",\n"
           << "        },\n"
           << "        \"runtime\": {\n"
           << "            \"linkage\": " << pythonString(cxxInfo.runtimeLinkage) << ",\n"
           << "            \"debug\": " << (cxxInfo.debugRuntime ? "True" : "False") << ",\n"
           << "            \"exceptions\": " << (cxxInfo.exceptionsEnabled ? "True" : "False") << ",\n"
           << "            \"rtti\": " << (cxxInfo.rttiEnabled ? "True" : "False") << ",\n"
           << "        },\n"
           << "        \"layoutCanaries\": {\n"
           << "            \"stdStringSize\": " << cxxInfo.stdStringSize << ",\n"
           << "            \"stdStringAlignment\": " << cxxInfo.stdStringAlignment << ",\n"
           << "            \"stdVectorIntSize\": " << cxxInfo.stdVectorIntSize << ",\n"
           << "            \"stdVectorIntAlignment\": " << cxxInfo.stdVectorIntAlignment << ",\n"
           << "            \"sysModelSize\": " << cxxInfo.sysModelSize << ",\n"
           << "            \"sysModelAlignment\": " << cxxInfo.sysModelAlignment << ",\n"
           << "            \"bskLoggerSize\": " << cxxInfo.bskLoggerSize << ",\n"
           << "            \"bskLoggerAlignment\": " << cxxInfo.bskLoggerAlignment << ",\n"
           << "            \"msgHeaderSize\": " << cxxInfo.msgHeaderSize << ",\n"
           << "            \"msgHeaderAlignment\": " << cxxInfo.msgHeaderAlignment << ",\n"
           << "            \"readFunctorSize\": " << cxxInfo.readFunctorSize << ",\n"
           << "            \"readFunctorAlignment\": " << cxxInfo.readFunctorAlignment << ",\n"
           << "            \"messageSize\": " << cxxInfo.messageSize << ",\n"
           << "            \"messageAlignment\": " << cxxInfo.messageAlignment << ",\n"
           << "        },\n"
           << "    },\n"
           << "    \"dependencies\": {\n"
           << "        \"eigen\": {\n"
           << "            \"version\": " << pythonString(eigenVersion) << ",\n"
           << "            \"maxAlignBytes\": " << cxxInfo.eigenMaxAlignBytes << ",\n"
           << "            \"maxStaticAlignBytes\": " << cxxInfo.eigenMaxStaticAlignBytes << ",\n"
           << "            \"vectorization\": " << pythonString(cxxInfo.eigenVectorization) << ",\n"
           << "            \"indexSize\": " << cxxInfo.eigenIndexSize << ",\n"
           << "            \"vector3dSize\": " << cxxInfo.eigenVector3dSize << ",\n"
           << "            \"vector3dAlignment\": " << cxxInfo.eigenVector3dAlignment << ",\n"
           << "            \"vectorXdSize\": " << cxxInfo.eigenVectorXdSize << ",\n"
           << "            \"vectorXdAlignment\": " << cxxInfo.eigenVectorXdAlignment << ",\n"
           << "            \"matrix3dSize\": " << cxxInfo.eigenMatrix3dSize << ",\n"
           << "            \"matrix3dAlignment\": " << cxxInfo.eigenMatrix3dAlignment << ",\n"
           << "        },\n"
           << "        \"swig\": {\n"
           << "            \"runtimeVersion\": " << pythonString(BSK_SWIG_RUNTIME_VERSION) << ",\n"
           << "        },\n"
           << "        \"python\": {\n"
           << "            \"implementation\": \"CPython\",\n"
           << "            \"versionMajor\": " << PY_MAJOR_VERSION << ",\n"
           << "            \"versionMinor\": " << PY_MINOR_VERSION << ",\n"
           << "            \"versionMicro\": " << PY_MICRO_VERSION << ",\n"
           << "            \"versionHex\": " << PY_VERSION_HEX << ",\n"
           << "            \"limitedApi\": " << cxxInfo.pythonLimitedApi << ",\n"
           << "            \"soabi\": " << pythonString(BSK_PYTHON_SOABI) << ",\n"
           << "            \"debug\": " << (cxxInfo.pythonDebugBuild ? "True" : "False") << ",\n"
           << "            \"freeThreaded\": " << (cxxInfo.pythonFreeThreadedBuild ? "True" : "False") << ",\n"
           << "        },\n"
           << "    },\n"
           << "}\n";

    return output.good();
}

} // namespace

int
main(int argc, char** argv)
{
    if (argc != 2) {
        std::cerr << "Usage: bskBuildInfoProbe <output-file>\n";
        return EXIT_FAILURE;
    }

    const std::filesystem::path outputPath(argv[1]);
    const std::filesystem::path temporaryPath = outputPath.string() + ".tmp";
    std::ofstream output(temporaryPath, std::ios::out | std::ios::trunc);
    if (!output || !writeBuildAbiData(output)) {
        std::cerr << "Unable to write Basilisk ABI metadata to " << temporaryPath << '\n';
        return EXIT_FAILURE;
    }
    output.close();

    std::error_code error;
    std::filesystem::remove(outputPath, error);
    error.clear();
    std::filesystem::rename(temporaryPath, outputPath, error);
    if (error) {
        std::cerr << "Unable to install Basilisk ABI metadata at " << outputPath << ": " << error.message() << '\n';
        return EXIT_FAILURE;
    }

    return EXIT_SUCCESS;
}
