# ISC License
#
# Copyright (c) 2026, Autonomous Vehicle Systems Lab, University of Colorado at Boulder
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

include_guard(GLOBAL)

# Temporary CI experiment: revert this default after cross-platform validation.
option(BSK_COMBINE_FSW_BINDINGS "Experimentally combine core FSW native bindings" ON)

function(bsk_finalize_fsw_bindings)
  get_property(OBJECT_TARGETS GLOBAL PROPERTY BSK_FSW_OBJECT_TARGETS)
  get_property(MODULE_NAMES GLOBAL PROPERTY BSK_FSW_COMBINED_MODULES)
  get_property(BINDING_TARGETS GLOBAL PROPERTY BSK_FSW_BINDING_TARGETS)
  set(PACKAGE_DIR "${CMAKE_BINARY_DIR}/Basilisk/fswAlgorithms")
  set(MANIFEST "${CMAKE_BINARY_DIR}/autoSource/fswCoreBindings.txt")
  set(STAMP "${CMAKE_BINARY_DIR}/autoSource/fswBindingsLayout.stamp")
  list(SORT MODULE_NAMES)
  string(REPLACE ";" "\n" MANIFEST_CONTENT "${MODULE_NAMES}")
  file(CONFIGURE OUTPUT "${MANIFEST}" CONTENT "${MANIFEST_CONTENT}\n" @ONLY)

  set(LAYOUT_OUTPUTS "${STAMP}")
  foreach(MODULE_NAME IN LISTS MODULE_NAMES)
    list(APPEND LAYOUT_OUTPUTS "${PACKAGE_DIR}/_${MODULE_NAME}.py")
  endforeach()
  if(OBJECT_TARGETS)
    list(APPEND LAYOUT_OUTPUTS "${PACKAGE_DIR}/_load_fsw.py")
    # Xcode needs a source on the aggregate target to create its link phase.
    # Preserve the file's timestamp so reconfiguration does not force a relink.
    set(NATIVE_SOURCE "${CMAKE_BINARY_DIR}/autoSource/fswCoreNative.cpp")
    file(CONFIGURE OUTPUT "${NATIVE_SOURCE}" CONTENT
      "// Generated by bskCombineFswBindings.cmake.\n// This empty translation unit enables the Xcode link phase.\n" @ONLY)
    add_library(fswCoreNative MODULE "${NATIVE_SOURCE}")
    target_link_libraries(fswCoreNative PRIVATE ${OBJECT_TARGETS})
    set_target_properties(fswCoreNative PROPERTIES
      PREFIX "_" NO_SONAME ON LINKER_LANGUAGE CXX FOLDER "fswAlgorithms"
      LIBRARY_OUTPUT_DIRECTORY "${PACKAGE_DIR}"
      RUNTIME_OUTPUT_DIRECTORY "${PACKAGE_DIR}"
      ARCHIVE_OUTPUT_DIRECTORY "${PACKAGE_DIR}")
    foreach(CONFIG IN ITEMS DEBUG RELEASE RELWITHDEBINFO MINSIZEREL)
      set_target_properties(fswCoreNative PROPERTIES
        LIBRARY_OUTPUT_DIRECTORY_${CONFIG} "${PACKAGE_DIR}"
        RUNTIME_OUTPUT_DIRECTORY_${CONFIG} "${PACKAGE_DIR}"
        ARCHIVE_OUTPUT_DIRECTORY_${CONFIG} "${PACKAGE_DIR}")
    endforeach()
    if(WIN32)
      set_target_properties(fswCoreNative PROPERTIES SUFFIX ".pyd")
    endif()
    list(APPEND BINDING_TARGETS fswCoreNative)
  endif()

  add_custom_command(
    OUTPUT ${LAYOUT_OUTPUTS}
    COMMAND "${Python3_EXECUTABLE}" "${CMAKE_SOURCE_DIR}/cmake/generateFswBindings.py"
            "${MANIFEST}" "${PACKAGE_DIR}" "${CMAKE_SOURCE_DIR}/fswAlgorithms/_load_fsw.py"
    COMMAND "${CMAKE_COMMAND}" -E touch "${STAMP}"
    DEPENDS "${MANIFEST}" "${CMAKE_SOURCE_DIR}/cmake/generateFswBindings.py"
            "${CMAKE_SOURCE_DIR}/fswAlgorithms/_load_fsw.py"
    COMMENT "Updating the FSW binding layout"
    VERBATIM)
  add_custom_target(fswBindingsLayout DEPENDS ${LAYOUT_OUTPUTS})
  foreach(BINDING_TARGET IN LISTS BINDING_TARGETS)
    add_dependencies(${BINDING_TARGET} fswBindingsLayout)
  endforeach()
endfunction()

function(bsk_isolate_fsw_symbols MODULE_NAME)
  # Historically these helpers had external linkage in separate libraries.
  # Prefix their compiled C symbols within the combined library, including calls
  # from the generated wrapper. Do not pass the definitions to SWIG: its public
  # Python names must remain unchanged.
  set(SYMBOLS)
  if(MODULE_NAME MATCHES "^(okeefeEKF|sunlineEKF|sunlineSEKF)$")
    list(APPEND SYMBOLS sunlineMeasUpdate sunlineStateSTMProp sunlineHMatrixYMeas sunlineTimeUpdate)
  endif()
  if(MODULE_NAME MATCHES "^(sunlineEKF|sunlineSEKF)$")
    list(APPEND SYMBOLS sunlineCKFUpdate sunlineDynMatrix sunlineKalmanGain)
  endif()
  if(MODULE_NAME MATCHES "^(sunlineSuKF|sunlineUKF)$")
    list(APPEND SYMBOLS sunlineStateProp)
  endif()
  if(MODULE_NAME MATCHES "^(eulerRotation|mrpRotation)$")
    list(APPEND SYMBOLS checkRasterCommands computeTimeStep)
  endif()
  if(MODULE_NAME MATCHES "^(pixelLineBiasUKF|relativeODuKF)$")
    list(APPEND SYMBOLS relODStateProp)
  endif()
  foreach(SYMBOL IN LISTS SYMBOLS)
    set_property(SOURCE ${ARGN} APPEND PROPERTY COMPILE_DEFINITIONS
      "${SYMBOL}=bsk_${MODULE_NAME}_${SYMBOL}")
  endforeach()
endfunction()
