# ISC License
#
# Copyright (c) 2026, Autonomous Vehicle Systems Lab, University of Colorado at Boulder
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

"""Generate independent import layouts for simulation and optional binding groups."""

import importlib.machinery
from pathlib import Path
import re
import sys


def module_path(root: Path, name: str) -> Path:
    """Resolve a validated dotted module name inside a package root."""
    if re.fullmatch(r"[A-Za-z_][A-Za-z_0-9]*(?:\.[A-Za-z_][A-Za-z_0-9]*)*", name) is None:
        raise ValueError(f"Invalid binding module name: {name}")
    return root.joinpath(*name.split("."))


def write_if_changed(path: Path, content: str) -> None:
    """Write generated text without changing the timestamp of identical files."""
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists() or path.read_text(encoding="utf-8") != content:
        path.write_text(content, encoding="utf-8")


def remove_native(path: Path) -> None:
    """Remove an extension and its Windows import libraries, retaining other files."""
    for suffix in importlib.machinery.EXTENSION_SUFFIXES:
        path.with_name(path.name + suffix).unlink(missing_ok=True)
    # UseSWIG and plain MODULE targets can choose different import-library prefixes.
    for stem in {path.name, path.name.removeprefix("_")}:
        path.with_name(stem + ".lib").unlink(missing_ok=True)


def generate_layout(manifest: Path, root: Path, loader: Path, native: str, loader_name: str) -> None:
    """Create lazy import shims and retire a group's previous layout.

    :param manifest: Private extension base names, without underscores, relative to Basilisk.
    :param root: Generated Basilisk package directory.
    :param loader: Source of the shared native loader implementation.
    :param native: Dotted name of the native container relative to Basilisk.
    :param loader_name: Dotted destination of the loader relative to Basilisk.
    """
    previous = manifest.with_suffix(".previous.txt")
    names = set(manifest.read_text(encoding="utf-8").split())
    old_names = set(previous.read_text(encoding="utf-8").split()) if previous.exists() else set()
    paths = {name: module_path(root, name) for name in names | old_names}
    native_path = module_path(root, native)
    loader_path = module_path(root, loader_name).with_suffix(".py")
    for name in old_names - names:
        path = paths[name]
        path.with_name("_" + path.name + ".py").unlink(missing_ok=True)
    for name in sorted(names):
        path = paths[name].with_name("_" + paths[name].name)
        remove_native(path)
        shim = ("# Generated by generateGroupedBindings.py; do not edit.\n"
                f"from Basilisk.{loader_name} import load_native_module as _load_native_module\n"
                f"_load_native_module(__name__, 'Basilisk.{native}')\n"
                "del _load_native_module\n")
        write_if_changed(path.with_suffix(".py"), shim)
    if names:
        write_if_changed(loader_path, loader.read_text(encoding="utf-8"))
    else:
        loader_path.unlink(missing_ok=True)
        remove_native(native_path)
    write_if_changed(previous, manifest.read_text(encoding="utf-8"))


if __name__ == "__main__":
    generate_layout(*(Path(arg) for arg in sys.argv[1:4]), *sys.argv[4:6])
