/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) satellite_full_constr_h_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {10, 1, 1};
static const casadi_int casadi_s3[3] = {2, 1, 1};

static const casadi_real casadi_zeros[12] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0.};

/* satellite_full_constr_h_e_fun:(i0[12],i1[0],i2[0],i3[10])->(o0[2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w0, *w2=w+14, *w3=w+17, w4, *w5=w+21;
  const casadi_real *cr, *cs, *ct, *wr1, *wr2, *wr3, *wr5;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = input[0][0] */
  wr1 = arg[0] ? arg[0] : casadi_zeros;
  /* #2: @2 = @1[3:6] */
  wr2 = wr1+3;
  /* #3: @3 = @2' */
  wr3 = wr2;
  /* #4: @4 = mac(@3,@2,@0) */
  casadi_copy((&w0), 1, (&w4));
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=wr3+j, ct=wr2+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #5: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  /* #6: @5 = @1[6:12] */
  wr5 = wr1+6;
  /* #7: @4 = 1 */
  w4 = 1.;
  /* #8: @3 = @1[6:9] */
  wr3 = wr1+6;
  /* #9: @2 = @3' */
  wr2 = wr3;
  /* #10: @0 = mac(@2,@3,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=wr2+j, ct=wr3+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #11: @4 = (@4<@0) */
  w4  = (w4<w0);
  /* #12: @2 = (@3/@0) */
  for (i=0, rr=w2, cr=wr3; i<3; ++i) (*rr++)  = ((*cr++)/w0);
  /* #13: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #14: @2 = (@4?@2:0) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) (*rr++)  = (w4?cs[i]:0);
  /* #15: @4 = (!@4) */
  w4 = (! w4 );
  /* #16: @3 = (@4?@3:0) */
  for (i=0, rr=w3, cs=wr3; i<3; ++i) (*rr++)  = (w4?cs[i]:0);
  /* #17: @2 = (@2+@3) */
  for (i=0, rr=w2, cs=w3; i<3; ++i) (*rr++) += (*cs++);
  /* #18: (@5[:3] = @2) */
  casadi_copy(wr5, 6, w5);
  for (rr=w5+0, cs=w2; rr!=w5+3; rr+=1) *rr = *cs++;
  /* #19: @2 = @5[3:6] */
  for (rr=w2, cs=w5+3; cs!=w5+6; cs+=1) *rr++ = *cs;
  /* #20: @4 = dot(@2, @2) */
  w4 = casadi_dot(3, w2, w2);
  /* #21: output[0][1] = @4 */
  if (res[0]) res[0][1] = w4;
  return 0;
}

CASADI_SYMBOL_EXPORT int satellite_full_constr_h_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int satellite_full_constr_h_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int satellite_full_constr_h_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void satellite_full_constr_h_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int satellite_full_constr_h_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void satellite_full_constr_h_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void satellite_full_constr_h_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void satellite_full_constr_h_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int satellite_full_constr_h_e_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int satellite_full_constr_h_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real satellite_full_constr_h_e_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* satellite_full_constr_h_e_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* satellite_full_constr_h_e_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* satellite_full_constr_h_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* satellite_full_constr_h_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int satellite_full_constr_h_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 27;
  return 0;
}

CASADI_SYMBOL_EXPORT int satellite_full_constr_h_e_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 27*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
