/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) satellite_full_constr_h_e_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {10, 1, 1};
static const casadi_int casadi_s3[3] = {2, 1, 1};
static const casadi_int casadi_s4[11] = 
  {12, 2, 0, 3, 6, 3, 4, 5,
  9, 10, 11};
static const casadi_int casadi_s5[3] = {2, 0, 1};

static const casadi_real casadi_zeros[12] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0.};

/* satellite_full_constr_h_e_fun_jac_uxt_zt:(i0[12],i1[0],i2[0],i3[10])->(o0[2],o1[12x2,6nz],o2[2x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+2, *w02=w+14, *w03=w+17, w04, *w05=w+21, *w06=w+27, *w07=w+30, *w08=w+33, *w09=w+36, w10;
  casadi_real *w11=w+40, w12, *w13=w+44, *w14=w+50, w15, *w16=w+53;
  const casadi_real *cr, *cs, *ct, *wr01, *wr02, *wr03, *wr05, *wr06, *wr07;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = input[0][0] */
  wr01 = arg[0] ? arg[0] : casadi_zeros;
  /* #2: @2 = @1[3:6] */
  wr02 = wr01+3;
  /* #3: @3 = @2' */
  wr03 = wr02;
  /* #4: @4 = mac(@3,@2,@0) */
  casadi_copy((&w00), 1, (&w04));
  for (i=0, rr=(&w04); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=wr03+j, ct=wr02+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #5: output[0][0] = @4 */
  if (res[0]) res[0][0] = w04;
  /* #6: @5 = @1[6:12] */
  wr05 = wr01+6;
  /* #7: @4 = 1 */
  w04 = 1.;
  /* #8: @6 = @1[6:9] */
  wr06 = wr01+6;
  /* #9: @7 = @6' */
  wr07 = wr06;
  /* #10: @0 = mac(@7,@6,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=wr07+j, ct=wr06+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #11: @4 = (@4<@0) */
  w04  = (w04<w00);
  /* #12: @8 = (@6/@0) */
  for (i=0, rr=w08, cr=wr06; i<3; ++i) (*rr++)  = ((*cr++)/w00);
  /* #13: @9 = (-@8) */
  for (i=0, rr=w09, cs=w08; i<3; ++i) *rr++ = (- *cs++ );
  /* #14: @9 = (@4?@9:0) */
  for (i=0, rr=w09, cs=w09; i<3; ++i) (*rr++)  = (w04?cs[i]:0);
  /* #15: @10 = (!@4) */
  w10 = (! w04 );
  /* #16: @11 = (@10?@6:0) */
  for (i=0, rr=w11, cs=wr06; i<3; ++i) (*rr++)  = (w10?cs[i]:0);
  /* #17: @9 = (@9+@11) */
  for (i=0, rr=w09, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #18: (@5[:3] = @9) */
  casadi_copy(wr05, 6, w05);
  for (rr=w05+0, cs=w09; rr!=w05+3; rr+=1) *rr = *cs++;
  /* #19: @9 = @5[3:6] */
  for (rr=w09, cs=w05+3; cs!=w05+6; cs+=1) *rr++ = *cs;
  /* #20: @12 = dot(@9, @9) */
  w12 = casadi_dot(3, w09, w09);
  /* #21: output[0][1] = @12 */
  if (res[0]) res[0][1] = w12;
  /* #22: @5 = zeros(12x2,6nz) */
  casadi_clear(w05, 6);
  /* #23: @1 = zeros(12x1) */
  casadi_clear(w01, 12);
  /* #24: @13 = zeros(6x1) */
  casadi_clear(w13, 6);
  /* #25: @14 = ones(2x1) */
  casadi_fill(w14, 2, 1.);
  /* #26: {@12, @15} = vertsplit(@14) */
  w12 = w14[0];
  w15 = w14[1];
  /* #27: @9 = (@15*@9) */
  for (i=0, rr=w09, cs=w09; i<3; ++i) (*rr++)  = (w15*(*cs++));
  /* #28: @9 = (2.*@9) */
  for (i=0, rr=w09, cs=w09; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #29: (@13[3:6] += @9) */
  for (rr=w13+3, cs=w09; rr!=w13+6; rr+=1) *rr += *cs++;
  /* #30: @9 = @13[:3] */
  for (rr=w09, cs=w13+0; cs!=w13+3; cs+=1) *rr++ = *cs;
  /* #31: @11 = (@10?@9:0) */
  for (i=0, rr=w11, cs=w09; i<3; ++i) (*rr++)  = (w10?cs[i]:0);
  /* #32: @16 = (@9/@0) */
  for (i=0, rr=w16, cr=w09; i<3; ++i) (*rr++)  = ((*cr++)/w00);
  /* #33: @16 = (-@16) */
  for (i=0, rr=w16, cs=w16; i<3; ++i) *rr++ = (- *cs++ );
  /* #34: @16 = (@4?@16:0) */
  for (i=0, rr=w16, cs=w16; i<3; ++i) (*rr++)  = (w04?cs[i]:0);
  /* #35: @11 = (@11+@16) */
  for (i=0, rr=w11, cs=w16; i<3; ++i) (*rr++) += (*cs++);
  /* #36: @8 = (@8/@0) */
  for (i=0, rr=w08; i<3; ++i) (*rr++) /= w00;
  /* #37: @8 = (-@8) */
  for (i=0, rr=w08, cs=w08; i<3; ++i) *rr++ = (- *cs++ );
  /* #38: @9 = (-@9) */
  for (i=0, rr=w09, cs=w09; i<3; ++i) *rr++ = (- *cs++ );
  /* #39: @9 = (@4?@9:0) */
  for (i=0, rr=w09, cs=w09; i<3; ++i) (*rr++)  = (w04?cs[i]:0);
  /* #40: @4 = dot(@8, @9) */
  w04 = casadi_dot(3, w08, w09);
  /* #41: @6 = (@6*@4) */
  for (i=0, rr=w06, cr=wr06; i<3; ++i) (*rr++)  = ((*cr++)*w04);
  /* #42: @11 = (@11+@6) */
  for (i=0, rr=w11, cs=w06; i<3; ++i) (*rr++) += (*cs++);
  /* #43: @7 = (@4*@7) */
  for (i=0, rr=w07, cs=wr07; i<3; ++i) (*rr++)  = (w04*(*cs++));
  /* #44: @7 = @7' */
  /* #45: @11 = (@11+@7) */
  for (i=0, rr=w11, cs=w07; i<3; ++i) (*rr++) += (*cs++);
  /* #46: (@1[6:9] += @11) */
  for (rr=w01+6, cs=w11; rr!=w01+9; rr+=1) *rr += *cs++;
  /* #47: @11 = zeros(3x1) */
  casadi_clear(w11, 3);
  /* #48: (@13[:3] = @11) */
  for (rr=w13+0, cs=w11; rr!=w13+3; rr+=1) *rr = *cs++;
  /* #49: (@1[6:12] += @13) */
  for (rr=w01+6, cs=w13; rr!=w01+12; rr+=1) *rr += *cs++;
  /* #50: @2 = (@2*@12) */
  for (i=0, rr=w02, cr=wr02; i<3; ++i) (*rr++)  = ((*cr++)*w12);
  /* #51: (@1[3:6] += @2) */
  for (rr=w01+3, cs=w02; rr!=w01+6; rr+=1) *rr += *cs++;
  /* #52: @3 = (@12*@3) */
  for (i=0, rr=w03, cs=wr03; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #53: @3 = @3' */
  /* #54: (@1[3:6] += @3) */
  for (rr=w01+3, cs=w03; rr!=w01+6; rr+=1) *rr += *cs++;
  /* #55: @12 = @1[3] */
  for (rr=(&w12), cs=w01+3; cs!=w01+4; cs+=1) *rr++ = *cs;
  /* #56: (@5[0] = @12) */
  for (rr=w05+0, cs=(&w12); rr!=w05+1; rr+=1) *rr = *cs++;
  /* #57: @12 = @1[4] */
  for (rr=(&w12), cs=w01+4; cs!=w01+5; cs+=1) *rr++ = *cs;
  /* #58: (@5[1] = @12) */
  for (rr=w05+1, cs=(&w12); rr!=w05+2; rr+=1) *rr = *cs++;
  /* #59: @12 = @1[5] */
  for (rr=(&w12), cs=w01+5; cs!=w01+6; cs+=1) *rr++ = *cs;
  /* #60: (@5[2] = @12) */
  for (rr=w05+2, cs=(&w12); rr!=w05+3; rr+=1) *rr = *cs++;
  /* #61: @12 = @1[9] */
  for (rr=(&w12), cs=w01+9; cs!=w01+10; cs+=1) *rr++ = *cs;
  /* #62: (@5[3] = @12) */
  for (rr=w05+3, cs=(&w12); rr!=w05+4; rr+=1) *rr = *cs++;
  /* #63: @12 = @1[10] */
  for (rr=(&w12), cs=w01+10; cs!=w01+11; cs+=1) *rr++ = *cs;
  /* #64: (@5[4] = @12) */
  for (rr=w05+4, cs=(&w12); rr!=w05+5; rr+=1) *rr = *cs++;
  /* #65: @12 = @1[11] */
  for (rr=(&w12), cs=w01+11; cs!=w01+12; cs+=1) *rr++ = *cs;
  /* #66: (@5[5] = @12) */
  for (rr=w05+5, cs=(&w12); rr!=w05+6; rr+=1) *rr = *cs++;
  /* #67: output[1][0] = @5 */
  casadi_copy(w05, 6, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int satellite_full_constr_h_e_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int satellite_full_constr_h_e_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int satellite_full_constr_h_e_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void satellite_full_constr_h_e_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int satellite_full_constr_h_e_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void satellite_full_constr_h_e_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void satellite_full_constr_h_e_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void satellite_full_constr_h_e_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int satellite_full_constr_h_e_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int satellite_full_constr_h_e_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real satellite_full_constr_h_e_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* satellite_full_constr_h_e_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* satellite_full_constr_h_e_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* satellite_full_constr_h_e_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* satellite_full_constr_h_e_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int satellite_full_constr_h_e_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 56;
  return 0;
}

CASADI_SYMBOL_EXPORT int satellite_full_constr_h_e_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 56*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
