#!/usr/bin/env python3
"""Generate ``src/architecture/rust/bsk_messages/src/lib.rs`` from Basilisk's C message headers.

The output is committed (same as ``bsk_utilities/src/raw.rs``), so consuming
``bsk-messages`` never requires ``bindgen``/``libclang`` -- only developing
Basilisk's own message-related Rust tooling does. Re-run this script and
commit the result whenever message payload definitions change (new message
type, changed field, etc.).

This is the canonical copy (copied into ``bsk_sdk`` by ``tools/sync_rust.py``
there, the same way headers/SWIG files are). It targets two message-header
layouts so the *same* script works from either repo:

* Basilisk core (default here): message headers are a ``cargo build``-time
  *artifact* generated by CMake's ``msgAutoSource`` target into a build
  directory (default ``dist3/autoSource/cMsgCInterface``, override with
  ``--cmsg-dir`` if configured elsewhere) -- run
  ``cmake --build dist3 --target cMsgCInterface`` (or a full build) first.
  General headers (e.g. ``bskLogging.h``) are read straight from this repo's
  own ``src/``.
* ``bsk_sdk``'s vendored copy: ``--bsk-include`` points at a directory with
  both a flat ``cMsgCInterface/`` subdirectory and a ``Basilisk/`` subdirectory
  (``bsk_sdk.include_dir()``'s layout).

Requirements
------------
* ``bindgen`` CLI must be on ``$PATH``.  Install once with::

      cargo install bindgen-cli

* ``libclang`` must be available (``libclang-dev`` on Debian/Ubuntu).
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

RUST_SUPPORT_ROOT = Path(__file__).resolve().parent
REPO_ROOT = Path(__file__).resolve().parents[3]

FILE_HEADER = """\
// This file is AUTO-GENERATED by src/architecture/rust/gen_rust_messages.py.
// DO NOT EDIT BY HAND.
//
// Re-run `python3 src/architecture/rust/gen_rust_messages.py` after message payload
// definitions change to keep these bindings in sync.
//
// Crate: bsk-messages
// Source: Basilisk's generated cMsgCInterface headers

#![allow(non_snake_case, non_camel_case_types, non_upper_case_globals, dead_code, clippy::all)]

"""

# `BskContext`, `BskModuleRuntime`, `BskError`/`BskResult`,
# `Msg`/`MsgReader`/`MsgWriter`, `BskModule`, and the logger support are
# hand-written, not generated — they live in `bsk-build` (this crate has no
# bindgen step of its own to justify owning them) and are just re-exported
# here, so `use bsk_messages::*;` still brings in everything a module needs in
# one line. The procedural attribute itself is not re-exported; see
# `bsk-build`'s crate docs for why it is a second, direct dependency.
RUNTIME_SUPPORT_CODE = """\
pub use bsk_build::{
    BskContext, BskError, BskLoggerRef, BskModule, BskModuleRuntime, BskResult, Msg, MsgReader,
    MsgWriter,
};
"""

WRAPPER_TEMPLATE = """\
/* Wrapper header: include every cMsgCInterface message header in one shot.
 * Generated by gen_rust_messages.py. */
#include <stdint.h>
#include <stddef.h>

{includes}
"""


def find_default_cmsg_dir() -> Path:
    """Default to this repo's own build output (Basilisk core layout)."""
    candidate = REPO_ROOT / "dist3" / "autoSource" / "cMsgCInterface"
    if candidate.exists():
        return candidate
    raise RuntimeError(
        f"Cannot find generated cMsgCInterface headers under {candidate}. "
        "Configure/build Basilisk first (e.g. `python3 conanfile.py` / "
        "`cmake --build dist3 --target cMsgCInterface`), or pass "
        "--cmsg-dir/--bsk-include explicitly (e.g. a bsk_sdk include root)."
    )


def build_wrapper_header(cmsg_dir: Path, header_prefix: str) -> str:
    headers = sorted(cmsg_dir.glob("*_C.h"))
    if not headers:
        sys.exit(f"ERROR: no *_C.h headers found under {cmsg_dir}")
    # Use the full path so the wrapper header works regardless of working dir.
    includes = "\n".join(f'#include "{h}"' for h in headers)
    return WRAPPER_TEMPLATE.format(prefix=header_prefix, includes=includes)


def run_bindgen(
    wrapper_path: Path,
    include_dirs: list[Path],
    extra_clang_args: list[str],
) -> str:
    if not shutil.which("bindgen"):
        sys.exit(
            "ERROR: `bindgen` not found on $PATH.\n"
            "Install it with:  cargo install bindgen-cli"
        )

    # bindgen takes its own flags, then `--`, then raw clang flags.
    clang_args: list[str] = [f"-I{d}" for d in include_dirs] + extra_clang_args

    cmd = [
        "bindgen",
        str(wrapper_path),
        "--use-core",
        "--no-prepend-enum-name",
        "--merge-extern-blocks",
        "--with-derive-default",
        # Keep only the message-relevant surface: payloads, *_C structs,
        # MsgHeader, BSKLogger, and the C-interface functions.
        "--allowlist-type", r".*MsgPayload|.*Msg_C|MsgHeader|BSKLogger|logLevel_t",
        "--allowlist-function", r".*Msg_C_.*",
        # BSKLogger is a C++ class under __cplusplus; treat it as opaque.
        "--opaque-type", "BSKLogger",
        "--",   # everything after this is passed verbatim to clang
        *clang_args,
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        sys.exit(
            f"ERROR: bindgen failed (exit {result.returncode}):\n{result.stderr}"
        )
    return result.stdout


def rename_payload_to_msg(text: str) -> str:
    """Rename bindgen's ``FooMsgPayload`` to ``FooMsg`` throughout.

    The Rust binding calls a message's data type ``Msg`` (read/written via
    ``MsgReader``/``MsgWriter``), not ``MsgPayload``. The underlying
    Basilisk C struct is still named ``FooMsgPayload``; this is a
    Rust-binding-only rename.
    """
    return re.sub(r"MsgPayload\b", "Msg", text)


def rename_port_data_field(text: str) -> str:
    """Rename the ``payload``/``payloadPointer`` fields bindgen generates for
    every ``FooMsg_C`` port struct to ``data``/``dataPointer``.

    These fields exist only so the Rust struct's layout matches Basilisk's C
    ``FooMsg_C`` (which does call the field ``payload`` — this is a
    Rust-binding-only rename, same as ``rename_payload_to_msg`` above). No
    generated Rust code reads either field by name (``MsgReader``/
    ``MsgWriter`` call the C read/write functions instead), so this only
    changes what a field name in the crate's source, not behavior.

    Scoped to the exact field-declaration/offset-assertion syntax bindgen
    emits, so it doesn't touch unrelated prose like a doc comment's "message
    payload".
    """
    text = re.sub(r"\bpayloadPointer\b(?=[:,)])", "dataPointer", text)
    text = re.sub(r"\bpayload\b(?=[:,)])", "data", text)
    text = text.replace('::payloadPointer"', '::dataPointer"')
    text = text.replace('::payload"', '::data"')
    return text


def find_message_types(text: str) -> list[str]:
    """Return every message base name (``AttGuidMsg`` from ``AttGuidMsg_C``)."""
    return sorted(set(re.findall(r"pub struct (\w+Msg)_C\b", text)))


def render_msg_trait_impls(message_types: list[str]) -> str:
    """One ``impl Msg for <Type>`` block per Basilisk message, wiring the
    renamed message type to its C-interface port struct and
    read/write/init/is_linked functions."""
    parts = ["// Auto-generated `Msg` trait impl for every Basilisk message type.\n"]
    for m in message_types:
        parts.append(
            f"impl Msg for {m} {{\n"
            f"    type Port = {m}_C;\n"
            f"    fn __is_linked(port: &mut {m}_C) -> bool {{ unsafe {{ {m}_C_isLinked(port) != 0 }} }}\n"
            f"    fn __read(port: &mut {m}_C) -> Self {{ unsafe {{ {m}_C_read(port) }} }}\n"
            f"    fn __init(port: &mut {m}_C) {{ unsafe {{ {m}_C_init(port) }} }}\n"
            f"    fn __write(data: &Self, port: &mut {m}_C, module_id: i64, current_sim_nanos: u64) {{\n"
            f"        unsafe {{ {m}_C_write(data as *const {m} as *mut {m}, port, module_id, current_sim_nanos) }}\n"
            f"    }}\n"
            f"}}"
        )
    return "\n".join(parts) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--bsk-include",
        metavar="DIR",
        help="bsk_sdk include root (parent of cMsgCInterface/ and Basilisk/). "
             "Shorthand for --cmsg-dir DIR/cMsgCInterface --src-root DIR/Basilisk.",
    )
    parser.add_argument(
        "--cmsg-dir",
        metavar="DIR",
        help="Directory containing generated *_C.h message headers "
             "(default: dist3/autoSource/cMsgCInterface).",
    )
    parser.add_argument(
        "--src-root",
        metavar="DIR",
        help="Directory containing bare 'architecture/...' headers "
             "(default: this repo's src/).",
    )
    parser.add_argument(
        "--out",
        metavar="FILE",
        default=str(RUST_SUPPORT_ROOT / "bsk_messages" / "src" / "lib.rs"),
        help="Output path for the generated lib.rs "
             "(default: src/architecture/rust/bsk_messages/src/lib.rs)",
    )
    args = parser.parse_args()

    if args.bsk_include:
        bsk_include = Path(args.bsk_include).resolve()
        cmsg_dir = Path(args.cmsg_dir).resolve() if args.cmsg_dir else bsk_include / "cMsgCInterface"
        src_root = Path(args.src_root).resolve() if args.src_root else bsk_include / "Basilisk"
        header_prefix = ""  # bsk_sdk's cMsgCInterface/ is already flat/bare.
    else:
        cmsg_dir = Path(args.cmsg_dir).resolve() if args.cmsg_dir else find_default_cmsg_dir()
        src_root = Path(args.src_root).resolve() if args.src_root else REPO_ROOT / "src"
        header_prefix = ""

    if not cmsg_dir.exists():
        sys.exit(f"ERROR: cMsgCInterface directory not found under {cmsg_dir}")
    if not src_root.exists():
        sys.exit(f"ERROR: Basilisk src root not found under {src_root}")

    print(f"Using cMsgCInterface dir: {cmsg_dir}  ({len(list(cmsg_dir.glob('*_C.h')))} message headers)")
    print(f"Using Basilisk src root:  {src_root}")

    wrapper = build_wrapper_header(cmsg_dir, header_prefix)

    with tempfile.NamedTemporaryFile(suffix=".h", mode="w", delete=False) as f:
        f.write(wrapper)
        wrapper_path = Path(f.name)

    try:
        raw = run_bindgen(
            wrapper_path,
            # The wrapper #include's message headers by full path (so cmsg_dir
            # itself doesn't need to be on -I), but those headers in turn
            # `#include "architecture/..."` bare, which needs src_root; some
            # payload headers use <string>, so compile as C++.
            include_dirs=[src_root, cmsg_dir],
            extra_clang_args=["-std=c++17", "-x", "c++"],
        )
    finally:
        wrapper_path.unlink(missing_ok=True)

    raw = rename_payload_to_msg(raw)
    raw = rename_port_data_field(raw)
    message_types = find_message_types(raw)
    msg_impls = render_msg_trait_impls(message_types)
    print(f"  Msg trait impls:  {len(message_types)} message types")

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(FILE_HEADER + RUNTIME_SUPPORT_CODE + "\n" + raw + "\n" + msg_impls)
    print(f"Wrote {out_path}  ({out_path.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
