#!/usr/bin/env python3
#
#  ISC License
#
#  Copyright (c) 2026, Autonomous Vehicle Systems Lab, University of Colorado at Boulder
#
#  Permission to use, copy, modify, and/or distribute this software for any
#  purpose with or without fee is hereby granted, provided that the above
#  copyright notice and this permission notice appear in all copies.
#
"""Generate Rust FFI bindings for selected Basilisk C ABI utilities.

The generated bindings intentionally cover only C ABI headers.  C++/Eigen APIs
need a dedicated C shim and are excluded until that interface is designed.

This is the canonical copy (vendored into ``bsk_sdk`` by ``tools/sync_rust.py``
there, the same way headers/SWIG files are). It targets two include-root
shapes so the *same* script works from either repo:

* Basilisk core (default here): ``--bsk-include`` points at (or defaults to)
  this repo's own ``src/`` -- headers are included bare, e.g.
  ``architecture/utilities/astroConstants.h``.
* ``bsk_sdk``'s vendored copy: an include root with a ``Basilisk/``
  subdirectory (``bsk_sdk.include_dir()``'s layout) -- headers are included
  as ``Basilisk/architecture/utilities/astroConstants.h``, matching how
  bsk_sdk's own vendored tree is laid out. Detected automatically from
  whether ``<include-root>/Basilisk`` exists.
"""

import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


RUST_SUPPORT_ROOT = Path(__file__).resolve().parent
REPO_ROOT = Path(__file__).resolve().parents[3]
FILE_HEADER = """// This file is AUTO-GENERATED by src/architecture/rust/gen_rust_utilities.py.
// DO NOT EDIT BY HAND.
//
// Source headers: astroConstants.h, macroDefinitions.h, orbitalMotion.h, and
// rigidBodyKinematics.h.
//
"""
WRAPPER_TEMPLATE = """\
#include "{prefix}architecture/utilities/astroConstants.h"
#include "{prefix}architecture/utilities/macroDefinitions.h"
#include "{prefix}architecture/utilities/orbitalMotion.h"
#include "{prefix}architecture/utilities/rigidBodyKinematics.h"

/* Bindgen ignores some guarded/expression macros.  Re-expose the selected
 * values as typed constants without duplicating their definitions in Rust. */
static const double BSK_RUST_G_UNIVERSIAL = G_UNIVERSIAL;
static const double BSK_RUST_SEC2DAY = SEC2DAY;
static const double BSK_RUST_J2_EARTH = J2_EARTH;
static const double BSK_RUST_J3_EARTH = J3_EARTH;
static const double BSK_RUST_J4_EARTH = J4_EARTH;
static const double BSK_RUST_J5_EARTH = J5_EARTH;
static const double BSK_RUST_J6_EARTH = J6_EARTH;
static const double BSK_RUST_J2_MARS = J2_MARS;
"""


def resolve_layout(include_root: Path) -> tuple[Path, str]:
    """Return ``(basilisk_include_dir, header_prefix)`` for this include root.

    A ``bsk_sdk``-vendored root has a ``Basilisk/`` subdirectory containing
    the actual headers, with the root itself on the include path so
    ``#include "Basilisk/architecture/..."`` resolves; Basilisk core's own
    ``src/`` *is* that directory already, with nothing to prefix.
    """
    if (include_root / "Basilisk").is_dir():
        return include_root / "Basilisk", "Basilisk/"
    return include_root, ""


def find_default_include_root() -> Path:
    """Default to this repo's own ``src/`` (Basilisk core layout)."""
    src = REPO_ROOT / "src"
    if (src / "architecture" / "utilities" / "astroConstants.h").exists():
        return src
    raise RuntimeError(
        f"Cannot find architecture/utilities headers under {src}. "
        "Pass --bsk-include explicitly (e.g. a bsk_sdk include root)."
    )


def run_bindgen(wrapper_path: Path, include_root: Path, basilisk_dir: Path) -> str:
    """Run bindgen over the selected C ABI headers.

    ``include_root`` resolves the wrapper header's own ``#include`` lines
    (written with ``header_prefix``); ``basilisk_dir`` resolves the
    *internal* cross-includes Basilisk headers use among themselves, which
    are always bare (e.g. ``"architecture/utilities/linearAlgebra.h"``)
    regardless of ``header_prefix``. The two are the same directory in
    Basilisk core's own layout (no prefix) and different directories for a
    ``bsk_sdk``-vendored root (see ``resolve_layout``).
    """
    if not shutil.which("bindgen"):
        sys.exit("ERROR: `bindgen` not found on $PATH; run `cargo install bindgen-cli`.")

    allow_functions = (
        "E2f|E2M|f2E|f2H|H2f|H2N|M2E|N2H|"
        "elem2rv|rv2elem|clMeanOscMap|clElem2eqElem|"
        "hillFrame|hill2rv|rv2hill|"
        "atmosphericDensity|debyeLength|atmosphericDrag|solarRad|"
        "addMRP|subMRP|MRP2C|C2MRP|MRP2EP|EP2MRP|"
        "MRPshadow|MRPswitch|dMRP|dMRP2Omega|ddMRP|ddMRP2dOmega|"
        "BmatMRP|BdotmatMRP|BinvMRP|wrapToPi|tilde|Mi"
    )
    allow_constants = (
        "G_UNIVERSIAL|AU|AU2M|SPEED_LIGHT|SOLAR_FLUX_EARTH|"
        "D2R|R2D|RPM|SEC2DAY|EARTH_GRAV|"
        "MU_(SUN|MERCURY|VENUS|EARTH|MOON|MARS|JUPITER|SATURN|URANUS|NEPTUNE|PLUTO)|"
        "REQ_(SUN|MERCURY|VENUS|EARTH|MOON|MARS|JUPITER|SATURN|URANUS|NEPTUNE|PLUTO)|"
        "RP_(EARTH|MARS)|"
        "NANO2SEC|SEC2NANO|SEC2HOUR"
    )
    command = [
        "bindgen",
        str(wrapper_path),
        "--use-core",
        "--no-prepend-enum-name",
        "--merge-extern-blocks",
        "--with-derive-default",
        "--allowlist-type",
        "ClassicElements|equinoctialElements|CelestialObject_t",
        "--allowlist-function",
        f"^({allow_functions})$",
        "--allowlist-var",
        f"^({allow_constants}|BSK_RUST_.*)$",
        "--opaque-type",
        "BSKLogger",
        "--",
        f"-I{include_root}",
        f"-I{basilisk_dir}",
        "-std=c++17",
        "-x",
        "c++",
    ]
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode:
        sys.exit(f"ERROR: bindgen failed:\n{result.stderr}")
    return result.stdout


def main() -> None:
    """Generate ``bsk_utilities/src/raw.rs``."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--bsk-include",
        metavar="DIR",
        help="Include root: this repo's root (default) or a bsk_sdk include dir.",
    )
    parser.add_argument(
        "--out",
        default=RUST_SUPPORT_ROOT / "bsk_utilities" / "src" / "raw.rs",
        type=Path,
    )
    args = parser.parse_args()

    include_root = (
        Path(args.bsk_include).resolve() if args.bsk_include else find_default_include_root()
    )
    basilisk_dir, header_prefix = resolve_layout(include_root)

    with tempfile.NamedTemporaryFile(suffix=".h", mode="w", delete=False) as file:
        file.write(WRAPPER_TEMPLATE.format(prefix=header_prefix))
        wrapper_path = Path(file.name)
    try:
        bindings = run_bindgen(wrapper_path, include_root, basilisk_dir)
    finally:
        wrapper_path.unlink(missing_ok=True)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(FILE_HEADER + bindings)
    print(f"Wrote {args.out} ({args.out.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
