//  ISC License
//
//  Copyright (c) 2026, Autonomous Vehicle Systems Lab, University of Colorado at Boulder
//
//  Permission to use, copy, modify, and/or distribute this software for any
//  purpose with or without fee is hereby granted, provided that the above
//  copyright notice and this permission notice appear in all copies.

//! Legacy Rust FFI shim renderer: turns an unmarked module's [`ConfigInfo`]
//! into `OUT_DIR/bsk_shim.rs` — the `extern "C-unwind"` lifecycle entry
//! points that handle message I/O and call the config's `BskModule`
//! implementation. New modules receive these entry points from
//! `#[bsk_build::module]` instead.

use super::methods::rust_array_type;
use super::types::{ConfigInfo, FieldInfo, MethodInfo};

pub(super) fn camel_to_snake(s: &str) -> String {
    let mut out = String::new();
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            out.push('_');
        }
        out.push(ch.to_ascii_lowercase());
    }
    out
}

pub(super) fn render_shim(info: &ConfigInfo, module: &str) -> String {
    let cfg_type = &info.struct_name;

    let inputs: Vec<&FieldInfo> = info.fields.iter().filter(|f| f.is_in_msg()).collect();
    let outputs: Vec<&FieldInfo> = info.fields.iter().filter(|f| f.is_out_msg()).collect();

    let out_vars: Vec<String> = outputs.iter().map(|f| camel_to_snake(&f.name)).collect();
    let out_lhs = match out_vars.len() {
        0 => "let ()".to_owned(),
        1 => format!("let ({},)", out_vars[0]),
        _ => format!("let ({})", out_vars.join(", ")),
    };

    // Does the config struct expose a bskLogger field for per-module verbosity?
    let has_logger = info.fields.iter().any(|f| f.name == "bskLogger");
    // Expression to pass as the receiver of `BskLoggerExt::bsk_error` below.
    // Falls back to a null pointer, which `BskLoggerExt` resolves to the
    // process-wide default logger — see bsk-messages.
    let logger_expr = if has_logger {
        "(*cfg).bskLogger"
    } else {
        "::core::ptr::null_mut()"
    };

    let mut s = String::new();
    s.push_str("// Auto-generated by bsk-build — do not edit.\n\n");

    // Init — called from the generated C++ default constructor before Python
    // touches the struct. This is the Rust equivalent of a C++ module's
    // constructor: sets non-zero parameter defaults and initial state.
    s.push_str(&format!(
        "#[no_mangle]\npub unsafe extern \"C-unwind\" fn Init_{module}(\n    cfg: *mut {cfg_type},\n) {{\n\
         \x20   <{cfg_type} as BskModule>::init(&mut *cfg);\n\
         }}\n\n"
    ));

    // SelfInit — called at InitializeSimulation(), after Python has configured
    // the struct. Per Basilisk's cModules-3.rst: "The SelfInit function should
    // only do the above steps [Msg_C_init calls]." The shim handles all of them;
    // there is no BskModule::self_init() trait method.
    s.push_str(&format!(
        "#[no_mangle]\npub unsafe extern \"C-unwind\" fn SelfInit_{module}(\n    cfg: *mut {cfg_type},\n    runtime: *const BskModuleRuntime,\n) {{\n\
         \x20   (*cfg).runtime = ::core::ptr::read(runtime);\n"
    ));
    for f in &outputs {
        s.push_str(&format!("    (*cfg).{field}.init();\n", field = f.name));
    }
    s.push_str("}\n\n");

    // Reset
    s.push_str(&format!(
        "#[no_mangle]\npub unsafe extern \"C-unwind\" fn Reset_{module}(\n    cfg: *mut {cfg_type},\n    current_sim_nanos: u64,\n    runtime: *const BskModuleRuntime,\n) {{\n\
         \x20   (*cfg).runtime = ::core::ptr::read(runtime);\n"
    ));
    for f in &inputs {
        if !f.is_optional {
            s.push_str(&format!(
                "    if !(*cfg).{field}.is_linked() {{\n\
                 \x20       bsk_messages::BskLoggerExt::bsk_error({logger_expr}, \"[{module}] {field} is not connected\");\n\
                 \x20   }}\n",
                field = f.name,
            ));
        }
    }
    // Capture and write the outputs returned by reset(), just as Update does,
    // so every output port is initialised before the first UpdateState tick.
    s.push_str(&format!(
        "    {out_lhs}: <{cfg_type} as BskModule>::Outputs = \
         <{cfg_type} as BskModule>::reset(&mut *cfg, current_sim_nanos);\n",
    ));
    for f in &outputs {
        let var = camel_to_snake(&f.name);
        s.push_str(&format!(
            "    (*cfg).{field}.write(&{var}, (*cfg).runtime.module_id(), current_sim_nanos);\n",
            field = f.name,
        ));
    }
    s.push_str("}\n\n");

    // Update
    s.push_str(&format!(
        "#[no_mangle]\npub unsafe extern \"C-unwind\" fn Update_{module}(\n    cfg: *mut {cfg_type},\n    current_sim_nanos: u64,\n    runtime: *const BskModuleRuntime,\n) {{\n\
         \x20   (*cfg).runtime = ::core::ptr::read(runtime);\n"
    ));
    for f in &inputs {
        let var = camel_to_snake(&f.name);
        if f.is_optional {
            s.push_str(&format!(
                "    let {var} = (*cfg).{field}.is_linked().then(|| (*cfg).{field}.read());\n",
                field = f.name,
            ));
        } else {
            s.push_str(&format!(
                "    if !(*cfg).{field}.is_linked() {{\n\
                 \x20       bsk_messages::BskLoggerExt::bsk_error({logger_expr}, \"[{module}] {field} is not connected\");\n\
                 \x20   }}\n\
                 \x20   let {var} = (*cfg).{field}.read();\n",
                field = f.name,
            ));
        }
    }

    let input_vars: Vec<String> = inputs.iter().map(|f| camel_to_snake(&f.name)).collect();
    let input_tuple = match input_vars.len() {
        0 => "()".to_owned(),
        1 => format!("({},)", input_vars[0]),
        _ => format!("({})", input_vars.join(", ")),
    };

    s.push_str(&format!(
        "    {out_lhs}: <{cfg_type} as BskModule>::Outputs = \
         <{cfg_type} as BskModule>::update(&mut *cfg, {input_tuple}, current_sim_nanos);\n",
    ));

    for f in &outputs {
        let var = camel_to_snake(&f.name);
        s.push_str(&format!(
            "    (*cfg).{field}.write(&{var}, (*cfg).runtime.module_id(), current_sim_nanos);\n",
            field = f.name,
        ));
    }
    s.push_str("}\n\n");

    // Called from the generated header's `~{cfg_type}()` (see
    // `render_header::render_c_header`) — runs the config struct's ordinary
    // drop glue (freeing any `Option<Box<T>>` owned-state field) without
    // deallocating the struct itself; the C++ side does that immediately
    // afterward.
    s.push_str(&format!(
        "#[no_mangle]\npub unsafe extern \"C-unwind\" fn Drop_{module}(cfg: *mut {cfg_type}) {{\n\
         \x20   ::core::ptr::drop_in_place(cfg);\n\
         }}\n",
    ));

    // Config methods (see `methods::find_config_methods`) — each gets its
    // own shim calling straight through to the real, strongly typed
    // inherent method; the only marshalling needed is reconstructing an
    // array parameter from the pointer it decayed to on the C++ side (see
    // `render_method_shim`).
    for m in &info.methods {
        s.push('\n');
        s.push_str(&render_method_shim(m, module, cfg_type));
    }

    s
}

/// Renders one config method's `extern "C-unwind"` shim. An array parameter
/// arrives as a pointer (C++ callers pass an array argument by pointer
/// decay — see the `methods::find_config_methods` module comment), so the
/// shim's own parameter type is a pointer one level down (`rust_array_type`
/// of `array_dims[1..]`), which it reconstitutes into the real
/// `array_dims`-shaped array `update`/`reset`-style code expects before
/// calling through. A scalar or nested-struct parameter needs no such
/// reconstruction: unlike an array, it is genuinely passed by value in both
/// C's and Rust's `extern "C"` ABI.
fn render_method_shim(m: &MethodInfo, module: &str, cfg_type: &str) -> String {
    let mut sig_params = String::new();
    let mut call_args = String::new();
    let mut conversions = String::new();
    for p in &m.params {
        if p.array_dims.is_empty() {
            sig_params.push_str(&format!(", {}: {}", p.name, p.rust_base_type));
            call_args.push_str(&format!("{}, ", p.name));
        } else {
            let decayed = rust_array_type(&p.rust_base_type, &p.array_dims[1..]);
            let full = rust_array_type(&p.rust_base_type, &p.array_dims);
            sig_params.push_str(&format!(", {}: *const {decayed}", p.name));
            conversions.push_str(&format!(
                "    let {} = *({} as *const {full});\n",
                p.name, p.name,
            ));
            call_args.push_str(&format!("{}, ", p.name));
        }
    }
    call_args.truncate(call_args.trim_end_matches(", ").len());

    let ret_ty = m
        .ret
        .as_ref()
        .map(|r| format!(" -> {}", r.rust_base_type))
        .unwrap_or_default();
    let call = format!("(*cfg).{}({call_args})", m.name);
    let body = if m.ret.is_some() {
        format!("{call}\n")
    } else {
        format!("{call};\n")
    };

    format!(
        "#[no_mangle]\npub unsafe extern \"C-unwind\" fn {}_{module}(\n    cfg: *mut {cfg_type}{sig_params},\n){ret_ty} {{\n{conversions}\x20   {body}}}\n",
        m.name,
    )
}

#[cfg(test)]
mod tests {
    use super::super::test_support::info_for;
    use super::*;

    #[test]
    fn shim_generates_init_and_drop_functions() {
        let info = info_for(
            "#[repr(C)] pub struct MyConfig { \
             pub runtime: bsk_messages::BskModuleRuntime, \
             pub state: Option<Box<MyState>>, \
             }",
        );
        let shim = render_shim(&info, "myModule");
        // Init_ calls BskModule::init() — the constructor hook.
        assert!(shim.contains("fn Init_myModule("), "Init_ must be in shim:\n{shim}");
        assert!(shim.contains("<MyConfig as BskModule>::init(&mut *cfg)"));
        // Drop_ calls drop_in_place for owned-state cleanup.
        assert!(shim.contains("fn Drop_myModule(cfg: *mut MyConfig)"));
        assert!(shim.contains("::core::ptr::drop_in_place(cfg);"));
    }

    #[test]
    fn self_init_shim_only_does_port_init_no_trait_call() {
        // Per Basilisk's cModules-3.rst: SelfInit should ONLY call Msg_C_init
        // on output ports. The shim handles this; there is no BskModule trait
        // method for SelfInit.
        let info = info_for(
            "#[repr(C)] pub struct MyController { \
             pub runtime: bsk_messages::BskModuleRuntime, \
             pub attGuidInMsg: MsgReader<AttGuidMsg>, \
             pub cmdTorqueOutMsg: MsgWriter<CmdTorqueBodyMsg>, \
             }",
        );
        let shim = render_shim(&info, "myModule");
        let self_init_fn = {
            let start = shim.find("fn SelfInit_myModule").expect("SelfInit_ must exist");
            let end = shim[start..].find("\n}\n").map(|i| start + i + 3).unwrap_or(shim.len());
            &shim[start..end]
        };
        // Must call .init() on the output port.
        assert!(
            self_init_fn.contains("(*cfg).cmdTorqueOutMsg.init()"),
            "SelfInit shim must init output ports:\n{self_init_fn}"
        );
        // Must NOT contain a BskModule trait method call — only BskModuleRuntime
        // appears (in the parameter type), never a `<Type as BskModule>::` dispatch.
        assert!(
            !self_init_fn.contains("as BskModule>"),
            "SelfInit shim must not call any BskModule trait method:\n{self_init_fn}"
        );
    }

    #[test]
    fn reset_shim_writes_all_outputs_like_update() {
        // The generated Reset_ shim must capture reset()'s return value and
        // write every output port — exactly as Update_ does — so output
        // messages are valid before the first UpdateState tick, and so the
        // type system forces the module author to return something for every
        // output rather than silently leaving a port uninitialised.
        let info = info_for(
            "#[repr(C)] pub struct MyController { \
             pub runtime: bsk_messages::BskModuleRuntime, \
             pub attGuidInMsg: MsgReader<AttGuidMsg>, \
             pub cmdTorqueOutMsg: MsgWriter<CmdTorqueBodyMsg>, \
             pub statusOutMsg: MsgWriter<DeviceCmdMsg>, \
             }",
        );
        let shim = render_shim(&info, "myModule");

        let reset_fn = {
            let start = shim.find("fn Reset_myModule").expect("Reset_ must exist");
            let end = shim[start..].find("\n}\n").map(|i| start + i + 3).unwrap_or(shim.len());
            &shim[start..end]
        };

        // reset() return value must be destructured
        assert!(
            reset_fn.contains("let (cmd_torque_out_msg, status_out_msg)"),
            "reset shim must destructure outputs:\n{reset_fn}"
        );
        // Each output must be written by the shim
        assert!(
            reset_fn.contains("(*cfg).cmdTorqueOutMsg.write(&cmd_torque_out_msg,"),
            "reset shim must write cmdTorqueOutMsg:\n{reset_fn}"
        );
        assert!(
            reset_fn.contains("(*cfg).statusOutMsg.write(&status_out_msg,"),
            "reset shim must write statusOutMsg:\n{reset_fn}"
        );
    }
}
