//  ISC License
//
//  Copyright (c) 2026, Autonomous Vehicle Systems Lab, University of Colorado at Boulder
//
//  Permission to use, copy, modify, and/or distribute this software for any
//  purpose with or without fee is hereby granted, provided that the above
//  copyright notice and this permission notice appear in all copies.

//! C header renderer: turns a [`ConfigInfo`] into the `<ModuleName>.h` file
//! CMake/SWIG consume.

use std::collections::BTreeSet;

use super::types::{ConfigInfo, FieldInfo, MethodInfo, NestedStructInfo};

/// Renders one field declaration per line, e.g. `"    double K;"`, doc
/// comments right-aligned as trailing Doxygen `/*!< ... */`. Shared by the
/// config struct and nested struct renderers.
fn render_field_decls(fields: &[FieldInfo]) -> String {
    let mut out = String::new();
    for f in fields {
        // "BSKLogger *" + name -> "BSKLogger *bskLogger" (no space after
        // `*`); non-pointer types get the usual single space.
        let sep = if f.c_type.ends_with('*') { "" } else { " " };
        // C's array-length suffix attaches after the field name
        // (`double name[3];`, `double name[4][3];`), never after the type.
        let array_suffix: String = f.array_dims.iter().map(|n| format!("[{n}]")).collect();
        let decl = format!("    {}{sep}{}{array_suffix};", f.c_type, f.name);

        if f.doc.is_empty() {
            out.push_str(&format!("{decl}\n"));
        } else {
            out.push_str(&format!("{decl:<52} /*!< {} */\n", f.doc));
        }
    }
    out
}

/// Renders a nested struct's `typedef struct` (see "Nested structs" in the
/// module docs) — a plain C struct with no BSK-specific machinery, since
/// only the top-level config struct gets the runtime field, message
/// includes, and destructor.
fn render_nested_struct(s: &NestedStructInfo) -> String {
    format!(
        "\n\
         /*! @brief Nested struct type, generated from the Rust source by \
         bsk-build. Do not edit by hand. */\n\
         typedef struct {name} {{\n\
         {fields}\
         }} {name};\n",
        name = s.name,
        fields = render_field_decls(&s.fields),
    )
}

pub(super) fn render_c_header(info: &ConfigInfo, module: &str) -> String {
    let cfg_type = &info.struct_name;

    // Include-guard: insert underscores before each uppercase run.
    let guard = to_include_guard(module);

    // Determine which cMsgCInterface headers to include.
    let msg_includes: BTreeSet<String> = info
        .fields
        .iter()
        .filter(|f| f.msg.is_some())
        .map(|f| format!("cMsgCInterface/{}.h", f.c_type))
        .collect();

    let mut h = String::new();

    h.push_str(&format!(
        "// Auto-generated by bsk-build from src/*.rs.\n\
         // Source of truth: `pub struct {cfg_type}` in the Rust source.\n\
         // Do not edit manually — re-run `cargo build` to regenerate.\n\
         #ifndef {guard}\n\
         #define {guard}\n\
         \n\
         #include \"architecture/_GeneralModuleFiles/bsk_rust_module.h\"\n\
         #include <string.h>\n"
    ));
    for inc in &msg_includes {
        h.push_str(&format!("#include \"{inc}\"\n"));
    }

    // Nested struct types (see "Nested structs" in the module docs) must be
    // fully declared before the config struct uses them by value; `ctx`
    // populated `info.nested_structs` in dependency order during field
    // extraction, so a simple in-order emission satisfies that.
    for nested in &info.nested_structs {
        h.push_str(&render_nested_struct(nested));
    }

    h.push_str(&format!(
        "\n\
         /*! @brief Config struct for the {module} Basilisk module (Rust implementation).\n\
         *\n\
         *  This struct is generated from the Rust source by bsk-build.\n\
         *  Do not edit the C header by hand; edit the Rust struct instead.\n\
         */\n\
         typedef struct {cfg_type} {{\n"
    ));

    h.push_str(&render_field_decls(&info.fields));

    // The C++ constructor zeros the struct (a user-provided constructor makes
    // `new Config()` direct- rather than value-initialization, so fields
    // without a member-initializer would otherwise hold garbage, not zero),
    // then calls Init_<module> so `BskModule::init()` can set real defaults.
    // The destructor runs the struct's ordinary Rust drop glue, freeing any
    // `Option<Box<T>>` owned-state field. Both are only visible to C++
    // (SWIG); plain-C consumers see an ordinary struct. Methods from a
    // plain `impl <ConfigType>` block (see `methods::find_config_methods`)
    // are declared here too, right after the destructor.
    h.push_str(
        "#ifdef __cplusplus\n\
         \x20   ",
    );
    h.push_str(cfg_type);
    h.push_str(
        "();\n\
         \x20   ~",
    );
    h.push_str(cfg_type);
    h.push_str("();\n");
    for m in &info.methods {
        let ret = method_ret_c_type(m);
        let params = render_method_params(m);
        let const_qual = if m.is_mut { "" } else { " const" };
        let line = format!("    {ret} {}({params}){const_qual};\n", m.name);
        if m.doc.is_empty() {
            h.push_str(&line);
        } else {
            h.push_str(&format!("{:<52} /*!< {} */\n", line.trim_end(), m.doc));
        }
    }
    h.push_str("#endif\n");

    h.push_str(&format!(
        "}} {cfg_type};\n\
         \n\
         BSK_RUST_DECL({module}, {cfg_type})\n\
         \n\
         #ifdef __cplusplus\n\
         extern \"C\" void Init_{module}({cfg_type}* cfg);\n\
         inline {cfg_type}::{cfg_type}() {{ ::memset(this, 0, sizeof(*this)); Init_{module}(this); }}\n\
         inline {cfg_type}::~{cfg_type}() {{ Drop_{module}(this); }}\n"
    ));
    for m in &info.methods {
        h.push_str(&render_method_extern_decl(m, module, cfg_type));
        h.push_str(&render_method_inline_def(m, module, cfg_type));
    }
    h.push_str(&format!(
        "#endif\n\
         \n\
         #endif /* {guard} */\n"
    ));

    h
}

/// `"void"` for a `()`-returning method, otherwise the scalar C element
/// type (never an array — see `methods::find_config_methods`' doc comment
/// for why).
fn method_ret_c_type(m: &MethodInfo) -> &str {
    m.ret.as_ref().map_or("void", |r| r.c_type.as_str())
}

/// Renders a method's C++ parameter list, e.g. `"double value[3]"` for an
/// array parameter or `"double value"` for a scalar one — the same
/// declaration syntax `render_field_decls` uses for a field, which is
/// exactly what's needed here too: C++ decays `T name[N]` to a pointer
/// parameter automatically, so writing it this way (rather than spelling
/// out the pointer type) keeps the header's array syntax consistent
/// whether it's looking at a field or a parameter.
fn render_method_params(m: &MethodInfo) -> String {
    m.params
        .iter()
        .map(|p| {
            let sep = if p.c_type.ends_with('*') { "" } else { " " };
            let array_suffix: String = p.array_dims.iter().map(|n| format!("[{n}]")).collect();
            format!("{}{sep}{}{array_suffix}", p.c_type, p.name)
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn render_method_extern_decl(m: &MethodInfo, module: &str, cfg_type: &str) -> String {
    let ret = method_ret_c_type(m);
    let mut params = format!("{cfg_type}* cfg");
    for p in &m.params {
        params.push_str(", ");
        let sep = if p.c_type.ends_with('*') { "" } else { " " };
        let array_suffix: String = p.array_dims.iter().map(|n| format!("[{n}]")).collect();
        params.push_str(&format!("{}{sep}{}{array_suffix}", p.c_type, p.name));
    }
    // `C-unwind` is a Rust ABI spelling, not a valid C++ linkage language.
    // The Rust definitions retain `extern \"C-unwind\"`; C++ declares the
    // same unmangled symbols with ordinary C language linkage.
    format!("extern \"C\" {ret} {}_{module}({params});\n", m.name)
}

fn render_method_inline_def(m: &MethodInfo, module: &str, cfg_type: &str) -> String {
    let ret = method_ret_c_type(m);
    let params = render_method_params(m);
    let const_qual = if m.is_mut { "" } else { " const" };
    let self_arg = if m.is_mut {
        "this".to_owned()
    } else {
        format!("const_cast<{cfg_type}*>(this)")
    };
    let mut call_args = self_arg;
    for p in &m.params {
        call_args.push_str(", ");
        call_args.push_str(&p.name);
    }
    let return_kw = if m.ret.is_some() { "return " } else { "" };
    format!(
        "inline {ret} {cfg_type}::{}({params}){const_qual} {{ {return_kw}{}_{module}({call_args}); }}\n",
        m.name, m.name,
    )
}

/// camelCase → CAMEL_CASE_H for include guards.
fn to_include_guard(name: &str) -> String {
    let mut out = String::new();
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            out.push('_');
        }
        out.push(ch.to_ascii_uppercase());
    }
    out.push_str("_H");
    out
}

#[cfg(test)]
mod tests {
    use super::super::test_support::{info_for, info_for_in};
    use super::*;

    #[test]
    fn header_declares_and_defines_cpp_constructor_and_destructor() {
        let info = info_for(
            "#[repr(C)] pub struct MyConfig { \
             pub runtime: bsk_messages::BskModuleRuntime, \
             pub state: Option<Box<MyState>>, \
             }",
        );
        let header = render_c_header(&info, "myModule");
        assert!(header.contains("// Auto-generated by bsk-build from src/*.rs."));
        // Struct must have a tag name (not anonymous) for the in-class declarations
        // to be legal C++.
        assert!(header.contains("typedef struct MyConfig {"));
        // Both declarations appear inside the struct body.
        assert!(header.contains("MyConfig();"));
        assert!(header.contains("~MyConfig();"));
        // Inline definitions appear after BSK_RUST_DECL.
        assert!(header.contains("extern \"C\" void Init_myModule(MyConfig* cfg);"));
        // The struct must memset itself to zero before calling Init_, or
        // fields init() doesn't touch would hold garbage instead of zero.
        assert!(
            header.contains(
                "inline MyConfig::MyConfig() { ::memset(this, 0, sizeof(*this)); Init_myModule(this); }"
            ),
            "constructor must zero the struct before Init_:\n{header}"
        );
        assert!(header.contains("#include <string.h>"), "header:\n{header}");
        assert!(header.contains("inline MyConfig::~MyConfig() { Drop_myModule(this); }"));
        assert!(header.contains("void *state;"), "header:\n{header}");
        assert!(header.contains("BSK_RUST_DECL(myModule, MyConfig)"));
    }

    #[test]
    fn cpp_method_shim_declaration_uses_c_language_linkage() {
        let method = MethodInfo {
            name: "clear".to_owned(),
            is_mut: true,
            params: Vec::new(),
            ret: None,
            doc: String::new(),
        };

        assert_eq!(
            render_method_extern_decl(&method, "myModule", "MyConfig"),
            "extern \"C\" void clear_myModule(MyConfig* cfg);\n"
        );
    }

    #[test]
    fn nested_repr_c_struct_field_is_generated_before_parent() {
        let tmp = std::env::temp_dir().join(format!(
            "bsk_build_test_nested_{}_{}",
            std::process::id(),
            line!()
        ));
        std::fs::create_dir_all(&tmp).unwrap();
        std::fs::write(
            tmp.join("types.rs"),
            "#[repr(C)] pub struct Vec2 { pub x: f64, pub y: f64 }",
        )
        .unwrap();

        let info = info_for_in(
            "#[repr(C)] pub struct MyConfig { \
             pub runtime: bsk_messages::BskModuleRuntime, \
             pub pos: Vec2, \
             }",
            &tmp,
        );

        let pos = info.fields.iter().find(|f| f.name == "pos").unwrap();
        assert_eq!(pos.c_type, "Vec2");

        assert_eq!(info.nested_structs.len(), 1);
        assert_eq!(info.nested_structs[0].name, "Vec2");
        assert_eq!(info.nested_structs[0].fields.len(), 2);

        let header = render_c_header(&info, "myModule");
        let vec2_decl = header.find("typedef struct Vec2").expect("Vec2 must be declared");
        let myconfig_decl = header
            .find("typedef struct MyConfig")
            .expect("MyConfig must be declared");
        assert!(
            vec2_decl < myconfig_decl,
            "Vec2 must be declared before MyConfig uses it by value:\n{header}"
        );

        std::fs::remove_dir_all(&tmp).ok();
    }

    #[test]
    fn fixed_size_array_of_primitives_is_supported() {
        let info = info_for(
            "#[repr(C)] pub struct MyConfig { \
             pub runtime: bsk_messages::BskModuleRuntime, \
             pub maxTorques: [f64; 3], \
             }",
        );

        let field = info.fields.iter().find(|f| f.name == "maxTorques").unwrap();
        // `c_type` is the scalar element type; dimensions are in `array_dims`.
        assert_eq!(field.c_type, "double");
        assert_eq!(field.array_dims, [3]);

        let header = render_c_header(&info, "myModule");
        assert!(
            header.contains("double maxTorques[3];"),
            "expected a C array field declaration, got:\n{header}"
        );
    }

    #[test]
    fn fixed_size_2d_array_of_primitives_is_supported() {
        // [[f64; 3]; 4] in Rust == double field[4][3] in C (outermost dim first).
        let info = info_for(
            "#[repr(C)] pub struct MyConfig { \
             pub runtime: bsk_messages::BskModuleRuntime, \
             pub dcm: [[f64; 3]; 3], \
             }",
        );

        let field = info.fields.iter().find(|f| f.name == "dcm").unwrap();
        assert_eq!(field.c_type, "double");
        assert_eq!(field.array_dims, [3, 3]);

        let header = render_c_header(&info, "myModule");
        assert!(
            header.contains("double dcm[3][3];"),
            "expected a 2D C array field declaration, got:\n{header}"
        );
    }

    #[test]
    fn fixed_size_array_of_nested_struct_is_supported() {
        let tmp = std::env::temp_dir().join(format!(
            "bsk_build_test_array_nested_{}_{}",
            std::process::id(),
            line!()
        ));
        std::fs::create_dir_all(&tmp).unwrap();
        std::fs::write(
            tmp.join("types.rs"),
            "#[repr(C)] pub struct Vec2 { pub x: f64, pub y: f64 }",
        )
        .unwrap();

        let info = info_for_in(
            "#[repr(C)] pub struct MyConfig { \
             pub runtime: bsk_messages::BskModuleRuntime, \
             pub corners: [Vec2; 4], \
             }",
            &tmp,
        );

        let field = info.fields.iter().find(|f| f.name == "corners").unwrap();
        assert_eq!(field.c_type, "Vec2");
        assert_eq!(field.array_dims, [4]);
        assert_eq!(info.nested_structs.len(), 1);

        let header = render_c_header(&info, "myModule");
        assert!(
            header.contains("Vec2 corners[4];"),
            "expected a C array-of-struct field declaration, got:\n{header}"
        );

        std::fs::remove_dir_all(&tmp).ok();
    }
}
