# ISC License
#
# Copyright (c) 2026, Autonomous Vehicle Systems Lab, University of Colorado at Boulder
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

[package]
name = "mrpPDRust"
version = "1.0.0"
edition = "2024"
rust-version.workspace = true
license.workspace = true

[package.metadata.basilisk]
module = true

[lib]
path = "mrpPDRust.rs"
crate-type = ["staticlib"]

[dependencies]
bsk-messages = { path = "../../../architecture/rust/bsk_messages" }
bsk-build = { path = "../../../architecture/rust/bsk_build" }
nalgebra.workspace = true

[build-dependencies]
bsk-build = { path = "../../../architecture/rust/bsk_build", default-features = false, features = ["codegen"] }
