/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) satellite_others_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

static const casadi_int casadi_s0[9] = 
  {6, 3, 0, 1, 2, 3, 3, 4,
  5};
static const casadi_int casadi_s1[12] = 
  {3, 6, 0, 0, 0, 0, 1, 2,
  3, 0, 1, 2};
static const casadi_int casadi_s2[18] = 
  {6, 3, 0, 4, 8, 12, 0, 1,
  2, 3, 0, 1, 2, 4, 0, 1,
  2, 5};
static const casadi_int casadi_s3[15] = 
  {6, 3, 0, 3, 6, 9, 0, 1,
  2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s4[3] = {6, 1, 1};
static const casadi_int casadi_s5[3] = {6, 6, 1};
static const casadi_int casadi_s6[3] = {6, 3, 1};
static const casadi_int casadi_s7[3] = {3, 1, 1};
static const casadi_int casadi_s8[3] = {0, 1, 1};
static const casadi_int casadi_s9[27] = 
  {6, 6, 0, 3, 6, 9, 12, 15,
  18, 0, 1, 2, 0, 1, 2, 0,
  1, 2, 0, 1, 2, 0, 1, 2,
  0, 1, 2};

static const casadi_real casadi_zeros[36] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0.};

/* satellite_others_expl_vde_forw:(i0[6],i1[6x6],i2[6x3],i3[3],i4[0])->(o0[6],o1[6x6,18nz],o2[6x3,12nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w00=w+6, *w01=w+12, w02, *w09=w+82, *w10=w+85, *w13=w+115, *w14=w+118, *w15=w+121, *w16=w+130;
  const casadi_real *cs, *wr00, *wr01, *wr03, *wr04, *wr05, *wr06, *wr07, *wr08, *wr09, *wr11;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 6, w00);
  /* #1: @1 = @0[3:6] */
  for (rr=w01, cs=w00+3; cs!=w00+6; cs+=1) *rr++ = *cs;
  /* #2: output[0][0] = @1 */
  casadi_copy(w01, 3, res[0]);
  /* #3: @1 = input[3][0] */
  casadi_copy(arg[3], 3, w01);
  /* #4: @2 = 16.8 */
  w02 = 1.6800000000000001e+01;
  /* #5: @1 = (@1/@2) */
  for (i=0, rr=w01; i<3; ++i) (*rr++) /= w02;
  /* #6: output[0][1] = @1 */
  if (res[0]) casadi_copy(w01, 3, res[0]+3);
  /* #7: @3 = input[1][0] */
  wr03 = arg[1] ? arg[1] : casadi_zeros;
  /* #8: {@0, @4, @5, @6, @7, @8} = horzsplit(@3) */
  wr00 = wr03;
  wr04 = wr03+6;
  wr05 = wr03+12;
  wr06 = wr03+18;
  wr07 = wr03+24;
  wr08 = wr03+30;
  /* #9: @1 = @0[3:6] */
  wr01 = wr00+3;
  /* #10: output[1][0] = @1 */
  casadi_copy(wr01, 3, res[1]);
  /* #11: @1 = @4[3:6] */
  wr01 = wr04+3;
  /* #12: output[1][1] = @1 */
  if (res[1]) casadi_copy(wr01, 3, res[1]+3);
  /* #13: @1 = @5[3:6] */
  wr01 = wr05+3;
  /* #14: output[1][2] = @1 */
  if (res[1]) casadi_copy(wr01, 3, res[1]+6);
  /* #15: @1 = @6[3:6] */
  wr01 = wr06+3;
  /* #16: output[1][3] = @1 */
  if (res[1]) casadi_copy(wr01, 3, res[1]+9);
  /* #17: @1 = @7[3:6] */
  wr01 = wr07+3;
  /* #18: output[1][4] = @1 */
  if (res[1]) casadi_copy(wr01, 3, res[1]+12);
  /* #19: @1 = @8[3:6] */
  wr01 = wr08+3;
  /* #20: output[1][5] = @1 */
  if (res[1]) casadi_copy(wr01, 3, res[1]+15);
  /* #21: @1 = zeros(3x6,3nz) */
  casadi_clear(w01, 3);
  /* #22: @9 = all_0.0595238(3x1) */
  casadi_fill(w09, 3, 5.9523809523809521e-02);
  /* #23: (@1[:3] = @9) */
  for (rr=w01+0, cs=w09; rr!=w01+3; rr+=1) *rr = *cs++;
  /* #24: @9 = @1' */
  casadi_trans(w01,casadi_s1, w09, casadi_s0, iw);
  /* #25: @10 = project(@9) */
  casadi_project(w09, casadi_s0, w10, casadi_s2, w);
  /* #26: @11 = input[2][0] */
  wr11 = arg[2] ? arg[2] : casadi_zeros;
  /* #27: {@8, @7, @6} = horzsplit(@11) */
  wr08 = wr11;
  wr07 = wr11+6;
  wr06 = wr11+12;
  /* #28: @9 = @8[3:6] */
  wr09 = wr08+3;
  /* #29: @12 = zeros(3x1,0nz) */
  /* #30: @1 = vertcat(@9, @12) */
  rr=w01;
  for (i=0, cs=wr09; i<3; ++i) *rr++ = *cs++;
  /* #31: @9 = @7[3:6] */
  wr09 = wr07+3;
  /* #32: @13 = vertcat(@9, @12) */
  rr=w13;
  for (i=0, cs=wr09; i<3; ++i) *rr++ = *cs++;
  /* #33: @9 = @6[3:6] */
  wr09 = wr06+3;
  /* #34: @14 = vertcat(@9, @12) */
  rr=w14;
  for (i=0, cs=wr09; i<3; ++i) *rr++ = *cs++;
  /* #35: @15 = horzcat(@1, @13, @14) */
  rr=w15;
  for (i=0, cs=w01; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  /* #36: @16 = project(@15) */
  casadi_project(w15, casadi_s3, w16, casadi_s2, w);
  /* #37: @10 = (@10+@16) */
  for (i=0, rr=w10, cs=w16; i<12; ++i) (*rr++) += (*cs++);
  /* #38: output[2][0] = @10 */
  casadi_copy(w10, 12, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int satellite_others_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int satellite_others_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int satellite_others_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void satellite_others_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int satellite_others_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void satellite_others_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void satellite_others_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void satellite_others_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int satellite_others_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int satellite_others_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real satellite_others_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* satellite_others_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* satellite_others_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* satellite_others_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* satellite_others_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s9;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int satellite_others_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 4;
  if (sz_w) *sz_w = 142;
  return 0;
}

CASADI_SYMBOL_EXPORT int satellite_others_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 9*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 4*sizeof(casadi_int);
  if (sz_w) *sz_w = 142*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
