//  ISC License
//
//  Copyright (c) 2026, Autonomous Vehicle Systems Lab, University of Colorado at Boulder
//
//  Permission to use, copy, modify, and/or distribute this software for any
//  purpose with or without fee is hereby granted, provided that the above
//  copyright notice and this permission notice appear in all copies.
//
//! Safe Rust access to selected Basilisk utilities with a C ABI.
//!
//! The underlying algorithms and physical constants remain defined by
//! Basilisk's own headers and implementations.  ``raw`` is generated by
//! ``../gen_rust_utilities.py``; this file only converts C arrays into
//! idiomatic fixed-size Rust arrays.
//!
//! C++/Eigen utilities are deliberately excluded.  They require a separate C
//! shim and must not be bound directly through this crate.

#![allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]

/// Generated C ABI declarations and constants from Basilisk headers.
pub mod raw;

/// Physical and unit-conversion constants from ``astroConstants.h`` and
/// ``macroDefinitions.h``.
pub mod constants {
    pub use crate::raw::{
        AU, AU2M, BSK_RUST_G_UNIVERSIAL as G_UNIVERSIAL, BSK_RUST_J2_EARTH as J2_EARTH,
        BSK_RUST_J2_MARS as J2_MARS, BSK_RUST_J3_EARTH as J3_EARTH, BSK_RUST_J4_EARTH as J4_EARTH,
        BSK_RUST_J5_EARTH as J5_EARTH, BSK_RUST_J6_EARTH as J6_EARTH, BSK_RUST_SEC2DAY as SEC2DAY,
        D2R, EARTH_GRAV, MU_EARTH, MU_JUPITER, MU_MARS, MU_MERCURY, MU_MOON, MU_NEPTUNE, MU_PLUTO,
        MU_SATURN, MU_SUN, MU_URANUS, MU_VENUS, NANO2SEC, R2D, REQ_EARTH, REQ_JUPITER, REQ_MARS,
        REQ_MERCURY, REQ_MOON, REQ_NEPTUNE, REQ_PLUTO, REQ_SATURN, REQ_SUN, REQ_URANUS, REQ_VENUS,
        RPM, RP_EARTH, RP_MARS, SEC2HOUR, SEC2NANO, SOLAR_FLUX_EARTH, SPEED_LIGHT,
    };
}

/// Basilisk orbital-mechanics functions from ``orbitalMotion.h``.
pub mod orbital {
    pub use crate::raw::{equinoctialElements as EquinoctialElements, ClassicElements};

    /// Convert Basilisk classical orbital elements to inertial position and velocity.
    ///
    /// :param mu: Central-body gravitational parameter [km^3/s^2].
    /// :param elements: Classical elements, updated by Basilisk where applicable.
    /// :returns: Position [km] and velocity [km/s] in the inertial frame.
    pub fn elements_to_state(mu: f64, elements: &mut ClassicElements) -> ([f64; 3], [f64; 3]) {
        let mut position = [0.0; 3]; // [km]
        let mut velocity = [0.0; 3]; // [km/s]
        unsafe {
            crate::raw::elem2rv(mu, elements, position.as_mut_ptr(), velocity.as_mut_ptr());
        }
        (position, velocity)
    }

    /// Convert inertial Cartesian state vectors to Basilisk classical elements.
    ///
    /// :param mu: Central-body gravitational parameter [km^3/s^2].
    /// :param position: Inertial position vector [km].
    /// :param velocity: Inertial velocity vector [km/s].
    /// :returns: Basilisk classical orbital elements.
    pub fn state_to_elements(mu: f64, position: [f64; 3], velocity: [f64; 3]) -> ClassicElements {
        let mut position = position;
        let mut velocity = velocity;
        let mut elements = ClassicElements::default();
        unsafe {
            crate::raw::rv2elem(
                mu,
                position.as_mut_ptr(),
                velocity.as_mut_ptr(),
                &mut elements,
            );
        }
        elements
    }

    /// Convert an eccentric anomaly to a true anomaly.
    ///
    /// :param eccentric_anomaly: Eccentric anomaly [rad].
    /// :param eccentricity: Orbital eccentricity [-].
    /// :returns: True anomaly [rad].
    pub fn eccentric_to_true_anomaly(eccentric_anomaly: f64, eccentricity: f64) -> f64 {
        unsafe { crate::raw::E2f(eccentric_anomaly, eccentricity) }
    }

    /// Convert a mean anomaly to an eccentric anomaly.
    ///
    /// :param mean_anomaly: Mean anomaly [rad].
    /// :param eccentricity: Orbital eccentricity [-].
    /// :returns: Eccentric anomaly [rad].
    pub fn mean_to_eccentric_anomaly(mean_anomaly: f64, eccentricity: f64) -> f64 {
        unsafe { crate::raw::M2E(mean_anomaly, eccentricity) }
    }
}

/// Basilisk modified Rodrigues parameter utilities from ``rigidBodyKinematics.h``.
pub mod attitude {
    /// Convert modified Rodrigues parameters to a direction cosine matrix.
    ///
    /// :param sigma: Modified Rodrigues parameters [-].
    /// :returns: Direction cosine matrix [-].
    pub fn mrp_to_dcm(sigma: [f64; 3]) -> [[f64; 3]; 3] {
        let mut sigma = sigma;
        let mut dcm = [[0.0; 3]; 3]; // [-]
        unsafe {
            crate::raw::MRP2C(sigma.as_mut_ptr(), dcm.as_mut_ptr());
        }
        dcm
    }

    /// Convert a direction cosine matrix to modified Rodrigues parameters.
    ///
    /// :param dcm: Direction cosine matrix [-].
    /// :returns: Modified Rodrigues parameters [-].
    pub fn dcm_to_mrp(dcm: [[f64; 3]; 3]) -> [f64; 3] {
        let mut dcm = dcm;
        let mut sigma = [0.0; 3]; // [-]
        unsafe {
            crate::raw::C2MRP(dcm.as_mut_ptr(), sigma.as_mut_ptr());
        }
        sigma
    }

    /// Compose two modified Rodrigues parameter rotations.
    ///
    /// :param first: First MRP rotation [-].
    /// :param second: Second MRP rotation [-].
    /// :returns: Composed MRP rotation [-].
    pub fn add_mrp(first: [f64; 3], second: [f64; 3]) -> [f64; 3] {
        let mut first = first;
        let mut second = second;
        let mut result = [0.0; 3]; // [-]
        unsafe {
            crate::raw::addMRP(first.as_mut_ptr(), second.as_mut_ptr(), result.as_mut_ptr());
        }
        result
    }

    /// Map an angle to Basilisk's ``[-π, π]`` convention.
    ///
    /// :param angle: Input angle [rad].
    /// :returns: Wrapped angle [rad].
    pub fn wrap_to_pi(angle: f64) -> f64 {
        unsafe { crate::raw::wrapToPi(angle) }
    }
}

#[cfg(test)]
mod tests {
    use super::constants;

    /// Ensure generated constants retain Basilisk's canonical Earth parameter.
    #[test]
    fn earth_gravitational_parameter_matches_basilisk() {
        assert_eq!(constants::MU_EARTH, 398600.436); // [km^3/s^2]
    }

    /// Ensure guarded J-coefficients are generated from the Basilisk header.
    #[test]
    fn earth_j2_matches_basilisk() {
        assert_eq!(constants::J2_EARTH, 1082.616e-6); // [-]
    }
}
