void dataInitialization(EMMConfigData *ConfigData) {
	ConfigData->cssSensorDecode.ChebyCount = 14;
	ConfigData->cssSensorDecode.KellyCheby[0] = -1734963.34695;
	ConfigData->cssSensorDecode.KellyCheby[1] = 3294117.1461;
	ConfigData->cssSensorDecode.KellyCheby[2] = -2816333.29462;
	ConfigData->cssSensorDecode.KellyCheby[3] = 2163709.94214;
	ConfigData->cssSensorDecode.KellyCheby[4] = -1488025.99386;
	ConfigData->cssSensorDecode.KellyCheby[5] = 910735.938278;
	ConfigData->cssSensorDecode.KellyCheby[6] = -491971.250029;
	ConfigData->cssSensorDecode.KellyCheby[7] = 231843.658351;
	ConfigData->cssSensorDecode.KellyCheby[8] = -93761.0504553;
	ConfigData->cssSensorDecode.KellyCheby[9] = 31775.3687343;
	ConfigData->cssSensorDecode.MaxSensorValue = 0.0005;
	ConfigData->cssSensorDecode.NumSensors = 8;
	strcpy(ConfigData->cssSensorDecode.OutputDataName,"css_data_aggregate");
	ConfigData->cssSensorDecode.OutputMsgID = 0;
	strcpy(ConfigData->cssSensorDecode.SensorListName,"css_sensors_data");
	ConfigData->cssSensorDecode.SensorMsgID = 0;
	strcpy(ConfigData->imuSensorDecode.InputDataName,"imu_meas_data");
	strcpy(ConfigData->imuSensorDecode.InputPropsName,"adcs_config_data");
	strcpy(ConfigData->imuSensorDecode.OutputDataName,"parsed_imu_data");
	ConfigData->imuSensorDecode.OutputMsgID = 0;
	ConfigData->imuSensorDecode.PropsMsgID = 0;
	ConfigData->imuSensorDecode.SensorMsgID = 0;
	ConfigData->imuSensorDecode.platform2BdyDCM[0] = 0.0;
	ConfigData->imuSensorDecode.platform2BdyDCM[1] = 0.0;
	ConfigData->imuSensorDecode.platform2BdyDCM[2] = 0.0;
	ConfigData->imuSensorDecode.platform2BdyDCM[3] = 0.0;
	ConfigData->imuSensorDecode.platform2BdyDCM[4] = 0.0;
	ConfigData->imuSensorDecode.platform2BdyDCM[5] = 0.0;
	ConfigData->imuSensorDecode.platform2BdyDCM[6] = 0.0;
	ConfigData->imuSensorDecode.platform2BdyDCM[7] = 0.0;
	ConfigData->imuSensorDecode.platform2BdyDCM[8] = 0.0;
	ConfigData->imuSensorDecode.platform2BdyDCM[9] = 0.0;
	ConfigData->imuSensorDecode.platform2StrDCM[0] = 1.0;
	ConfigData->imuSensorDecode.platform2StrDCM[1] = 0.0;
	ConfigData->imuSensorDecode.platform2StrDCM[2] = 0.0;
	ConfigData->imuSensorDecode.platform2StrDCM[3] = 0.0;
	ConfigData->imuSensorDecode.platform2StrDCM[4] = 1.0;
	ConfigData->imuSensorDecode.platform2StrDCM[5] = 0.0;
	ConfigData->imuSensorDecode.platform2StrDCM[6] = 0.0;
	ConfigData->imuSensorDecode.platform2StrDCM[7] = 0.0;
	ConfigData->imuSensorDecode.platform2StrDCM[8] = 1.0;
	ConfigData->imuSensorDecode.platform2StrDCM[9] = 6.0816419016e+247;
	strcpy(ConfigData->stSensorDecode.InputDataName,"star_tracker_state");
	strcpy(ConfigData->stSensorDecode.InputPropsName,"adcs_config_data");
	strcpy(ConfigData->stSensorDecode.OutputDataName,"parsed_st_data");
	ConfigData->stSensorDecode.OutputMsgID = 0;
	ConfigData->stSensorDecode.PropsMsgID = 0;
	ConfigData->stSensorDecode.SensorMsgID = 0;
	ConfigData->stSensorDecode.T_BdyPlatform[0] = 0.0;
	ConfigData->stSensorDecode.T_BdyPlatform[1] = 0.0;
	ConfigData->stSensorDecode.T_BdyPlatform[2] = 0.0;
	ConfigData->stSensorDecode.T_BdyPlatform[3] = 0.0;
	ConfigData->stSensorDecode.T_BdyPlatform[4] = 0.0;
	ConfigData->stSensorDecode.T_BdyPlatform[5] = 0.0;
	ConfigData->stSensorDecode.T_BdyPlatform[6] = 0.0;
	ConfigData->stSensorDecode.T_BdyPlatform[7] = 0.0;
	ConfigData->stSensorDecode.T_BdyPlatform[8] = 0.0;
	ConfigData->stSensorDecode.T_BdyPlatform[9] = 2.20186088602e-314;
	ConfigData->stSensorDecode.T_StrPlatform[0] = 1.0;
	ConfigData->stSensorDecode.T_StrPlatform[1] = 0.0;
	ConfigData->stSensorDecode.T_StrPlatform[2] = 0.0;
	ConfigData->stSensorDecode.T_StrPlatform[3] = 0.0;
	ConfigData->stSensorDecode.T_StrPlatform[4] = 1.0;
	ConfigData->stSensorDecode.T_StrPlatform[5] = 0.0;
	ConfigData->stSensorDecode.T_StrPlatform[6] = 0.0;
	ConfigData->stSensorDecode.T_StrPlatform[7] = 0.0;
	ConfigData->stSensorDecode.T_StrPlatform[8] = 1.0;
	ConfigData->stSensorDecode.T_StrPlatform[9] = 2.59454908889e+161;
}