void dataInitialization(EMMConfigData *ConfigData) {
	ConfigData->cssCommcssComm.ChebyCount = 14;
	ConfigData->cssCommcssComm.InputValues.CosValue = 0.0;
	ConfigData->cssCommcssComm.KellyCheby[0] = -1734963.34695;
	ConfigData->cssCommcssComm.KellyCheby[1] = 3294117.1461;
	ConfigData->cssCommcssComm.KellyCheby[2] = -2816333.29462;
	ConfigData->cssCommcssComm.MaxSensorValue = 0.0005;
	ConfigData->cssCommcssComm.NumSensors = 8;
	strcpy(ConfigData->cssCommcssComm.OutputDataName,"css_data_aggregate");
	ConfigData->cssCommcssComm.OutputMsgID = 0;
	strcpy(ConfigData->cssCommcssComm.SensorListName,"css_sensors_data");
	ConfigData->cssCommcssComm.SensorMsgID = 0;
	strcpy(ConfigData->imuCommimuComm.InputDataName,"imu_meas_data");
	strcpy(ConfigData->imuCommimuComm.InputPropsName,"adcs_config_data");
	ConfigData->imuCommimuComm.LocalOutput.AccelBody[0] = 0.0;
	ConfigData->imuCommimuComm.LocalOutput.AccelBody[1] = 0.0;
	ConfigData->imuCommimuComm.LocalOutput.AccelBody[2] = 0.0;
	ConfigData->imuCommimuComm.LocalOutput.AngVelBody[0] = 0.0;
	ConfigData->imuCommimuComm.LocalOutput.AngVelBody[1] = 0.0;
	ConfigData->imuCommimuComm.LocalOutput.AngVelBody[2] = 0.0;
	ConfigData->imuCommimuComm.LocalOutput.DRFrameBody[0] = 0.0;
	ConfigData->imuCommimuComm.LocalOutput.DRFrameBody[1] = 0.0;
	ConfigData->imuCommimuComm.LocalOutput.DRFrameBody[2] = 0.0;
	ConfigData->imuCommimuComm.LocalOutput.DVFrameBody[0] = 0.0;
	ConfigData->imuCommimuComm.LocalOutput.DVFrameBody[1] = 0.0;
	ConfigData->imuCommimuComm.LocalOutput.DVFrameBody[2] = 0.0;
	strcpy(ConfigData->imuCommimuComm.OutputDataName,"parsed_imu_data");
	ConfigData->imuCommimuComm.OutputMsgID = 0;
	ConfigData->imuCommimuComm.PropsMsgID = 0;
	ConfigData->imuCommimuComm.SensorMsgID = 0;
	ConfigData->imuCommimuComm.platform2BdyDCM[0] = 0.0;
	ConfigData->imuCommimuComm.platform2BdyDCM[1] = 0.0;
	ConfigData->imuCommimuComm.platform2BdyDCM[2] = 0.0;
	ConfigData->imuCommimuComm.platform2StrDCM[0] = 1.0;
	ConfigData->imuCommimuComm.platform2StrDCM[1] = 0.0;
	ConfigData->imuCommimuComm.platform2StrDCM[2] = 0.0;
	strcpy(ConfigData->stCommstComm.InputDataName,"star_tracker_state");
	strcpy(ConfigData->stCommstComm.InputPropsName,"adcs_config_data");
	ConfigData->stCommstComm.LocalOutput.MRP_BdyInrtl[0] = 0.0;
	ConfigData->stCommstComm.LocalOutput.MRP_BdyInrtl[1] = 0.0;
	ConfigData->stCommstComm.LocalOutput.MRP_BdyInrtl[2] = 0.0;
	ConfigData->stCommstComm.LocalOutput.timeTag = 0.0;
	strcpy(ConfigData->stCommstComm.OutputDataName,"parsed_st_data");
	ConfigData->stCommstComm.OutputMsgID = 0;
	ConfigData->stCommstComm.PropsMsgID = 0;
	ConfigData->stCommstComm.SensorMsgID = 0;
	ConfigData->stCommstComm.T_BdyPlatform[0] = 0.0;
	ConfigData->stCommstComm.T_BdyPlatform[1] = 0.0;
	ConfigData->stCommstComm.T_BdyPlatform[2] = 0.0;
	ConfigData->stCommstComm.T_StrPlatform[0] = 1.0;
	ConfigData->stCommstComm.T_StrPlatform[1] = 0.0;
	ConfigData->stCommstComm.T_StrPlatform[2] = 0.0;
	ConfigData->TaskList_12_TaskModel_0.attRefOut.domega_RN_N[0] = 0.0;
	ConfigData->TaskList_12_TaskModel_0.attRefOut.domega_RN_N[1] = 0.0;
	ConfigData->TaskList_12_TaskModel_0.attRefOut.domega_RN_N[2] = 0.0;
	ConfigData->TaskList_12_TaskModel_0.attRefOut.omega_RN_N[0] = 0.0;
	ConfigData->TaskList_12_TaskModel_0.attRefOut.omega_RN_N[1] = 0.0;
	ConfigData->TaskList_12_TaskModel_0.attRefOut.omega_RN_N[2] = 0.0;
	ConfigData->TaskList_12_TaskModel_0.attRefOut.sigma_RN[0] = 0.0;
	ConfigData->TaskList_12_TaskModel_0.attRefOut.sigma_RN[1] = 0.0;
	ConfigData->TaskList_12_TaskModel_0.attRefOut.sigma_RN[2] = 0.0;
	strcpy(ConfigData->TaskList_12_TaskModel_0.outputDataName,"att_ref_output_stage1");
	ConfigData->TaskList_12_TaskModel_0.outputMsgID = 0;
	ConfigData->TaskList_12_TaskModel_0.sigma_R0N[0] = 0.0;
	ConfigData->TaskList_12_TaskModel_0.sigma_R0N[1] = 0.0;
	ConfigData->TaskList_12_TaskModel_0.sigma_R0N[2] = 0.0;
	ConfigData->TaskList_13_TaskModel_0.attRefOut.domega_RN_N[0] = 0.0;
	ConfigData->TaskList_13_TaskModel_0.attRefOut.domega_RN_N[1] = 0.0;
	ConfigData->TaskList_13_TaskModel_0.attRefOut.domega_RN_N[2] = 0.0;
	ConfigData->TaskList_13_TaskModel_0.attRefOut.omega_RN_N[0] = 0.0;
	ConfigData->TaskList_13_TaskModel_0.attRefOut.omega_RN_N[1] = 0.0;
	ConfigData->TaskList_13_TaskModel_0.attRefOut.omega_RN_N[2] = 0.0;
	ConfigData->TaskList_13_TaskModel_0.attRefOut.sigma_RN[0] = 0.0;
	ConfigData->TaskList_13_TaskModel_0.attRefOut.sigma_RN[1] = 0.0;
	ConfigData->TaskList_13_TaskModel_0.attRefOut.sigma_RN[2] = 0.0;
	ConfigData->TaskList_13_TaskModel_0.inputCelID = 0;
	strcpy(ConfigData->TaskList_13_TaskModel_0.inputCelMessName,"mars_display_frame_data");
	strcpy(ConfigData->TaskList_13_TaskModel_0.inputNavDataName,"simple_nav_output");
	ConfigData->TaskList_13_TaskModel_0.inputNavID = 0;
	strcpy(ConfigData->TaskList_13_TaskModel_0.outputDataName,"att_ref_output_stage1");
	ConfigData->TaskList_13_TaskModel_0.outputMsgID = 0;
	ConfigData->TaskList_14_TaskModel_0.attRefOut.domega_RN_N[0] = 0.0;
	ConfigData->TaskList_14_TaskModel_0.attRefOut.domega_RN_N[1] = 0.0;
	ConfigData->TaskList_14_TaskModel_0.attRefOut.domega_RN_N[2] = 0.0;
	ConfigData->TaskList_14_TaskModel_0.attRefOut.omega_RN_N[0] = 0.0;
	ConfigData->TaskList_14_TaskModel_0.attRefOut.omega_RN_N[1] = 0.0;
	ConfigData->TaskList_14_TaskModel_0.attRefOut.omega_RN_N[2] = 0.0;
	ConfigData->TaskList_14_TaskModel_0.attRefOut.sigma_RN[0] = 0.0;
	ConfigData->TaskList_14_TaskModel_0.attRefOut.sigma_RN[1] = 0.0;
	ConfigData->TaskList_14_TaskModel_0.attRefOut.sigma_RN[2] = 0.0;
	ConfigData->TaskList_14_TaskModel_0.inputCelID = 0;
	strcpy(ConfigData->TaskList_14_TaskModel_0.inputCelMessName,"mars_display_frame_data");
	strcpy(ConfigData->TaskList_14_TaskModel_0.inputNavDataName,"simple_nav_output");
	ConfigData->TaskList_14_TaskModel_0.inputNavID = 0;
	ConfigData->TaskList_14_TaskModel_0.mu = 1.32712440018e+20;
	ConfigData->TaskList_14_TaskModel_0.oe.Omega = 0.0;
	ConfigData->TaskList_14_TaskModel_0.oe.a = 0.0;
	ConfigData->TaskList_14_TaskModel_0.oe.alpha = 0.0;
	ConfigData->TaskList_14_TaskModel_0.oe.e = 0.0;
	ConfigData->TaskList_14_TaskModel_0.oe.f = 0.0;
	ConfigData->TaskList_14_TaskModel_0.oe.i = 0.0;
	ConfigData->TaskList_14_TaskModel_0.oe.omega = 0.0;
	ConfigData->TaskList_14_TaskModel_0.oe.rApoap = 0.0;
	ConfigData->TaskList_14_TaskModel_0.oe.rPeriap = 0.0;
	ConfigData->TaskList_14_TaskModel_0.oe.rmag = 0.0;
	strcpy(ConfigData->TaskList_14_TaskModel_0.outputDataName,"att_ref_output");
	ConfigData->TaskList_14_TaskModel_0.outputMsgID = 0;
	ConfigData->TaskList_15_TaskModel_0.R_P1[0] = 0.0;
	ConfigData->TaskList_15_TaskModel_0.R_P1[1] = 0.0;
	ConfigData->TaskList_15_TaskModel_0.R_P1[2] = 0.0;
	ConfigData->TaskList_15_TaskModel_0.R_P2[0] = 0.0;
	ConfigData->TaskList_15_TaskModel_0.R_P2[1] = 0.0;
	ConfigData->TaskList_15_TaskModel_0.R_P2[2] = 0.0;
	ConfigData->TaskList_15_TaskModel_0.a_P1[0] = 0.0;
	ConfigData->TaskList_15_TaskModel_0.a_P1[1] = 0.0;
	ConfigData->TaskList_15_TaskModel_0.a_P1[2] = 0.0;
	ConfigData->TaskList_15_TaskModel_0.a_P2[0] = 0.0;
	ConfigData->TaskList_15_TaskModel_0.a_P2[1] = 0.0;
	ConfigData->TaskList_15_TaskModel_0.a_P2[2] = 0.0;
	ConfigData->TaskList_15_TaskModel_0.attRefOut.domega_RN_N[0] = 0.0;
	ConfigData->TaskList_15_TaskModel_0.attRefOut.domega_RN_N[1] = 0.0;
	ConfigData->TaskList_15_TaskModel_0.attRefOut.domega_RN_N[2] = 0.0;
	ConfigData->TaskList_15_TaskModel_0.attRefOut.omega_RN_N[0] = 0.0;
	ConfigData->TaskList_15_TaskModel_0.attRefOut.omega_RN_N[1] = 0.0;
	ConfigData->TaskList_15_TaskModel_0.attRefOut.omega_RN_N[2] = 0.0;
	ConfigData->TaskList_15_TaskModel_0.attRefOut.sigma_RN[0] = 0.0;
	ConfigData->TaskList_15_TaskModel_0.attRefOut.sigma_RN[1] = 0.0;
	ConfigData->TaskList_15_TaskModel_0.attRefOut.sigma_RN[2] = 0.0;
	ConfigData->TaskList_15_TaskModel_0.inputCelID = 0;
	strcpy(ConfigData->TaskList_15_TaskModel_0.inputCelMessName,"mars_display_frame_data");
	strcpy(ConfigData->TaskList_15_TaskModel_0.inputNavDataName,"simple_nav_output");
	ConfigData->TaskList_15_TaskModel_0.inputNavID = 0;
	ConfigData->TaskList_15_TaskModel_0.inputSecID = 0;
	strcpy(ConfigData->TaskList_15_TaskModel_0.inputSecMessName,"");
	strcpy(ConfigData->TaskList_15_TaskModel_0.outputDataName,"att_ref_output");
	ConfigData->TaskList_15_TaskModel_0.outputMsgID = 0;
	ConfigData->TaskList_15_TaskModel_0.singularityThresh = 0.0174532925199;
	ConfigData->TaskList_15_TaskModel_0.v_P1[0] = 0.0;
	ConfigData->TaskList_15_TaskModel_0.v_P1[1] = 0.0;
	ConfigData->TaskList_15_TaskModel_0.v_P1[2] = 0.0;
	ConfigData->TaskList_15_TaskModel_0.v_P2[0] = 0.0;
	ConfigData->TaskList_15_TaskModel_0.v_P2[1] = 0.0;
	ConfigData->TaskList_15_TaskModel_0.v_P2[2] = 0.0;
	ConfigData->TaskList_19_TaskModel_0.mnvrActive = 0;
	ConfigData->TaskList_19_TaskModel_0.mnvrComplete = 0;
	ConfigData->TaskList_19_TaskModel_0.mnvrStartTime = 0;
	ConfigData->TaskList_19_TaskModel_0.numRasters = 12;
	ConfigData->TaskList_19_TaskModel_0.outputAngleRates.set[0] = 0.0;
	ConfigData->TaskList_19_TaskModel_0.outputAngleRates.set[1] = 0.0;
	ConfigData->TaskList_19_TaskModel_0.outputAngleRates.set[2] = 0.0;
	ConfigData->TaskList_19_TaskModel_0.outputAngleSet.set[0] = 0.0;
	ConfigData->TaskList_19_TaskModel_0.outputAngleSet.set[1] = 0.0;
	ConfigData->TaskList_19_TaskModel_0.outputAngleSet.set[2] = 0.0;
	ConfigData->TaskList_19_TaskModel_0.outputEulerRatesID = 0;
	strcpy(ConfigData->TaskList_19_TaskModel_0.outputEulerRatesName,"euler_angle_rates");
	ConfigData->TaskList_19_TaskModel_0.outputEulerSetID = 0;
	strcpy(ConfigData->TaskList_19_TaskModel_0.outputEulerSetName,"euler_angle_set");
	ConfigData->TaskList_19_TaskModel_0.rasterTimes[0] = 720.0;
	ConfigData->TaskList_19_TaskModel_0.rasterTimes[1] = 360.0;
	ConfigData->TaskList_19_TaskModel_0.rasterTimes[2] = 360.0;
	ConfigData->TaskList_19_TaskModel_0.scanSelector = 0;
	ConfigData->TaskList_19_TaskModel_0.scanningAngles[0] = 0.0;
	ConfigData->TaskList_19_TaskModel_0.scanningAngles[1] = 0.0;
	ConfigData->TaskList_19_TaskModel_0.scanningAngles[2] = 0.0;
	ConfigData->TaskList_19_TaskModel_0.scanningRates[0] = 0.0;
	ConfigData->TaskList_19_TaskModel_0.scanningRates[1] = 0.0;
	ConfigData->TaskList_19_TaskModel_0.scanningRates[2] = 0.000349065850399;
	ConfigData->TaskList_19_TaskModel_1.angleRates[0] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.angleRates[1] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.angleRates[2] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.angleSet[0] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.angleSet[1] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.angleSet[2] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.attRefOut.domega_RN_N[0] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.attRefOut.domega_RN_N[1] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.attRefOut.domega_RN_N[2] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.attRefOut.omega_RN_N[0] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.attRefOut.omega_RN_N[1] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.attRefOut.omega_RN_N[2] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.attRefOut.sigma_RN[0] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.attRefOut.sigma_RN[1] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.attRefOut.sigma_RN[2] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.cmdRates[0] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.cmdRates[1] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.cmdRates[2] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.cmdSet[0] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.cmdSet[1] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.cmdSet[2] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.dt = 0.0;
	ConfigData->TaskList_19_TaskModel_1.eulerRatesOut.set[0] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.eulerRatesOut.set[1] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.eulerRatesOut.set[2] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.eulerSetOut.set[0] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.eulerSetOut.set[1] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.eulerSetOut.set[2] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.inputEulerRatesID = 0;
	strcpy(ConfigData->TaskList_19_TaskModel_1.inputEulerRatesName,"");
	ConfigData->TaskList_19_TaskModel_1.inputEulerSetID = 0;
	strcpy(ConfigData->TaskList_19_TaskModel_1.inputEulerSetName,"");
	ConfigData->TaskList_19_TaskModel_1.inputRefID = 0;
	strcpy(ConfigData->TaskList_19_TaskModel_1.inputRefName,"att_ref_output_stage1");
	strcpy(ConfigData->TaskList_19_TaskModel_1.outputDataName,"att_ref_output");
	ConfigData->TaskList_19_TaskModel_1.outputEulerRatesID = 0;
	strcpy(ConfigData->TaskList_19_TaskModel_1.outputEulerRatesName,"euler_rates_output");
	ConfigData->TaskList_19_TaskModel_1.outputEulerSetID = 0;
	strcpy(ConfigData->TaskList_19_TaskModel_1.outputEulerSetName,"euler_set_output");
	ConfigData->TaskList_19_TaskModel_1.outputMsgID = 0;
	ConfigData->TaskList_19_TaskModel_1.priorCmdRates[0] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.priorCmdRates[1] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.priorCmdRates[2] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.priorCmdSet[0] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.priorCmdSet[1] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.priorCmdSet[2] = 0.0;
	ConfigData->TaskList_19_TaskModel_1.priorTime = 0;
	ConfigData->TaskList_20_TaskModel_0.angleRates[0] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.angleRates[1] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.angleRates[2] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.angleSet[0] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.angleSet[1] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.angleSet[2] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.attRefOut.domega_RN_N[0] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.attRefOut.domega_RN_N[1] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.attRefOut.domega_RN_N[2] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.attRefOut.omega_RN_N[0] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.attRefOut.omega_RN_N[1] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.attRefOut.omega_RN_N[2] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.attRefOut.sigma_RN[0] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.attRefOut.sigma_RN[1] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.attRefOut.sigma_RN[2] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.cmdRates[0] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.cmdRates[1] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.cmdRates[2] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.cmdSet[0] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.cmdSet[1] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.cmdSet[2] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.dt = 0.0;
	ConfigData->TaskList_20_TaskModel_0.eulerRatesOut.set[0] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.eulerRatesOut.set[1] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.eulerRatesOut.set[2] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.eulerSetOut.set[0] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.eulerSetOut.set[1] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.eulerSetOut.set[2] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.inputEulerRatesID = 0;
	strcpy(ConfigData->TaskList_20_TaskModel_0.inputEulerRatesName,"");
	ConfigData->TaskList_20_TaskModel_0.inputEulerSetID = 0;
	strcpy(ConfigData->TaskList_20_TaskModel_0.inputEulerSetName,"");
	ConfigData->TaskList_20_TaskModel_0.inputRefID = 0;
	strcpy(ConfigData->TaskList_20_TaskModel_0.inputRefName,"att_ref_output_stage1");
	strcpy(ConfigData->TaskList_20_TaskModel_0.outputDataName,"att_ref_output");
	ConfigData->TaskList_20_TaskModel_0.outputEulerRatesID = 0;
	strcpy(ConfigData->TaskList_20_TaskModel_0.outputEulerRatesName,"euler_rates_output");
	ConfigData->TaskList_20_TaskModel_0.outputEulerSetID = 0;
	strcpy(ConfigData->TaskList_20_TaskModel_0.outputEulerSetName,"euler_set_output");
	ConfigData->TaskList_20_TaskModel_0.outputMsgID = 0;
	ConfigData->TaskList_20_TaskModel_0.priorCmdRates[0] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.priorCmdRates[1] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.priorCmdRates[2] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.priorCmdSet[0] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.priorCmdSet[1] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.priorCmdSet[2] = 0.0;
	ConfigData->TaskList_20_TaskModel_0.priorTime = 0;
	ConfigData->TaskList_22_TaskModel_0.attGuidOut.domega_RN_B[0] = 0.0;
	ConfigData->TaskList_22_TaskModel_0.attGuidOut.domega_RN_B[1] = 0.0;
	ConfigData->TaskList_22_TaskModel_0.attGuidOut.domega_RN_B[2] = 0.0;
	ConfigData->TaskList_22_TaskModel_0.attGuidOut.omega_BR_B[0] = 0.0;
	ConfigData->TaskList_22_TaskModel_0.attGuidOut.omega_BR_B[1] = 0.0;
	ConfigData->TaskList_22_TaskModel_0.attGuidOut.omega_BR_B[2] = 0.0;
	ConfigData->TaskList_22_TaskModel_0.attGuidOut.omega_RN_B[0] = 0.0;
	ConfigData->TaskList_22_TaskModel_0.attGuidOut.omega_RN_B[1] = 0.0;
	ConfigData->TaskList_22_TaskModel_0.attGuidOut.omega_RN_B[2] = 0.0;
	ConfigData->TaskList_22_TaskModel_0.attGuidOut.sigma_BR[0] = 0.0;
	ConfigData->TaskList_22_TaskModel_0.attGuidOut.sigma_BR[1] = 0.0;
	ConfigData->TaskList_22_TaskModel_0.attGuidOut.sigma_BR[2] = 0.0;
	ConfigData->TaskList_22_TaskModel_0.inputNavID = 0;
	strcpy(ConfigData->TaskList_22_TaskModel_0.inputNavName,"simple_nav_output");
	ConfigData->TaskList_22_TaskModel_0.inputRefID = 0;
	strcpy(ConfigData->TaskList_22_TaskModel_0.inputRefName,"att_ref_output");
	strcpy(ConfigData->TaskList_22_TaskModel_0.outputDataName,"nom_att_guid_out");
	ConfigData->TaskList_22_TaskModel_0.outputMsgID = 0;
	ConfigData->TaskList_22_TaskModel_0.sigma_BcB = None;
	ConfigData->TaskList_22_TaskModel_0.sigma_R0R[0] = 0.0;
	ConfigData->TaskList_22_TaskModel_0.sigma_R0R[1] = 0.0;
	ConfigData->TaskList_22_TaskModel_0.sigma_R0R[2] = 0.0;
	ConfigData->errorDeadband.attGuidOut.domega_RN_B[0] = 0.0;
	ConfigData->errorDeadband.attGuidOut.domega_RN_B[1] = 0.0;
	ConfigData->errorDeadband.attGuidOut.domega_RN_B[2] = 0.0;
	ConfigData->errorDeadband.attGuidOut.omega_BR_B[0] = 0.0;
	ConfigData->errorDeadband.attGuidOut.omega_BR_B[1] = 0.0;
	ConfigData->errorDeadband.attGuidOut.omega_BR_B[2] = 0.0;
	ConfigData->errorDeadband.attGuidOut.omega_RN_B[0] = 0.0;
	ConfigData->errorDeadband.attGuidOut.omega_RN_B[1] = 0.0;
	ConfigData->errorDeadband.attGuidOut.omega_RN_B[2] = 0.0;
	ConfigData->errorDeadband.attGuidOut.sigma_BR[0] = 0.0;
	ConfigData->errorDeadband.attGuidOut.sigma_BR[1] = 0.0;
	ConfigData->errorDeadband.attGuidOut.sigma_BR[2] = 0.0;
	ConfigData->errorDeadband.error = 0.0;
	ConfigData->errorDeadband.innerThresh = 0.0698131700798;
	ConfigData->errorDeadband.inputGuidID = 0;
	strcpy(ConfigData->errorDeadband.inputGuidName,"sun_safe_att_err");
	ConfigData->errorDeadband.omega_BR_B[0] = 0.0;
	ConfigData->errorDeadband.omega_BR_B[1] = 0.0;
	ConfigData->errorDeadband.omega_BR_B[2] = 0.0;
	ConfigData->errorDeadband.outerThresh = 0.305432619099;
	strcpy(ConfigData->errorDeadband.outputDataName,"db_att_guid_out");
	ConfigData->errorDeadband.outputGuidID = 0;
	ConfigData->errorDeadband.sigma_BR[0] = 0.0;
	ConfigData->errorDeadband.sigma_BR[1] = 0.0;
	ConfigData->errorDeadband.sigma_BR[2] = 0.0;
	ConfigData->TaskList_23_TaskModel_0.GsMatrix[0] = 0.0;
	ConfigData->TaskList_23_TaskModel_0.GsMatrix[1] = 0.0;
	ConfigData->TaskList_23_TaskModel_0.GsMatrix[2] = 0.0;
	ConfigData->TaskList_23_TaskModel_0.JsList[0] = 0.0;
	ConfigData->TaskList_23_TaskModel_0.JsList[1] = 0.0;
	ConfigData->TaskList_23_TaskModel_0.JsList[2] = 0.0;
	ConfigData->TaskList_23_TaskModel_0.K1 = 0.3;
	ConfigData->TaskList_23_TaskModel_0.K3 = 1.0;
	ConfigData->TaskList_23_TaskModel_0.Ki = -1.0;
	ConfigData->TaskList_23_TaskModel_0.P = 150.0;
	ConfigData->TaskList_23_TaskModel_0.controlOut.torqueRequestBody[0] = 0.0;
	ConfigData->TaskList_23_TaskModel_0.controlOut.torqueRequestBody[1] = 0.0;
	ConfigData->TaskList_23_TaskModel_0.controlOut.torqueRequestBody[2] = 0.0;
	ConfigData->TaskList_23_TaskModel_0.ignoreOuterLoopFeedforward = 0;
	ConfigData->TaskList_23_TaskModel_0.inputGuidID = 0;
	strcpy(ConfigData->TaskList_23_TaskModel_0.inputGuidName,"nom_att_guid_out");
	ConfigData->TaskList_23_TaskModel_0.inputRWConfID = 0;
	strcpy(ConfigData->TaskList_23_TaskModel_0.inputRWConfigData,"rwa_config_data");
	ConfigData->TaskList_23_TaskModel_0.inputRWSpeedsID = 0;
	strcpy(ConfigData->TaskList_23_TaskModel_0.inputRWSpeedsName,"reactionwheel_output_states");
	ConfigData->TaskList_23_TaskModel_0.inputVehicleConfigDataID = 0;
	strcpy(ConfigData->TaskList_23_TaskModel_0.inputVehicleConfigDataName,"adcs_config_data");
	ConfigData->TaskList_23_TaskModel_0.integralLimit = 0.0;
	ConfigData->TaskList_23_TaskModel_0.numRWAs = 4;
	ConfigData->TaskList_23_TaskModel_0.omega_max = 0.0261799387799;
	strcpy(ConfigData->TaskList_23_TaskModel_0.outputDataName,"controlTorqueRaw");
	ConfigData->TaskList_23_TaskModel_0.outputMsgID = 0;
	ConfigData->TaskList_23_TaskModel_0.priorTime = 0;
	ConfigData->TaskList_23_TaskModel_0.z[0] = 0.0;
	ConfigData->TaskList_23_TaskModel_0.z[1] = 0.0;
	ConfigData->TaskList_23_TaskModel_0.z[2] = 0.0;
	strcpy(ConfigData->TaskList_23_TaskModel_1.inputControlName,"controlTorqueRaw");
	ConfigData->TaskList_23_TaskModel_1.inputMsgID = 0;
	ConfigData->TaskList_23_TaskModel_1.numThrGroups = 1;
	ConfigData->TaskList_23_TaskModel_1.thrGroups.cmdRequests.effectorRequest[0] = 0.0;
	ConfigData->TaskList_23_TaskModel_1.thrGroups.cmdRequests.effectorRequest[1] = 0.0;
	ConfigData->TaskList_23_TaskModel_1.thrGroups.cmdRequests.effectorRequest[2] = 0.0;
	ConfigData->TaskList_23_TaskModel_1.thrGroups.maxNumCmds = 4;
	ConfigData->TaskList_23_TaskModel_1.thrGroups.minThrustRequest = -10.0;
	ConfigData->TaskList_23_TaskModel_1.thrGroups.nomThrustOn = 0.0;
	ConfigData->TaskList_23_TaskModel_1.thrGroups.numEffectors = 4;
	strcpy(ConfigData->TaskList_23_TaskModel_1.thrGroups.outputDataName,"reactionwheel_cmds_raw");
	ConfigData->TaskList_23_TaskModel_1.thrGroups.outputMsgID = 0;
	ConfigData->TaskList_23_TaskModel_1.thrGroups.thrOnMap[0] = 0.5;
	ConfigData->TaskList_23_TaskModel_1.thrGroups.thrOnMap[1] = 0.5;
	ConfigData->TaskList_23_TaskModel_1.thrGroups.thrOnMap[2] = 0.707106781187;
	ConfigData->TaskList_23_TaskModel_2.GsInverse[0] = 0.0;
	ConfigData->TaskList_23_TaskModel_2.GsInverse[1] = 0.0;
	ConfigData->TaskList_23_TaskModel_2.GsInverse[2] = 0.0;
	ConfigData->TaskList_23_TaskModel_2.OmegaGain = 0.002;
	ConfigData->TaskList_23_TaskModel_2.inputRWCmdsID = 0;
	strcpy(ConfigData->TaskList_23_TaskModel_2.inputRWCommands,"reactionwheel_cmds_raw");
	ConfigData->TaskList_23_TaskModel_2.inputRWConfID = 0;
	strcpy(ConfigData->TaskList_23_TaskModel_2.inputRWConfigData,"rwa_config_data");
	strcpy(ConfigData->TaskList_23_TaskModel_2.inputRWSpeeds,"reactionwheel_output_states");
	ConfigData->TaskList_23_TaskModel_2.inputSpeedsID = 0;
	ConfigData->TaskList_23_TaskModel_2.numWheels = 4;
	strcpy(ConfigData->TaskList_23_TaskModel_2.outputControlName,"reactionwheel_cmds");
	ConfigData->TaskList_23_TaskModel_2.outputMsgID = 0;
	ConfigData->TaskList_24_TaskModel_0.attGuidOut.domega_RN_B[0] = 0.0;
	ConfigData->TaskList_24_TaskModel_0.attGuidOut.domega_RN_B[1] = 0.0;
	ConfigData->TaskList_24_TaskModel_0.attGuidOut.domega_RN_B[2] = 0.0;
	ConfigData->TaskList_24_TaskModel_0.attGuidOut.omega_BR_B[0] = 0.0;
	ConfigData->TaskList_24_TaskModel_0.attGuidOut.omega_BR_B[1] = 0.0;
	ConfigData->TaskList_24_TaskModel_0.attGuidOut.omega_BR_B[2] = 0.0;
	ConfigData->TaskList_24_TaskModel_0.attGuidOut.omega_RN_B[0] = 0.0;
	ConfigData->TaskList_24_TaskModel_0.attGuidOut.omega_RN_B[1] = 0.0;
	ConfigData->TaskList_24_TaskModel_0.attGuidOut.omega_RN_B[2] = 0.0;
	ConfigData->TaskList_24_TaskModel_0.attGuidOut.sigma_BR[0] = 0.0;
	ConfigData->TaskList_24_TaskModel_0.attGuidOut.sigma_BR[1] = 0.0;
	ConfigData->TaskList_24_TaskModel_0.attGuidOut.sigma_BR[2] = 0.0;
	ConfigData->TaskList_24_TaskModel_0.inputNavID = 0;
	strcpy(ConfigData->TaskList_24_TaskModel_0.inputNavName,"simple_nav_output");
	ConfigData->TaskList_24_TaskModel_0.inputRefID = 0;
	strcpy(ConfigData->TaskList_24_TaskModel_0.inputRefName,"att_ref_output");
	strcpy(ConfigData->TaskList_24_TaskModel_0.outputDataName,"nom_att_guid_out");
	ConfigData->TaskList_24_TaskModel_0.outputMsgID = 0;
	ConfigData->TaskList_24_TaskModel_0.sigma_BcB = None;
	ConfigData->TaskList_24_TaskModel_0.sigma_R0R[0] = 0.0;
	ConfigData->TaskList_24_TaskModel_0.sigma_R0R[1] = 0.0;
	ConfigData->TaskList_24_TaskModel_0.sigma_R0R[2] = 0.0;
	ConfigData->TaskList_24_TaskModel_1.GsMatrix[0] = 0.0;
	ConfigData->TaskList_24_TaskModel_1.GsMatrix[1] = 0.0;
	ConfigData->TaskList_24_TaskModel_1.GsMatrix[2] = 0.0;
	ConfigData->TaskList_24_TaskModel_1.JsList[0] = 0.0;
	ConfigData->TaskList_24_TaskModel_1.JsList[1] = 0.0;
	ConfigData->TaskList_24_TaskModel_1.JsList[2] = 0.0;
	ConfigData->TaskList_24_TaskModel_1.K1 = 0.3;
	ConfigData->TaskList_24_TaskModel_1.K3 = 1.0;
	ConfigData->TaskList_24_TaskModel_1.Ki = -1.0;
	ConfigData->TaskList_24_TaskModel_1.P = 150.0;
	ConfigData->TaskList_24_TaskModel_1.controlOut.torqueRequestBody[0] = 0.0;
	ConfigData->TaskList_24_TaskModel_1.controlOut.torqueRequestBody[1] = 0.0;
	ConfigData->TaskList_24_TaskModel_1.controlOut.torqueRequestBody[2] = 0.0;
	ConfigData->TaskList_24_TaskModel_1.ignoreOuterLoopFeedforward = 0;
	ConfigData->TaskList_24_TaskModel_1.inputGuidID = 0;
	strcpy(ConfigData->TaskList_24_TaskModel_1.inputGuidName,"nom_att_guid_out");
	ConfigData->TaskList_24_TaskModel_1.inputRWConfID = 0;
	strcpy(ConfigData->TaskList_24_TaskModel_1.inputRWConfigData,"rwa_config_data");
	ConfigData->TaskList_24_TaskModel_1.inputRWSpeedsID = 0;
	strcpy(ConfigData->TaskList_24_TaskModel_1.inputRWSpeedsName,"reactionwheel_output_states");
	ConfigData->TaskList_24_TaskModel_1.inputVehicleConfigDataID = 0;
	strcpy(ConfigData->TaskList_24_TaskModel_1.inputVehicleConfigDataName,"adcs_config_data");
	ConfigData->TaskList_24_TaskModel_1.integralLimit = 0.0;
	ConfigData->TaskList_24_TaskModel_1.numRWAs = 4;
	ConfigData->TaskList_24_TaskModel_1.omega_max = 0.0261799387799;
	strcpy(ConfigData->TaskList_24_TaskModel_1.outputDataName,"controlTorqueRaw");
	ConfigData->TaskList_24_TaskModel_1.outputMsgID = 0;
	ConfigData->TaskList_24_TaskModel_1.priorTime = 0;
	ConfigData->TaskList_24_TaskModel_1.z[0] = 0.0;
	ConfigData->TaskList_24_TaskModel_1.z[1] = 0.0;
	ConfigData->TaskList_24_TaskModel_1.z[2] = 0.0;
	strcpy(ConfigData->TaskList_24_TaskModel_2.inputControlName,"controlTorqueRaw");
	ConfigData->TaskList_24_TaskModel_2.inputMsgID = 0;
	ConfigData->TaskList_24_TaskModel_2.numThrGroups = 1;
	ConfigData->TaskList_24_TaskModel_2.thrGroups.cmdRequests.effectorRequest[0] = 0.0;
	ConfigData->TaskList_24_TaskModel_2.thrGroups.cmdRequests.effectorRequest[1] = 0.0;
	ConfigData->TaskList_24_TaskModel_2.thrGroups.cmdRequests.effectorRequest[2] = 0.0;
	ConfigData->TaskList_24_TaskModel_2.thrGroups.maxNumCmds = 4;
	ConfigData->TaskList_24_TaskModel_2.thrGroups.minThrustRequest = -10.0;
	ConfigData->TaskList_24_TaskModel_2.thrGroups.nomThrustOn = 0.0;
	ConfigData->TaskList_24_TaskModel_2.thrGroups.numEffectors = 4;
	strcpy(ConfigData->TaskList_24_TaskModel_2.thrGroups.outputDataName,"reactionwheel_cmds_raw");
	ConfigData->TaskList_24_TaskModel_2.thrGroups.outputMsgID = 0;
	ConfigData->TaskList_24_TaskModel_2.thrGroups.thrOnMap[0] = 0.5;
	ConfigData->TaskList_24_TaskModel_2.thrGroups.thrOnMap[1] = 0.5;
	ConfigData->TaskList_24_TaskModel_2.thrGroups.thrOnMap[2] = 0.707106781187;
	ConfigData->TaskList_24_TaskModel_3.GsInverse[0] = 0.0;
	ConfigData->TaskList_24_TaskModel_3.GsInverse[1] = 0.0;
	ConfigData->TaskList_24_TaskModel_3.GsInverse[2] = 0.0;
	ConfigData->TaskList_24_TaskModel_3.OmegaGain = 0.002;
	ConfigData->TaskList_24_TaskModel_3.inputRWCmdsID = 0;
	strcpy(ConfigData->TaskList_24_TaskModel_3.inputRWCommands,"reactionwheel_cmds_raw");
	ConfigData->TaskList_24_TaskModel_3.inputRWConfID = 0;
	strcpy(ConfigData->TaskList_24_TaskModel_3.inputRWConfigData,"rwa_config_data");
	strcpy(ConfigData->TaskList_24_TaskModel_3.inputRWSpeeds,"reactionwheel_output_states");
	ConfigData->TaskList_24_TaskModel_3.inputSpeedsID = 0;
	ConfigData->TaskList_24_TaskModel_3.numWheels = 4;
	strcpy(ConfigData->TaskList_24_TaskModel_3.outputControlName,"reactionwheel_cmds");
	ConfigData->TaskList_24_TaskModel_3.outputMsgID = 0;
	ConfigData->TaskList_25_TaskModel_0.attGuidOut.domega_RN_B[0] = 0.0;
	ConfigData->TaskList_25_TaskModel_0.attGuidOut.domega_RN_B[1] = 0.0;
	ConfigData->TaskList_25_TaskModel_0.attGuidOut.domega_RN_B[2] = 0.0;
	ConfigData->TaskList_25_TaskModel_0.attGuidOut.omega_BR_B[0] = 0.0;
	ConfigData->TaskList_25_TaskModel_0.attGuidOut.omega_BR_B[1] = 0.0;
	ConfigData->TaskList_25_TaskModel_0.attGuidOut.omega_BR_B[2] = 0.0;
	ConfigData->TaskList_25_TaskModel_0.attGuidOut.omega_RN_B[0] = 0.0;
	ConfigData->TaskList_25_TaskModel_0.attGuidOut.omega_RN_B[1] = 0.0;
	ConfigData->TaskList_25_TaskModel_0.attGuidOut.omega_RN_B[2] = 0.0;
	ConfigData->TaskList_25_TaskModel_0.attGuidOut.sigma_BR[0] = 0.0;
	ConfigData->TaskList_25_TaskModel_0.attGuidOut.sigma_BR[1] = 0.0;
	ConfigData->TaskList_25_TaskModel_0.attGuidOut.sigma_BR[2] = 0.0;
	ConfigData->TaskList_25_TaskModel_0.inputNavID = 0;
	strcpy(ConfigData->TaskList_25_TaskModel_0.inputNavName,"simple_nav_output");
	ConfigData->TaskList_25_TaskModel_0.inputRefID = 0;
	strcpy(ConfigData->TaskList_25_TaskModel_0.inputRefName,"att_ref_output");
	strcpy(ConfigData->TaskList_25_TaskModel_0.outputDataName,"nom_att_guid_out");
	ConfigData->TaskList_25_TaskModel_0.outputMsgID = 0;
	ConfigData->TaskList_25_TaskModel_0.sigma_BcB = None;
	ConfigData->TaskList_25_TaskModel_0.sigma_R0R[0] = 0.0;
	ConfigData->TaskList_25_TaskModel_0.sigma_R0R[1] = 0.0;
	ConfigData->TaskList_25_TaskModel_0.sigma_R0R[2] = 0.0;
	ConfigData->TaskList_25_TaskModel_1.GsMatrix[0] = 0.0;
	ConfigData->TaskList_25_TaskModel_1.GsMatrix[1] = 0.0;
	ConfigData->TaskList_25_TaskModel_1.GsMatrix[2] = 0.0;
	ConfigData->TaskList_25_TaskModel_1.JsList[0] = 0.0;
	ConfigData->TaskList_25_TaskModel_1.JsList[1] = 0.0;
	ConfigData->TaskList_25_TaskModel_1.JsList[2] = 0.0;
	ConfigData->TaskList_25_TaskModel_1.K = 1.0;
	ConfigData->TaskList_25_TaskModel_1.Ki = -1.0;
	ConfigData->TaskList_25_TaskModel_1.P = 3.0;
	ConfigData->TaskList_25_TaskModel_1.controlOut.torqueRequestBody[0] = 0.0;
	ConfigData->TaskList_25_TaskModel_1.controlOut.torqueRequestBody[1] = 0.0;
	ConfigData->TaskList_25_TaskModel_1.controlOut.torqueRequestBody[2] = 0.0;
	ConfigData->TaskList_25_TaskModel_1.domega0[0] = 0.0;
	ConfigData->TaskList_25_TaskModel_1.domega0[1] = 0.0;
	ConfigData->TaskList_25_TaskModel_1.domega0[2] = 0.0;
	ConfigData->TaskList_25_TaskModel_1.inputGuidID = 0;
	strcpy(ConfigData->TaskList_25_TaskModel_1.inputGuidName,"nom_att_guid_out");
	ConfigData->TaskList_25_TaskModel_1.inputRWConfID = 0;
	strcpy(ConfigData->TaskList_25_TaskModel_1.inputRWConfigData,"rwa_config_data");
	ConfigData->TaskList_25_TaskModel_1.inputRWSpeedsID = 0;
	strcpy(ConfigData->TaskList_25_TaskModel_1.inputRWSpeedsName,"reactionwheel_output_states");
	ConfigData->TaskList_25_TaskModel_1.inputVehicleConfigDataID = 0;
	strcpy(ConfigData->TaskList_25_TaskModel_1.inputVehicleConfigDataName,"adcs_config_data");
	ConfigData->TaskList_25_TaskModel_1.int_sigma[0] = 0.0;
	ConfigData->TaskList_25_TaskModel_1.int_sigma[1] = 0.0;
	ConfigData->TaskList_25_TaskModel_1.int_sigma[2] = 0.0;
	ConfigData->TaskList_25_TaskModel_1.integralLimit = 0.0;
	ConfigData->TaskList_25_TaskModel_1.numRWAs = 4;
	strcpy(ConfigData->TaskList_25_TaskModel_1.outputDataName,"controlTorqueRaw");
	ConfigData->TaskList_25_TaskModel_1.outputMsgID = 0;
	ConfigData->TaskList_25_TaskModel_1.priorTime = 0;
	ConfigData->TaskList_25_TaskModel_1.z[0] = 0.0;
	ConfigData->TaskList_25_TaskModel_1.z[1] = 0.0;
	ConfigData->TaskList_25_TaskModel_1.z[2] = 0.0;
	strcpy(ConfigData->TaskList_25_TaskModel_2.inputControlName,"controlTorqueRaw");
	ConfigData->TaskList_25_TaskModel_2.inputMsgID = 0;
	ConfigData->TaskList_25_TaskModel_2.numThrGroups = 1;
	ConfigData->TaskList_25_TaskModel_2.thrGroups.cmdRequests.effectorRequest[0] = 0.0;
	ConfigData->TaskList_25_TaskModel_2.thrGroups.cmdRequests.effectorRequest[1] = 0.0;
	ConfigData->TaskList_25_TaskModel_2.thrGroups.cmdRequests.effectorRequest[2] = 0.0;
	ConfigData->TaskList_25_TaskModel_2.thrGroups.maxNumCmds = 4;
	ConfigData->TaskList_25_TaskModel_2.thrGroups.minThrustRequest = -10.0;
	ConfigData->TaskList_25_TaskModel_2.thrGroups.nomThrustOn = 0.0;
	ConfigData->TaskList_25_TaskModel_2.thrGroups.numEffectors = 4;
	strcpy(ConfigData->TaskList_25_TaskModel_2.thrGroups.outputDataName,"reactionwheel_cmds_raw");
	ConfigData->TaskList_25_TaskModel_2.thrGroups.outputMsgID = 0;
	ConfigData->TaskList_25_TaskModel_2.thrGroups.thrOnMap[0] = 0.5;
	ConfigData->TaskList_25_TaskModel_2.thrGroups.thrOnMap[1] = 0.5;
	ConfigData->TaskList_25_TaskModel_2.thrGroups.thrOnMap[2] = 0.707106781187;
	ConfigData->TaskList_25_TaskModel_3.GsInverse[0] = 0.0;
	ConfigData->TaskList_25_TaskModel_3.GsInverse[1] = 0.0;
	ConfigData->TaskList_25_TaskModel_3.GsInverse[2] = 0.0;
	ConfigData->TaskList_25_TaskModel_3.OmegaGain = 0.002;
	ConfigData->TaskList_25_TaskModel_3.inputRWCmdsID = 0;
	strcpy(ConfigData->TaskList_25_TaskModel_3.inputRWCommands,"reactionwheel_cmds_raw");
	ConfigData->TaskList_25_TaskModel_3.inputRWConfID = 0;
	strcpy(ConfigData->TaskList_25_TaskModel_3.inputRWConfigData,"rwa_config_data");
	strcpy(ConfigData->TaskList_25_TaskModel_3.inputRWSpeeds,"reactionwheel_output_states");
	ConfigData->TaskList_25_TaskModel_3.inputSpeedsID = 0;
	ConfigData->TaskList_25_TaskModel_3.numWheels = 4;
	strcpy(ConfigData->TaskList_25_TaskModel_3.outputControlName,"reactionwheel_cmds");
	ConfigData->TaskList_25_TaskModel_3.outputMsgID = 0;
	ConfigData->inertial3DSpin.attRefOut.domega_RN_N[0] = 0.0;
	ConfigData->inertial3DSpin.attRefOut.domega_RN_N[1] = 0.0;
	ConfigData->inertial3DSpin.attRefOut.domega_RN_N[2] = 0.0;
	ConfigData->inertial3DSpin.attRefOut.omega_RN_N[0] = 0.0;
	ConfigData->inertial3DSpin.attRefOut.omega_RN_N[1] = 0.0;
	ConfigData->inertial3DSpin.attRefOut.omega_RN_N[2] = 0.0;
	ConfigData->inertial3DSpin.attRefOut.sigma_RN[0] = 0.0;
	ConfigData->inertial3DSpin.attRefOut.sigma_RN[1] = 0.0;
	ConfigData->inertial3DSpin.attRefOut.sigma_RN[2] = 0.0;
	ConfigData->inertial3DSpin.dt = 0.0;
	ConfigData->inertial3DSpin.inputRefID = 0;
	strcpy(ConfigData->inertial3DSpin.inputRefName,"att_ref_output_stage1");
	ConfigData->inertial3DSpin.omega_RN_N[0] = 0.00349065850399;
	ConfigData->inertial3DSpin.omega_RN_N[1] = 0.00349065850399;
	ConfigData->inertial3DSpin.omega_RN_N[2] = 0.00698131700798;
	strcpy(ConfigData->inertial3DSpin.outputDataName,"att_ref_output");
	ConfigData->inertial3DSpin.outputMsgID = 0;
	ConfigData->inertial3DSpin.priorCmdSigma_RN[0] = 0.0;
	ConfigData->inertial3DSpin.priorCmdSigma_RN[1] = 0.0;
	ConfigData->inertial3DSpin.priorCmdSigma_RN[2] = 0.0;
	ConfigData->inertial3DSpin.priorTime = 0;
	ConfigData->inertial3DSpin.sigma_RN[0] = 0.0;
	ConfigData->inertial3DSpin.sigma_RN[1] = 0.0;
	ConfigData->inertial3DSpin.sigma_RN[2] = 0.0;
	ConfigData->attTrackingError.attGuidOut.domega_RN_B[0] = 0.0;
	ConfigData->attTrackingError.attGuidOut.domega_RN_B[1] = 0.0;
	ConfigData->attTrackingError.attGuidOut.domega_RN_B[2] = 0.0;
	ConfigData->attTrackingError.attGuidOut.omega_BR_B[0] = 0.0;
	ConfigData->attTrackingError.attGuidOut.omega_BR_B[1] = 0.0;
	ConfigData->attTrackingError.attGuidOut.omega_BR_B[2] = 0.0;
	ConfigData->attTrackingError.attGuidOut.omega_RN_B[0] = 0.0;
	ConfigData->attTrackingError.attGuidOut.omega_RN_B[1] = 0.0;
	ConfigData->attTrackingError.attGuidOut.omega_RN_B[2] = 0.0;
	ConfigData->attTrackingError.attGuidOut.sigma_BR[0] = 0.0;
	ConfigData->attTrackingError.attGuidOut.sigma_BR[1] = 0.0;
	ConfigData->attTrackingError.attGuidOut.sigma_BR[2] = 0.0;
	ConfigData->attTrackingError.inputNavID = 0;
	strcpy(ConfigData->attTrackingError.inputNavName,"simple_nav_output");
	ConfigData->attTrackingError.inputRefID = 0;
	strcpy(ConfigData->attTrackingError.inputRefName,"att_ref_output");
	strcpy(ConfigData->attTrackingError.outputDataName,"nom_att_guid_out");
	ConfigData->attTrackingError.outputMsgID = 0;
	ConfigData->attTrackingError.sigma_BcB = None;
	ConfigData->attTrackingError.sigma_R0R[0] = 0.0;
	ConfigData->attTrackingError.sigma_R0R[1] = 0.0;
	ConfigData->attTrackingError.sigma_R0R[2] = 0.0;
	ConfigData->PRV_SteeringRWA.GsMatrix[0] = 0.0;
	ConfigData->PRV_SteeringRWA.GsMatrix[1] = 0.0;
	ConfigData->PRV_SteeringRWA.GsMatrix[2] = 0.0;
	ConfigData->PRV_SteeringRWA.JsList[0] = 0.0;
	ConfigData->PRV_SteeringRWA.JsList[1] = 0.0;
	ConfigData->PRV_SteeringRWA.JsList[2] = 0.0;
	ConfigData->PRV_SteeringRWA.K1 = 0.3;
	ConfigData->PRV_SteeringRWA.K3 = 1.0;
	ConfigData->PRV_SteeringRWA.Ki = -1.0;
	ConfigData->PRV_SteeringRWA.P = 150.0;
	ConfigData->PRV_SteeringRWA.controlOut.torqueRequestBody[0] = 0.0;
	ConfigData->PRV_SteeringRWA.controlOut.torqueRequestBody[1] = 0.0;
	ConfigData->PRV_SteeringRWA.controlOut.torqueRequestBody[2] = 0.0;
	ConfigData->PRV_SteeringRWA.inputGuidID = 0;
	strcpy(ConfigData->PRV_SteeringRWA.inputGuidName,"nom_att_guid_out");
	ConfigData->PRV_SteeringRWA.inputRWConfID = 0;
	strcpy(ConfigData->PRV_SteeringRWA.inputRWConfigData,"rwa_config_data");
	ConfigData->PRV_SteeringRWA.inputRWSpeedsID = 0;
	strcpy(ConfigData->PRV_SteeringRWA.inputRWSpeedsName,"reactionwheel_output_states");
	ConfigData->PRV_SteeringRWA.inputVehicleConfigDataID = 0;
	strcpy(ConfigData->PRV_SteeringRWA.inputVehicleConfigDataName,"adcs_config_data");
	ConfigData->PRV_SteeringRWA.integralLimit = 0.0;
	ConfigData->PRV_SteeringRWA.numRWAs = 0;
	ConfigData->PRV_SteeringRWA.omega_max = 0.0261799387799;
	strcpy(ConfigData->PRV_SteeringRWA.outputDataName,"controlTorqueRaw");
	ConfigData->PRV_SteeringRWA.outputMsgID = 0;
	ConfigData->PRV_SteeringRWA.priorTime = 0;
	ConfigData->PRV_SteeringRWA.z[0] = 0.0;
	ConfigData->PRV_SteeringRWA.z[1] = 0.0;
	ConfigData->PRV_SteeringRWA.z[2] = 0.0;
	strcpy(ConfigData->TaskList_26_TaskModel_2.inputControlName,"controlTorqueRaw");
	ConfigData->TaskList_26_TaskModel_2.inputMsgID = 0;
	ConfigData->TaskList_26_TaskModel_2.numThrGroups = 1;
	ConfigData->TaskList_26_TaskModel_2.thrGroups.cmdRequests.effectorRequest[0] = 0.0;
	ConfigData->TaskList_26_TaskModel_2.thrGroups.cmdRequests.effectorRequest[1] = 0.0;
	ConfigData->TaskList_26_TaskModel_2.thrGroups.cmdRequests.effectorRequest[2] = 0.0;
	ConfigData->TaskList_26_TaskModel_2.thrGroups.maxNumCmds = 4;
	ConfigData->TaskList_26_TaskModel_2.thrGroups.minThrustRequest = -10.0;
	ConfigData->TaskList_26_TaskModel_2.thrGroups.nomThrustOn = 0.0;
	ConfigData->TaskList_26_TaskModel_2.thrGroups.numEffectors = 4;
	strcpy(ConfigData->TaskList_26_TaskModel_2.thrGroups.outputDataName,"reactionwheel_cmds_raw");
	ConfigData->TaskList_26_TaskModel_2.thrGroups.outputMsgID = 0;
	ConfigData->TaskList_26_TaskModel_2.thrGroups.thrOnMap[0] = 0.5;
	ConfigData->TaskList_26_TaskModel_2.thrGroups.thrOnMap[1] = 0.5;
	ConfigData->TaskList_26_TaskModel_2.thrGroups.thrOnMap[2] = 0.707106781187;
	ConfigData->TaskList_26_TaskModel_3.GsInverse[0] = 0.0;
	ConfigData->TaskList_26_TaskModel_3.GsInverse[1] = 0.0;
	ConfigData->TaskList_26_TaskModel_3.GsInverse[2] = 0.0;
	ConfigData->TaskList_26_TaskModel_3.OmegaGain = 0.002;
	ConfigData->TaskList_26_TaskModel_3.inputRWCmdsID = 0;
	strcpy(ConfigData->TaskList_26_TaskModel_3.inputRWCommands,"reactionwheel_cmds_raw");
	ConfigData->TaskList_26_TaskModel_3.inputRWConfID = 0;
	strcpy(ConfigData->TaskList_26_TaskModel_3.inputRWConfigData,"rwa_config_data");
	strcpy(ConfigData->TaskList_26_TaskModel_3.inputRWSpeeds,"reactionwheel_output_states");
	ConfigData->TaskList_26_TaskModel_3.inputSpeedsID = 0;
	ConfigData->TaskList_26_TaskModel_3.numWheels = 4;
	strcpy(ConfigData->TaskList_26_TaskModel_3.outputControlName,"reactionwheel_cmds");
	ConfigData->TaskList_26_TaskModel_3.outputMsgID = 0;
}