/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) satellite_full_cost_ext_cost_0_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {10, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};
static const casadi_int casadi_s5[3] = {20, 1, 1};

static const casadi_real casadi_c0[12] = 
  {100., 100., 100., 1., 1., 1., 1., 1.,
  1., 1., 1., 1.};
static const casadi_real casadi_c1[144] = 
  {1000., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 1000., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 1000., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 10.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 10., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 10., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 40., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 40., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  40., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 50., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 50., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 50.};
static const casadi_real casadi_c2[64] = 
  {10., 0., 0., 0., 0., 0., 0., 0.,
  0., 10., 0., 0., 0., 0., 0., 0.,
  0., 0., 10., 0., 0., 0., 0., 0.,
  0., 0., 0., 10., 0., 0., 0., 0.,
  0., 0., 0., 0., 10., 0., 0., 0.,
  0., 0., 0., 0., 0., 10., 0., 0.,
  0., 0., 0., 0., 0., 0., 10., 0.,
  0., 0., 0., 0., 0., 0., 0., 10.};

static const casadi_real casadi_zeros[12] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0.};

/* satellite_full_cost_ext_cost_0_fun_jac:(i0[12],i1[8],i2[0],i3[10])->(o0,o1[20]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+2, *w02=w+14, *w03=w+26, *w04=w+29, *w05=w+35, *w06=w+38, *w07=w+41, *w09=w+56, *w11=w+212, w12;
  casadi_real *w13=w+225, *w17=w+313, *w18=w+321, *w19=w+385;
  const casadi_real *cr, *cs, *ct, *wr02, *wr03, *wr05, *wr06, *wr07, *wr08, *wr10, *wr14, *wr15;
  const casadi_real *wr16;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x12) */
  casadi_clear(w01, 12);
  /* #2: @2 = input[0][0] */
  wr02 = arg[0] ? arg[0] : casadi_zeros;
  /* #3: @3 = @2[:3] */
  wr03 = wr02+0;
  /* #4: @4 = input[3][0] */
  casadi_copy(arg[3], 6, w04);
  /* #5: @5 = @4[:3] */
  for (rr=w05, cs=w04+0; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #6: @3 = (@3-@5) */
  for (i=0, rr=w03, cr=wr03, cs=w05; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #7: @5 = @2[3:6] */
  wr05 = wr02+3;
  /* #8: @6 = @2[6:9] */
  wr06 = wr02+6;
  /* #9: @7 = @2[9:12] */
  wr07 = wr02+9;
  /* #10: @2 = vertcat(@3, @5, @6, @7) */
  rr=w02;
  for (i=0, cs=w03; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=wr05; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=wr06; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=wr07; i<3; ++i) *rr++ = *cs++;
  /* #11: @8 = [100, 100, 100, 1, 1, 1, 1, 1, 1, 1, 1, 1] */
  wr08 = casadi_c0;
  /* #12: @2 = (@2/@8) */
  for (i=0, rr=w02, cs=wr08; i<12; ++i) (*rr++) /= (*cs++);
  /* #13: @9 = @2' */
  casadi_copy(w02, 12, w09);
  /* #14: @10 = 
  [[1000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 40, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 40, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0, 40, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0, 0, 50, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 50, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 50]] */
  wr10 = casadi_c1;
  /* #15: @11 = mac(@9,@10,@1) */
  casadi_copy(w01, 12, w11);
  for (i=0, rr=w11; i<12; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w09+j, ct=wr10+i*12; k<12; ++k) *rr += cs[k*1]**ct++;
  /* #16: @12 = mac(@11,@2,@0) */
  casadi_copy((&w00), 1, (&w12));
  for (i=0, rr=(&w12); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w11+j, ct=w02+i*12; k<12; ++k) *rr += cs[k*1]**ct++;
  /* #17: @13 = zeros(1x8) */
  casadi_clear(w13, 8);
  /* #18: @14 = input[1][0] */
  wr14 = arg[1] ? arg[1] : casadi_zeros;
  /* #19: @15 = @14' */
  wr15 = wr14;
  /* #20: @16 = 
  [[10, 0, 0, 0, 0, 0, 0, 0], 
   [0, 10, 0, 0, 0, 0, 0, 0], 
   [0, 0, 10, 0, 0, 0, 0, 0], 
   [0, 0, 0, 10, 0, 0, 0, 0], 
   [0, 0, 0, 0, 10, 0, 0, 0], 
   [0, 0, 0, 0, 0, 10, 0, 0], 
   [0, 0, 0, 0, 0, 0, 10, 0], 
   [0, 0, 0, 0, 0, 0, 0, 10]] */
  wr16 = casadi_c2;
  /* #21: @17 = mac(@15,@16,@13) */
  casadi_copy(w13, 8, w17);
  for (i=0, rr=w17; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=wr15+j, ct=wr16+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #22: @0 = mac(@17,@14,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w17+j, ct=wr14+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #23: @12 = (@12+@0) */
  w12 += w00;
  /* #24: output[0][0] = @12 */
  if (res[0]) res[0][0] = w12;
  /* #25: @17 = @17' */
  /* #26: @18 = @16' */
  for (i=0, rr=w18, cs=wr16; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #27: @13 = mac(@15,@18,@13) */
  for (i=0, rr=w13; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=wr15+j, ct=w18+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #28: @13 = @13' */
  /* #29: @17 = (@17+@13) */
  for (i=0, rr=w17, cs=w13; i<8; ++i) (*rr++) += (*cs++);
  /* #30: output[1][0] = @17 */
  casadi_copy(w17, 8, res[1]);
  /* #31: @2 = zeros(12x1) */
  casadi_clear(w02, 12);
  /* #32: @11 = @11' */
  /* #33: @19 = @10' */
  for (i=0, rr=w19, cs=wr10; i<12; ++i) for (j=0; j<12; ++j) rr[i+j*12] = *cs++;
  /* #34: @1 = mac(@9,@19,@1) */
  for (i=0, rr=w01; i<12; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w09+j, ct=w19+i*12; k<12; ++k) *rr += cs[k*1]**ct++;
  /* #35: @1 = @1' */
  /* #36: @11 = (@11+@1) */
  for (i=0, rr=w11, cs=w01; i<12; ++i) (*rr++) += (*cs++);
  /* #37: @11 = (@11/@8) */
  for (i=0, rr=w11, cs=wr08; i<12; ++i) (*rr++) /= (*cs++);
  /* #38: {@3, @5, @6, @7} = vertsplit(@11) */
  casadi_copy(w11, 3, w03);
  casadi_copy(w11+3, 3, w05);
  casadi_copy(w11+6, 3, w06);
  casadi_copy(w11+9, 3, w07);
  /* #39: (@2[9:12] += @7) */
  for (rr=w02+9, cs=w07; rr!=w02+12; rr+=1) *rr += *cs++;
  /* #40: (@2[6:9] += @6) */
  for (rr=w02+6, cs=w06; rr!=w02+9; rr+=1) *rr += *cs++;
  /* #41: (@2[3:6] += @5) */
  for (rr=w02+3, cs=w05; rr!=w02+6; rr+=1) *rr += *cs++;
  /* #42: (@2[:3] += @3) */
  for (rr=w02+0, cs=w03; rr!=w02+3; rr+=1) *rr += *cs++;
  /* #43: output[1][1] = @2 */
  if (res[1]) casadi_copy(w02, 12, res[1]+8);
  return 0;
}

CASADI_SYMBOL_EXPORT int satellite_full_cost_ext_cost_0_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int satellite_full_cost_ext_cost_0_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int satellite_full_cost_ext_cost_0_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void satellite_full_cost_ext_cost_0_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int satellite_full_cost_ext_cost_0_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void satellite_full_cost_ext_cost_0_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void satellite_full_cost_ext_cost_0_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void satellite_full_cost_ext_cost_0_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int satellite_full_cost_ext_cost_0_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int satellite_full_cost_ext_cost_0_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real satellite_full_cost_ext_cost_0_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* satellite_full_cost_ext_cost_0_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* satellite_full_cost_ext_cost_0_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* satellite_full_cost_ext_cost_0_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* satellite_full_cost_ext_cost_0_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int satellite_full_cost_ext_cost_0_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 529;
  return 0;
}

CASADI_SYMBOL_EXPORT int satellite_full_cost_ext_cost_0_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 6*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 529*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
