/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) satellite_full_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s26 CASADI_PREFIX(s26)
#define casadi_s27 CASADI_PREFIX(s27)
#define casadi_s28 CASADI_PREFIX(s28)
#define casadi_s29 CASADI_PREFIX(s29)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s30 CASADI_PREFIX(s30)
#define casadi_s31 CASADI_PREFIX(s31)
#define casadi_s32 CASADI_PREFIX(s32)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

static const casadi_int casadi_s0[5] = {12, 1, 0, 1, 0};
static const casadi_int casadi_s1[27] = 
  {1, 12, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0};
static const casadi_int casadi_s2[159] = 
  {12, 12, 0, 12, 24, 36, 48, 60,
  72, 84, 96, 108, 120, 132, 144, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s3[16] = 
  {1, 12, 0, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 0};
static const casadi_int casadi_s4[5] = {12, 1, 0, 1, 1};
static const casadi_int casadi_s5[16] = 
  {1, 12, 0, 0, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 0};
static const casadi_int casadi_s6[5] = {12, 1, 0, 1, 2};
static const casadi_int casadi_s7[16] = 
  {1, 12, 0, 0, 0, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 0};
static const casadi_int casadi_s8[5] = {12, 1, 0, 1, 3};
static const casadi_int casadi_s9[16] = 
  {1, 12, 0, 0, 0, 0, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 0};
static const casadi_int casadi_s10[5] = {12, 1, 0, 1, 4};
static const casadi_int casadi_s11[16] = 
  {1, 12, 0, 0, 0, 0, 0, 1,
  1, 1, 1, 1, 1, 1, 1, 0};
static const casadi_int casadi_s12[5] = {12, 1, 0, 1, 5};
static const casadi_int casadi_s13[16] = 
  {1, 12, 0, 0, 0, 0, 0, 0,
  1, 1, 1, 1, 1, 1, 1, 0};
static const casadi_int casadi_s14[5] = {12, 1, 0, 1, 6};
static const casadi_int casadi_s15[16] = 
  {1, 12, 0, 0, 0, 0, 0, 0,
  0, 1, 1, 1, 1, 1, 1, 0};
static const casadi_int casadi_s16[5] = {12, 1, 0, 1, 7};
static const casadi_int casadi_s17[16] = 
  {1, 12, 0, 0, 0, 0, 0, 0,
  0, 0, 1, 1, 1, 1, 1, 0};
static const casadi_int casadi_s18[5] = {12, 1, 0, 1, 8};
static const casadi_int casadi_s19[16] = 
  {1, 12, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s20[5] = {12, 1, 0, 1, 9};
static const casadi_int casadi_s21[16] = 
  {1, 12, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s22[5] = {12, 1, 0, 1, 10};
static const casadi_int casadi_s23[16] = 
  {1, 12, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s24[5] = {12, 1, 0, 1, 11};
static const casadi_int casadi_s25[16] = 
  {1, 12, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s26[3] = {12, 1, 1};
static const casadi_int casadi_s27[3] = {0, 1, 1};
static const casadi_int casadi_s28[3] = {10, 1, 1};
static const casadi_int casadi_s29[3] = {1, 1, 1};
static const casadi_int casadi_s30[3] = {12, 12, 1};
static const casadi_int casadi_s31[3] = {0, 0, 1};
static const casadi_int casadi_s32[3] = {0, 12, 1};

static const casadi_real casadi_c0[12] = 
  {100., 100., 100., 1., 1., 1., 1., 1.,
  1., 1., 1., 1.};
static const casadi_real casadi_c1[144] = 
  {10000., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 10000., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 10000., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 100.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 100., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 100., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 400., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 400., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  400., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 500., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 500., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 500.};

static const casadi_real casadi_zeros[12] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0.};

/* satellite_full_cost_ext_cost_e_fun_jac_hess:(i0[12],i1[0],i2[0],i3[10])->(o0,o1[12],o2[12x12],o3[],o4[0x12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+2, *w02=w+14, *w03=w+26, *w04=w+29, *w05=w+35, *w06=w+38, *w07=w+41, *w09=w+56, *w11=w+212, *w12=w+224;
  casadi_real *w13=w+368, *w14=w+380, w15, w17, w18, w19;
  const casadi_real *cr, *cs, *ct, *wr02, *wr03, *wr05, *wr06, *wr07, *wr08, *wr10;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x12) */
  casadi_clear(w01, 12);
  /* #2: @2 = input[0][0] */
  wr02 = arg[0] ? arg[0] : casadi_zeros;
  /* #3: @3 = @2[:3] */
  wr03 = wr02+0;
  /* #4: @4 = input[3][0] */
  casadi_copy(arg[3], 6, w04);
  /* #5: @5 = @4[:3] */
  for (rr=w05, cs=w04+0; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #6: @3 = (@3-@5) */
  for (i=0, rr=w03, cr=wr03, cs=w05; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #7: @5 = @2[3:6] */
  wr05 = wr02+3;
  /* #8: @6 = @2[6:9] */
  wr06 = wr02+6;
  /* #9: @7 = @2[9:12] */
  wr07 = wr02+9;
  /* #10: @2 = vertcat(@3, @5, @6, @7) */
  rr=w02;
  for (i=0, cs=w03; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=wr05; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=wr06; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=wr07; i<3; ++i) *rr++ = *cs++;
  /* #11: @8 = [100, 100, 100, 1, 1, 1, 1, 1, 1, 1, 1, 1] */
  wr08 = casadi_c0;
  /* #12: @2 = (@2/@8) */
  for (i=0, rr=w02, cs=wr08; i<12; ++i) (*rr++) /= (*cs++);
  /* #13: @9 = @2' */
  casadi_copy(w02, 12, w09);
  /* #14: @10 = 
  [[10000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 10000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 10000, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 400, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 400, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0, 400, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0, 0, 500, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 500, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 500]] */
  wr10 = casadi_c1;
  /* #15: @11 = mac(@9,@10,@1) */
  casadi_copy(w01, 12, w11);
  for (i=0, rr=w11; i<12; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w09+j, ct=wr10+i*12; k<12; ++k) *rr += cs[k*1]**ct++;
  /* #16: @0 = mac(@11,@2,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w11+j, ct=w02+i*12; k<12; ++k) *rr += cs[k*1]**ct++;
  /* #17: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #18: @2 = zeros(12x1) */
  casadi_clear(w02, 12);
  /* #19: @11 = @11' */
  /* #20: @12 = @10' */
  for (i=0, rr=w12, cs=wr10; i<12; ++i) for (j=0; j<12; ++j) rr[i+j*12] = *cs++;
  /* #21: @13 = mac(@9,@12,@1) */
  casadi_copy(w01, 12, w13);
  for (i=0, rr=w13; i<12; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w09+j, ct=w12+i*12; k<12; ++k) *rr += cs[k*1]**ct++;
  /* #22: @13 = @13' */
  /* #23: @11 = (@11+@13) */
  for (i=0, rr=w11, cs=w13; i<12; ++i) (*rr++) += (*cs++);
  /* #24: @11 = (@11/@8) */
  for (i=0, rr=w11, cs=wr08; i<12; ++i) (*rr++) /= (*cs++);
  /* #25: {@3, @5, @6, @7} = vertsplit(@11) */
  casadi_copy(w11, 3, w03);
  casadi_copy(w11+3, 3, w05);
  casadi_copy(w11+6, 3, w06);
  casadi_copy(w11+9, 3, w07);
  /* #26: @11 = @2; (@11[9:12] += @7) */
  casadi_copy(w02, 12, w11);
  for (rr=w11+9, cs=w07; rr!=w11+12; rr+=1) *rr += *cs++;
  /* #27: (@11[6:9] += @6) */
  for (rr=w11+6, cs=w06; rr!=w11+9; rr+=1) *rr += *cs++;
  /* #28: (@11[3:6] += @5) */
  for (rr=w11+3, cs=w05; rr!=w11+6; rr+=1) *rr += *cs++;
  /* #29: (@11[:3] += @3) */
  for (rr=w11+0, cs=w03; rr!=w11+3; rr+=1) *rr += *cs++;
  /* #30: output[1][0] = @11 */
  casadi_copy(w11, 12, res[1]);
  /* #31: @14 = zeros(12x12) */
  casadi_clear(w14, 144);
  /* #32: @11 = (1./@8) */
  for (i=0, rr=w11, cs=wr08; i<12; ++i) *rr++ = (1./ *cs++ );
  /* #33: @0 = project(@11) */
  casadi_sparsify(w11, (&w00), casadi_s0, 0);
  /* #34: @15 = ones(3x1,1nz) */
  w15 = 1.;
  /* #35: @16 = zeros(3x1,0nz) */
  /* #36: @17 = vertcat(@15, @16, @16, @16) */
  rr=(&w17);
  *rr++ = w15;
  /* #37: @0 = (@0*@17) */
  w00 *= w17;
  /* #38: @0 = @0' */
  /* #39: @13 = mac(@0,@10,@1) */
  casadi_copy(w01, 12, w13);
  casadi_mtimes((&w00), casadi_s3, wr10, casadi_s2, w13, casadi_s1, w, 0);
  /* #40: @13 = @13' */
  /* #41: @9 = mac(@0,@12,@1) */
  casadi_copy(w01, 12, w09);
  casadi_mtimes((&w00), casadi_s3, w12, casadi_s2, w09, casadi_s1, w, 0);
  /* #42: @9 = @9' */
  /* #43: @13 = (@13+@9) */
  for (i=0, rr=w13, cs=w09; i<12; ++i) (*rr++) += (*cs++);
  /* #44: @13 = (@13/@8) */
  for (i=0, rr=w13, cs=wr08; i<12; ++i) (*rr++) /= (*cs++);
  /* #45: {@3, @5, @6, @7} = vertsplit(@13) */
  casadi_copy(w13, 3, w03);
  casadi_copy(w13+3, 3, w05);
  casadi_copy(w13+6, 3, w06);
  casadi_copy(w13+9, 3, w07);
  /* #46: @13 = @2; (@13[9:12] += @7) */
  casadi_copy(w02, 12, w13);
  for (rr=w13+9, cs=w07; rr!=w13+12; rr+=1) *rr += *cs++;
  /* #47: (@13[6:9] += @6) */
  for (rr=w13+6, cs=w06; rr!=w13+9; rr+=1) *rr += *cs++;
  /* #48: (@13[3:6] += @5) */
  for (rr=w13+3, cs=w05; rr!=w13+6; rr+=1) *rr += *cs++;
  /* #49: (@13[:3] += @3) */
  for (rr=w13+0, cs=w03; rr!=w13+3; rr+=1) *rr += *cs++;
  /* #50: (@14[:12] = @13) */
  for (rr=w14+0, cs=w13; rr!=w14+12; rr+=1) *rr = *cs++;
  /* #51: (@14[:144:12] = @13) */
  for (rr=w14+0, cs=w13; rr!=w14+144; rr+=12) *rr = *cs++;
  /* #52: @0 = project(@11) */
  casadi_sparsify(w11, (&w00), casadi_s4, 0);
  /* #53: @17 = ones(3x1,1nz) */
  w17 = 1.;
  /* #54: @18 = vertcat(@17, @16, @16, @16) */
  rr=(&w18);
  *rr++ = w17;
  /* #55: @0 = (@0*@18) */
  w00 *= w18;
  /* #56: @0 = @0' */
  /* #57: @13 = mac(@0,@10,@1) */
  casadi_copy(w01, 12, w13);
  casadi_mtimes((&w00), casadi_s5, wr10, casadi_s2, w13, casadi_s1, w, 0);
  /* #58: @13 = @13' */
  /* #59: @9 = mac(@0,@12,@1) */
  casadi_copy(w01, 12, w09);
  casadi_mtimes((&w00), casadi_s5, w12, casadi_s2, w09, casadi_s1, w, 0);
  /* #60: @9 = @9' */
  /* #61: @13 = (@13+@9) */
  for (i=0, rr=w13, cs=w09; i<12; ++i) (*rr++) += (*cs++);
  /* #62: @13 = (@13/@8) */
  for (i=0, rr=w13, cs=wr08; i<12; ++i) (*rr++) /= (*cs++);
  /* #63: {@3, @5, @6, @7} = vertsplit(@13) */
  casadi_copy(w13, 3, w03);
  casadi_copy(w13+3, 3, w05);
  casadi_copy(w13+6, 3, w06);
  casadi_copy(w13+9, 3, w07);
  /* #64: @13 = @2; (@13[9:12] += @7) */
  casadi_copy(w02, 12, w13);
  for (rr=w13+9, cs=w07; rr!=w13+12; rr+=1) *rr += *cs++;
  /* #65: (@13[6:9] += @6) */
  for (rr=w13+6, cs=w06; rr!=w13+9; rr+=1) *rr += *cs++;
  /* #66: (@13[3:6] += @5) */
  for (rr=w13+3, cs=w05; rr!=w13+6; rr+=1) *rr += *cs++;
  /* #67: (@13[:3] += @3) */
  for (rr=w13+0, cs=w03; rr!=w13+3; rr+=1) *rr += *cs++;
  /* #68: (@14[12:24] = @13) */
  for (rr=w14+12, cs=w13; rr!=w14+24; rr+=1) *rr = *cs++;
  /* #69: (@14[1:145:12] = @13) */
  for (rr=w14+1, cs=w13; rr!=w14+145; rr+=12) *rr = *cs++;
  /* #70: @0 = project(@11) */
  casadi_sparsify(w11, (&w00), casadi_s6, 0);
  /* #71: @18 = ones(3x1,1nz) */
  w18 = 1.;
  /* #72: @19 = vertcat(@18, @16, @16, @16) */
  rr=(&w19);
  *rr++ = w18;
  /* #73: @0 = (@0*@19) */
  w00 *= w19;
  /* #74: @0 = @0' */
  /* #75: @13 = mac(@0,@10,@1) */
  casadi_copy(w01, 12, w13);
  casadi_mtimes((&w00), casadi_s7, wr10, casadi_s2, w13, casadi_s1, w, 0);
  /* #76: @13 = @13' */
  /* #77: @9 = mac(@0,@12,@1) */
  casadi_copy(w01, 12, w09);
  casadi_mtimes((&w00), casadi_s7, w12, casadi_s2, w09, casadi_s1, w, 0);
  /* #78: @9 = @9' */
  /* #79: @13 = (@13+@9) */
  for (i=0, rr=w13, cs=w09; i<12; ++i) (*rr++) += (*cs++);
  /* #80: @13 = (@13/@8) */
  for (i=0, rr=w13, cs=wr08; i<12; ++i) (*rr++) /= (*cs++);
  /* #81: {@3, @5, @6, @7} = vertsplit(@13) */
  casadi_copy(w13, 3, w03);
  casadi_copy(w13+3, 3, w05);
  casadi_copy(w13+6, 3, w06);
  casadi_copy(w13+9, 3, w07);
  /* #82: @13 = @2; (@13[9:12] += @7) */
  casadi_copy(w02, 12, w13);
  for (rr=w13+9, cs=w07; rr!=w13+12; rr+=1) *rr += *cs++;
  /* #83: (@13[6:9] += @6) */
  for (rr=w13+6, cs=w06; rr!=w13+9; rr+=1) *rr += *cs++;
  /* #84: (@13[3:6] += @5) */
  for (rr=w13+3, cs=w05; rr!=w13+6; rr+=1) *rr += *cs++;
  /* #85: (@13[:3] += @3) */
  for (rr=w13+0, cs=w03; rr!=w13+3; rr+=1) *rr += *cs++;
  /* #86: (@14[24:36] = @13) */
  for (rr=w14+24, cs=w13; rr!=w14+36; rr+=1) *rr = *cs++;
  /* #87: (@14[2:146:12] = @13) */
  for (rr=w14+2, cs=w13; rr!=w14+146; rr+=12) *rr = *cs++;
  /* #88: @0 = project(@11) */
  casadi_sparsify(w11, (&w00), casadi_s8, 0);
  /* #89: @19 = vertcat(@16, @15, @16, @16) */
  rr=(&w19);
  *rr++ = w15;
  /* #90: @0 = (@0*@19) */
  w00 *= w19;
  /* #91: @0 = @0' */
  /* #92: @13 = mac(@0,@10,@1) */
  casadi_copy(w01, 12, w13);
  casadi_mtimes((&w00), casadi_s9, wr10, casadi_s2, w13, casadi_s1, w, 0);
  /* #93: @13 = @13' */
  /* #94: @9 = mac(@0,@12,@1) */
  casadi_copy(w01, 12, w09);
  casadi_mtimes((&w00), casadi_s9, w12, casadi_s2, w09, casadi_s1, w, 0);
  /* #95: @9 = @9' */
  /* #96: @13 = (@13+@9) */
  for (i=0, rr=w13, cs=w09; i<12; ++i) (*rr++) += (*cs++);
  /* #97: @13 = (@13/@8) */
  for (i=0, rr=w13, cs=wr08; i<12; ++i) (*rr++) /= (*cs++);
  /* #98: {@3, @5, @6, @7} = vertsplit(@13) */
  casadi_copy(w13, 3, w03);
  casadi_copy(w13+3, 3, w05);
  casadi_copy(w13+6, 3, w06);
  casadi_copy(w13+9, 3, w07);
  /* #99: @13 = @2; (@13[9:12] += @7) */
  casadi_copy(w02, 12, w13);
  for (rr=w13+9, cs=w07; rr!=w13+12; rr+=1) *rr += *cs++;
  /* #100: (@13[6:9] += @6) */
  for (rr=w13+6, cs=w06; rr!=w13+9; rr+=1) *rr += *cs++;
  /* #101: (@13[3:6] += @5) */
  for (rr=w13+3, cs=w05; rr!=w13+6; rr+=1) *rr += *cs++;
  /* #102: (@13[:3] += @3) */
  for (rr=w13+0, cs=w03; rr!=w13+3; rr+=1) *rr += *cs++;
  /* #103: (@14[36:48] = @13) */
  for (rr=w14+36, cs=w13; rr!=w14+48; rr+=1) *rr = *cs++;
  /* #104: (@14[3:147:12] = @13) */
  for (rr=w14+3, cs=w13; rr!=w14+147; rr+=12) *rr = *cs++;
  /* #105: @0 = project(@11) */
  casadi_sparsify(w11, (&w00), casadi_s10, 0);
  /* #106: @19 = vertcat(@16, @17, @16, @16) */
  rr=(&w19);
  *rr++ = w17;
  /* #107: @0 = (@0*@19) */
  w00 *= w19;
  /* #108: @0 = @0' */
  /* #109: @13 = mac(@0,@10,@1) */
  casadi_copy(w01, 12, w13);
  casadi_mtimes((&w00), casadi_s11, wr10, casadi_s2, w13, casadi_s1, w, 0);
  /* #110: @13 = @13' */
  /* #111: @9 = mac(@0,@12,@1) */
  casadi_copy(w01, 12, w09);
  casadi_mtimes((&w00), casadi_s11, w12, casadi_s2, w09, casadi_s1, w, 0);
  /* #112: @9 = @9' */
  /* #113: @13 = (@13+@9) */
  for (i=0, rr=w13, cs=w09; i<12; ++i) (*rr++) += (*cs++);
  /* #114: @13 = (@13/@8) */
  for (i=0, rr=w13, cs=wr08; i<12; ++i) (*rr++) /= (*cs++);
  /* #115: {@3, @5, @6, @7} = vertsplit(@13) */
  casadi_copy(w13, 3, w03);
  casadi_copy(w13+3, 3, w05);
  casadi_copy(w13+6, 3, w06);
  casadi_copy(w13+9, 3, w07);
  /* #116: @13 = @2; (@13[9:12] += @7) */
  casadi_copy(w02, 12, w13);
  for (rr=w13+9, cs=w07; rr!=w13+12; rr+=1) *rr += *cs++;
  /* #117: (@13[6:9] += @6) */
  for (rr=w13+6, cs=w06; rr!=w13+9; rr+=1) *rr += *cs++;
  /* #118: (@13[3:6] += @5) */
  for (rr=w13+3, cs=w05; rr!=w13+6; rr+=1) *rr += *cs++;
  /* #119: (@13[:3] += @3) */
  for (rr=w13+0, cs=w03; rr!=w13+3; rr+=1) *rr += *cs++;
  /* #120: (@14[48:60] = @13) */
  for (rr=w14+48, cs=w13; rr!=w14+60; rr+=1) *rr = *cs++;
  /* #121: (@14[4:148:12] = @13) */
  for (rr=w14+4, cs=w13; rr!=w14+148; rr+=12) *rr = *cs++;
  /* #122: @0 = project(@11) */
  casadi_sparsify(w11, (&w00), casadi_s12, 0);
  /* #123: @19 = vertcat(@16, @18, @16, @16) */
  rr=(&w19);
  *rr++ = w18;
  /* #124: @0 = (@0*@19) */
  w00 *= w19;
  /* #125: @0 = @0' */
  /* #126: @13 = mac(@0,@10,@1) */
  casadi_copy(w01, 12, w13);
  casadi_mtimes((&w00), casadi_s13, wr10, casadi_s2, w13, casadi_s1, w, 0);
  /* #127: @13 = @13' */
  /* #128: @9 = mac(@0,@12,@1) */
  casadi_copy(w01, 12, w09);
  casadi_mtimes((&w00), casadi_s13, w12, casadi_s2, w09, casadi_s1, w, 0);
  /* #129: @9 = @9' */
  /* #130: @13 = (@13+@9) */
  for (i=0, rr=w13, cs=w09; i<12; ++i) (*rr++) += (*cs++);
  /* #131: @13 = (@13/@8) */
  for (i=0, rr=w13, cs=wr08; i<12; ++i) (*rr++) /= (*cs++);
  /* #132: {@3, @5, @6, @7} = vertsplit(@13) */
  casadi_copy(w13, 3, w03);
  casadi_copy(w13+3, 3, w05);
  casadi_copy(w13+6, 3, w06);
  casadi_copy(w13+9, 3, w07);
  /* #133: @13 = @2; (@13[9:12] += @7) */
  casadi_copy(w02, 12, w13);
  for (rr=w13+9, cs=w07; rr!=w13+12; rr+=1) *rr += *cs++;
  /* #134: (@13[6:9] += @6) */
  for (rr=w13+6, cs=w06; rr!=w13+9; rr+=1) *rr += *cs++;
  /* #135: (@13[3:6] += @5) */
  for (rr=w13+3, cs=w05; rr!=w13+6; rr+=1) *rr += *cs++;
  /* #136: (@13[:3] += @3) */
  for (rr=w13+0, cs=w03; rr!=w13+3; rr+=1) *rr += *cs++;
  /* #137: (@14[60:72] = @13) */
  for (rr=w14+60, cs=w13; rr!=w14+72; rr+=1) *rr = *cs++;
  /* #138: (@14[5:149:12] = @13) */
  for (rr=w14+5, cs=w13; rr!=w14+149; rr+=12) *rr = *cs++;
  /* #139: @0 = project(@11) */
  casadi_sparsify(w11, (&w00), casadi_s14, 0);
  /* #140: @19 = vertcat(@16, @16, @15, @16) */
  rr=(&w19);
  *rr++ = w15;
  /* #141: @0 = (@0*@19) */
  w00 *= w19;
  /* #142: @0 = @0' */
  /* #143: @13 = mac(@0,@10,@1) */
  casadi_copy(w01, 12, w13);
  casadi_mtimes((&w00), casadi_s15, wr10, casadi_s2, w13, casadi_s1, w, 0);
  /* #144: @13 = @13' */
  /* #145: @9 = mac(@0,@12,@1) */
  casadi_copy(w01, 12, w09);
  casadi_mtimes((&w00), casadi_s15, w12, casadi_s2, w09, casadi_s1, w, 0);
  /* #146: @9 = @9' */
  /* #147: @13 = (@13+@9) */
  for (i=0, rr=w13, cs=w09; i<12; ++i) (*rr++) += (*cs++);
  /* #148: @13 = (@13/@8) */
  for (i=0, rr=w13, cs=wr08; i<12; ++i) (*rr++) /= (*cs++);
  /* #149: {@3, @5, @6, @7} = vertsplit(@13) */
  casadi_copy(w13, 3, w03);
  casadi_copy(w13+3, 3, w05);
  casadi_copy(w13+6, 3, w06);
  casadi_copy(w13+9, 3, w07);
  /* #150: @13 = @2; (@13[9:12] += @7) */
  casadi_copy(w02, 12, w13);
  for (rr=w13+9, cs=w07; rr!=w13+12; rr+=1) *rr += *cs++;
  /* #151: (@13[6:9] += @6) */
  for (rr=w13+6, cs=w06; rr!=w13+9; rr+=1) *rr += *cs++;
  /* #152: (@13[3:6] += @5) */
  for (rr=w13+3, cs=w05; rr!=w13+6; rr+=1) *rr += *cs++;
  /* #153: (@13[:3] += @3) */
  for (rr=w13+0, cs=w03; rr!=w13+3; rr+=1) *rr += *cs++;
  /* #154: (@14[72:84] = @13) */
  for (rr=w14+72, cs=w13; rr!=w14+84; rr+=1) *rr = *cs++;
  /* #155: (@14[6:150:12] = @13) */
  for (rr=w14+6, cs=w13; rr!=w14+150; rr+=12) *rr = *cs++;
  /* #156: @0 = project(@11) */
  casadi_sparsify(w11, (&w00), casadi_s16, 0);
  /* #157: @19 = vertcat(@16, @16, @17, @16) */
  rr=(&w19);
  *rr++ = w17;
  /* #158: @0 = (@0*@19) */
  w00 *= w19;
  /* #159: @0 = @0' */
  /* #160: @13 = mac(@0,@10,@1) */
  casadi_copy(w01, 12, w13);
  casadi_mtimes((&w00), casadi_s17, wr10, casadi_s2, w13, casadi_s1, w, 0);
  /* #161: @13 = @13' */
  /* #162: @9 = mac(@0,@12,@1) */
  casadi_copy(w01, 12, w09);
  casadi_mtimes((&w00), casadi_s17, w12, casadi_s2, w09, casadi_s1, w, 0);
  /* #163: @9 = @9' */
  /* #164: @13 = (@13+@9) */
  for (i=0, rr=w13, cs=w09; i<12; ++i) (*rr++) += (*cs++);
  /* #165: @13 = (@13/@8) */
  for (i=0, rr=w13, cs=wr08; i<12; ++i) (*rr++) /= (*cs++);
  /* #166: {@3, @5, @6, @7} = vertsplit(@13) */
  casadi_copy(w13, 3, w03);
  casadi_copy(w13+3, 3, w05);
  casadi_copy(w13+6, 3, w06);
  casadi_copy(w13+9, 3, w07);
  /* #167: @13 = @2; (@13[9:12] += @7) */
  casadi_copy(w02, 12, w13);
  for (rr=w13+9, cs=w07; rr!=w13+12; rr+=1) *rr += *cs++;
  /* #168: (@13[6:9] += @6) */
  for (rr=w13+6, cs=w06; rr!=w13+9; rr+=1) *rr += *cs++;
  /* #169: (@13[3:6] += @5) */
  for (rr=w13+3, cs=w05; rr!=w13+6; rr+=1) *rr += *cs++;
  /* #170: (@13[:3] += @3) */
  for (rr=w13+0, cs=w03; rr!=w13+3; rr+=1) *rr += *cs++;
  /* #171: (@14[84:96] = @13) */
  for (rr=w14+84, cs=w13; rr!=w14+96; rr+=1) *rr = *cs++;
  /* #172: (@14[7:151:12] = @13) */
  for (rr=w14+7, cs=w13; rr!=w14+151; rr+=12) *rr = *cs++;
  /* #173: @0 = project(@11) */
  casadi_sparsify(w11, (&w00), casadi_s18, 0);
  /* #174: @19 = vertcat(@16, @16, @18, @16) */
  rr=(&w19);
  *rr++ = w18;
  /* #175: @0 = (@0*@19) */
  w00 *= w19;
  /* #176: @0 = @0' */
  /* #177: @13 = mac(@0,@10,@1) */
  casadi_copy(w01, 12, w13);
  casadi_mtimes((&w00), casadi_s19, wr10, casadi_s2, w13, casadi_s1, w, 0);
  /* #178: @13 = @13' */
  /* #179: @9 = mac(@0,@12,@1) */
  casadi_copy(w01, 12, w09);
  casadi_mtimes((&w00), casadi_s19, w12, casadi_s2, w09, casadi_s1, w, 0);
  /* #180: @9 = @9' */
  /* #181: @13 = (@13+@9) */
  for (i=0, rr=w13, cs=w09; i<12; ++i) (*rr++) += (*cs++);
  /* #182: @13 = (@13/@8) */
  for (i=0, rr=w13, cs=wr08; i<12; ++i) (*rr++) /= (*cs++);
  /* #183: {@3, @5, @6, @7} = vertsplit(@13) */
  casadi_copy(w13, 3, w03);
  casadi_copy(w13+3, 3, w05);
  casadi_copy(w13+6, 3, w06);
  casadi_copy(w13+9, 3, w07);
  /* #184: @13 = @2; (@13[9:12] += @7) */
  casadi_copy(w02, 12, w13);
  for (rr=w13+9, cs=w07; rr!=w13+12; rr+=1) *rr += *cs++;
  /* #185: (@13[6:9] += @6) */
  for (rr=w13+6, cs=w06; rr!=w13+9; rr+=1) *rr += *cs++;
  /* #186: (@13[3:6] += @5) */
  for (rr=w13+3, cs=w05; rr!=w13+6; rr+=1) *rr += *cs++;
  /* #187: (@13[:3] += @3) */
  for (rr=w13+0, cs=w03; rr!=w13+3; rr+=1) *rr += *cs++;
  /* #188: (@14[96:108] = @13) */
  for (rr=w14+96, cs=w13; rr!=w14+108; rr+=1) *rr = *cs++;
  /* #189: (@14[8:152:12] = @13) */
  for (rr=w14+8, cs=w13; rr!=w14+152; rr+=12) *rr = *cs++;
  /* #190: @0 = project(@11) */
  casadi_sparsify(w11, (&w00), casadi_s20, 0);
  /* #191: @19 = vertcat(@16, @16, @16, @15) */
  rr=(&w19);
  *rr++ = w15;
  /* #192: @0 = (@0*@19) */
  w00 *= w19;
  /* #193: @0 = @0' */
  /* #194: @13 = mac(@0,@10,@1) */
  casadi_copy(w01, 12, w13);
  casadi_mtimes((&w00), casadi_s21, wr10, casadi_s2, w13, casadi_s1, w, 0);
  /* #195: @13 = @13' */
  /* #196: @9 = mac(@0,@12,@1) */
  casadi_copy(w01, 12, w09);
  casadi_mtimes((&w00), casadi_s21, w12, casadi_s2, w09, casadi_s1, w, 0);
  /* #197: @9 = @9' */
  /* #198: @13 = (@13+@9) */
  for (i=0, rr=w13, cs=w09; i<12; ++i) (*rr++) += (*cs++);
  /* #199: @13 = (@13/@8) */
  for (i=0, rr=w13, cs=wr08; i<12; ++i) (*rr++) /= (*cs++);
  /* #200: {@3, @5, @6, @7} = vertsplit(@13) */
  casadi_copy(w13, 3, w03);
  casadi_copy(w13+3, 3, w05);
  casadi_copy(w13+6, 3, w06);
  casadi_copy(w13+9, 3, w07);
  /* #201: @13 = @2; (@13[9:12] += @7) */
  casadi_copy(w02, 12, w13);
  for (rr=w13+9, cs=w07; rr!=w13+12; rr+=1) *rr += *cs++;
  /* #202: (@13[6:9] += @6) */
  for (rr=w13+6, cs=w06; rr!=w13+9; rr+=1) *rr += *cs++;
  /* #203: (@13[3:6] += @5) */
  for (rr=w13+3, cs=w05; rr!=w13+6; rr+=1) *rr += *cs++;
  /* #204: (@13[:3] += @3) */
  for (rr=w13+0, cs=w03; rr!=w13+3; rr+=1) *rr += *cs++;
  /* #205: (@14[108:120] = @13) */
  for (rr=w14+108, cs=w13; rr!=w14+120; rr+=1) *rr = *cs++;
  /* #206: (@14[9:153:12] = @13) */
  for (rr=w14+9, cs=w13; rr!=w14+153; rr+=12) *rr = *cs++;
  /* #207: @0 = project(@11) */
  casadi_sparsify(w11, (&w00), casadi_s22, 0);
  /* #208: @19 = vertcat(@16, @16, @16, @17) */
  rr=(&w19);
  *rr++ = w17;
  /* #209: @0 = (@0*@19) */
  w00 *= w19;
  /* #210: @0 = @0' */
  /* #211: @13 = mac(@0,@10,@1) */
  casadi_copy(w01, 12, w13);
  casadi_mtimes((&w00), casadi_s23, wr10, casadi_s2, w13, casadi_s1, w, 0);
  /* #212: @13 = @13' */
  /* #213: @9 = mac(@0,@12,@1) */
  casadi_copy(w01, 12, w09);
  casadi_mtimes((&w00), casadi_s23, w12, casadi_s2, w09, casadi_s1, w, 0);
  /* #214: @9 = @9' */
  /* #215: @13 = (@13+@9) */
  for (i=0, rr=w13, cs=w09; i<12; ++i) (*rr++) += (*cs++);
  /* #216: @13 = (@13/@8) */
  for (i=0, rr=w13, cs=wr08; i<12; ++i) (*rr++) /= (*cs++);
  /* #217: {@3, @5, @6, @7} = vertsplit(@13) */
  casadi_copy(w13, 3, w03);
  casadi_copy(w13+3, 3, w05);
  casadi_copy(w13+6, 3, w06);
  casadi_copy(w13+9, 3, w07);
  /* #218: @13 = @2; (@13[9:12] += @7) */
  casadi_copy(w02, 12, w13);
  for (rr=w13+9, cs=w07; rr!=w13+12; rr+=1) *rr += *cs++;
  /* #219: (@13[6:9] += @6) */
  for (rr=w13+6, cs=w06; rr!=w13+9; rr+=1) *rr += *cs++;
  /* #220: (@13[3:6] += @5) */
  for (rr=w13+3, cs=w05; rr!=w13+6; rr+=1) *rr += *cs++;
  /* #221: (@13[:3] += @3) */
  for (rr=w13+0, cs=w03; rr!=w13+3; rr+=1) *rr += *cs++;
  /* #222: (@14[120:132] = @13) */
  for (rr=w14+120, cs=w13; rr!=w14+132; rr+=1) *rr = *cs++;
  /* #223: (@14[10:154:12] = @13) */
  for (rr=w14+10, cs=w13; rr!=w14+154; rr+=12) *rr = *cs++;
  /* #224: @0 = project(@11) */
  casadi_sparsify(w11, (&w00), casadi_s24, 0);
  /* #225: @19 = vertcat(@16, @16, @16, @18) */
  rr=(&w19);
  *rr++ = w18;
  /* #226: @0 = (@0*@19) */
  w00 *= w19;
  /* #227: @0 = @0' */
  /* #228: @11 = mac(@0,@10,@1) */
  casadi_copy(w01, 12, w11);
  casadi_mtimes((&w00), casadi_s25, wr10, casadi_s2, w11, casadi_s1, w, 0);
  /* #229: @11 = @11' */
  /* #230: @1 = mac(@0,@12,@1) */
  casadi_mtimes((&w00), casadi_s25, w12, casadi_s2, w01, casadi_s1, w, 0);
  /* #231: @1 = @1' */
  /* #232: @11 = (@11+@1) */
  for (i=0, rr=w11, cs=w01; i<12; ++i) (*rr++) += (*cs++);
  /* #233: @11 = (@11/@8) */
  for (i=0, rr=w11, cs=wr08; i<12; ++i) (*rr++) /= (*cs++);
  /* #234: {@3, @5, @6, @7} = vertsplit(@11) */
  casadi_copy(w11, 3, w03);
  casadi_copy(w11+3, 3, w05);
  casadi_copy(w11+6, 3, w06);
  casadi_copy(w11+9, 3, w07);
  /* #235: (@2[9:12] += @7) */
  for (rr=w02+9, cs=w07; rr!=w02+12; rr+=1) *rr += *cs++;
  /* #236: (@2[6:9] += @6) */
  for (rr=w02+6, cs=w06; rr!=w02+9; rr+=1) *rr += *cs++;
  /* #237: (@2[3:6] += @5) */
  for (rr=w02+3, cs=w05; rr!=w02+6; rr+=1) *rr += *cs++;
  /* #238: (@2[:3] += @3) */
  for (rr=w02+0, cs=w03; rr!=w02+3; rr+=1) *rr += *cs++;
  /* #239: (@14[132:144] = @2) */
  for (rr=w14+132, cs=w02; rr!=w14+144; rr+=1) *rr = *cs++;
  /* #240: (@14[11:155:12] = @2) */
  for (rr=w14+11, cs=w02; rr!=w14+155; rr+=12) *rr = *cs++;
  /* #241: @12 = @14' */
  for (i=0, rr=w12, cs=w14; i<12; ++i) for (j=0; j<12; ++j) rr[i+j*12] = *cs++;
  /* #242: output[2][0] = @12 */
  casadi_copy(w12, 144, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int satellite_full_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int satellite_full_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int satellite_full_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void satellite_full_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int satellite_full_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void satellite_full_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void satellite_full_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void satellite_full_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int satellite_full_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int satellite_full_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real satellite_full_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* satellite_full_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* satellite_full_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* satellite_full_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s26;
    case 1: return casadi_s27;
    case 2: return casadi_s27;
    case 3: return casadi_s28;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* satellite_full_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s29;
    case 1: return casadi_s26;
    case 2: return casadi_s30;
    case 3: return casadi_s31;
    case 4: return casadi_s32;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int satellite_full_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 528;
  return 0;
}

CASADI_SYMBOL_EXPORT int satellite_full_cost_ext_cost_e_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 9*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 528*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
