/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) satellite_full_cost_ext_cost_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {10, 1, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};

static const casadi_real casadi_c0[12] = 
  {100., 100., 100., 1., 1., 1., 1., 1.,
  1., 1., 1., 1.};
static const casadi_real casadi_c1[144] = 
  {10000., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 10000., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 10000., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 100.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 100., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 100., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 400., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 400., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  400., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 500., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 500., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 500.};

static const casadi_real casadi_zeros[12] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0.};

/* satellite_full_cost_ext_cost_e_fun:(i0[12],i1[0],i2[0],i3[10])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w0, *w1=w+2, *w2=w+14, *w3=w+26, *w4=w+29, *w5=w+35, *w8=w+44;
  const casadi_real *cr, *cs, *ct, *wr2, *wr3, *wr5, *wr6, *wr7, *wr8, *wr9;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x12) */
  casadi_clear(w1, 12);
  /* #2: @2 = input[0][0] */
  wr2 = arg[0] ? arg[0] : casadi_zeros;
  /* #3: @3 = @2[:3] */
  wr3 = wr2+0;
  /* #4: @4 = input[3][0] */
  casadi_copy(arg[3], 6, w4);
  /* #5: @5 = @4[:3] */
  for (rr=w5, cs=w4+0; cs!=w4+3; cs+=1) *rr++ = *cs;
  /* #6: @3 = (@3-@5) */
  for (i=0, rr=w3, cr=wr3, cs=w5; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #7: @5 = @2[3:6] */
  wr5 = wr2+3;
  /* #8: @6 = @2[6:9] */
  wr6 = wr2+6;
  /* #9: @7 = @2[9:12] */
  wr7 = wr2+9;
  /* #10: @2 = vertcat(@3, @5, @6, @7) */
  rr=w2;
  for (i=0, cs=w3; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=wr5; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=wr6; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=wr7; i<3; ++i) *rr++ = *cs++;
  /* #11: @8 = [100, 100, 100, 1, 1, 1, 1, 1, 1, 1, 1, 1] */
  wr8 = casadi_c0;
  /* #12: @2 = (@2/@8) */
  for (i=0, rr=w2, cs=wr8; i<12; ++i) (*rr++) /= (*cs++);
  /* #13: @8 = @2' */
  casadi_copy(w2, 12, w8);
  /* #14: @9 = 
  [[10000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 10000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 10000, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 400, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 400, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0, 400, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0, 0, 500, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 500, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 500]] */
  wr9 = casadi_c1;
  /* #15: @1 = mac(@8,@9,@1) */
  for (i=0, rr=w1; i<12; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w8+j, ct=wr9+i*12; k<12; ++k) *rr += cs[k*1]**ct++;
  /* #16: @0 = mac(@1,@2,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w1+j, ct=w2+i*12; k<12; ++k) *rr += cs[k*1]**ct++;
  /* #17: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int satellite_full_cost_ext_cost_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int satellite_full_cost_ext_cost_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int satellite_full_cost_ext_cost_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void satellite_full_cost_ext_cost_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int satellite_full_cost_ext_cost_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void satellite_full_cost_ext_cost_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void satellite_full_cost_ext_cost_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void satellite_full_cost_ext_cost_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int satellite_full_cost_ext_cost_e_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int satellite_full_cost_ext_cost_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real satellite_full_cost_ext_cost_e_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* satellite_full_cost_ext_cost_e_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* satellite_full_cost_ext_cost_e_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* satellite_full_cost_ext_cost_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* satellite_full_cost_ext_cost_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int satellite_full_cost_ext_cost_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 200;
  return 0;
}

CASADI_SYMBOL_EXPORT int satellite_full_cost_ext_cost_e_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 200*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
