/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) satellite_full_cost_ext_cost_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s26 CASADI_PREFIX(s26)
#define casadi_s27 CASADI_PREFIX(s27)
#define casadi_s28 CASADI_PREFIX(s28)
#define casadi_s29 CASADI_PREFIX(s29)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s30 CASADI_PREFIX(s30)
#define casadi_s31 CASADI_PREFIX(s31)
#define casadi_s32 CASADI_PREFIX(s32)
#define casadi_s33 CASADI_PREFIX(s33)
#define casadi_s34 CASADI_PREFIX(s34)
#define casadi_s35 CASADI_PREFIX(s35)
#define casadi_s36 CASADI_PREFIX(s36)
#define casadi_s37 CASADI_PREFIX(s37)
#define casadi_s38 CASADI_PREFIX(s38)
#define casadi_s39 CASADI_PREFIX(s39)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s40 CASADI_PREFIX(s40)
#define casadi_s41 CASADI_PREFIX(s41)
#define casadi_s42 CASADI_PREFIX(s42)
#define casadi_s43 CASADI_PREFIX(s43)
#define casadi_s44 CASADI_PREFIX(s44)
#define casadi_s45 CASADI_PREFIX(s45)
#define casadi_s46 CASADI_PREFIX(s46)
#define casadi_s47 CASADI_PREFIX(s47)
#define casadi_s48 CASADI_PREFIX(s48)
#define casadi_s49 CASADI_PREFIX(s49)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s50 CASADI_PREFIX(s50)
#define casadi_s51 CASADI_PREFIX(s51)
#define casadi_s52 CASADI_PREFIX(s52)
#define casadi_s53 CASADI_PREFIX(s53)
#define casadi_s54 CASADI_PREFIX(s54)
#define casadi_s55 CASADI_PREFIX(s55)
#define casadi_s56 CASADI_PREFIX(s56)
#define casadi_s57 CASADI_PREFIX(s57)
#define casadi_s58 CASADI_PREFIX(s58)
#define casadi_s59 CASADI_PREFIX(s59)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s60 CASADI_PREFIX(s60)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[19] = 
  {1, 8, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 0, 0, 0, 0, 0,
  0, 0, 0};
static const casadi_int casadi_s1[75] = 
  {8, 8, 0, 8, 16, 24, 32, 40,
  48, 56, 64, 0, 1, 2, 3, 4,
  5, 6, 7, 0, 1, 2, 3, 4,
  5, 6, 7, 0, 1, 2, 3, 4,
  5, 6, 7, 0, 1, 2, 3, 4,
  5, 6, 7, 0, 1, 2, 3, 4,
  5, 6, 7, 0, 1, 2, 3, 4,
  5, 6, 7, 0, 1, 2, 3, 4,
  5, 6, 7, 0, 1, 2, 3, 4,
  5, 6, 7};
static const casadi_int casadi_s2[12] = 
  {1, 8, 0, 1, 1, 1, 1, 1,
  1, 1, 1, 0};
static const casadi_int casadi_s3[5] = {12, 1, 0, 1, 0};
static const casadi_int casadi_s4[27] = 
  {1, 12, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0};
static const casadi_int casadi_s5[159] = 
  {12, 12, 0, 12, 24, 36, 48, 60,
  72, 84, 96, 108, 120, 132, 144, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s6[16] = 
  {1, 12, 0, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 0};
static const casadi_int casadi_s7[20] = 
  {0, 1, 2, 3, 4, 5, 6, 7,
  64, 65, 66, 67, 68, 69, 70, 71,
  72, 73, 74, 75};
static const casadi_int casadi_s8[20] = 
  {0, 8, 16, 24, 32, 40, 48, 56,
  64, 76, 88, 100, 112, 124, 136, 148,
  160, 172, 184, 196};
static const casadi_int casadi_s9[12] = 
  {1, 8, 0, 0, 1, 1, 1, 1,
  1, 1, 1, 0};
static const casadi_int casadi_s10[5] = {12, 1, 0, 1, 1};
static const casadi_int casadi_s11[16] = 
  {1, 12, 0, 0, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 0};
static const casadi_int casadi_s12[20] = 
  {8, 9, 10, 11, 12, 13, 14, 15,
  76, 77, 78, 79, 80, 81, 82, 83,
  84, 85, 86, 87};
static const casadi_int casadi_s13[20] = 
  {1, 9, 17, 25, 33, 41, 49, 57,
  65, 77, 89, 101, 113, 125, 137, 149,
  161, 173, 185, 197};
static const casadi_int casadi_s14[12] = 
  {1, 8, 0, 0, 0, 1, 1, 1,
  1, 1, 1, 0};
static const casadi_int casadi_s15[5] = {12, 1, 0, 1, 2};
static const casadi_int casadi_s16[16] = 
  {1, 12, 0, 0, 0, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 0};
static const casadi_int casadi_s17[20] = 
  {16, 17, 18, 19, 20, 21, 22, 23,
  88, 89, 90, 91, 92, 93, 94, 95,
  96, 97, 98, 99};
static const casadi_int casadi_s18[20] = 
  {2, 10, 18, 26, 34, 42, 50, 58,
  66, 78, 90, 102, 114, 126, 138, 150,
  162, 174, 186, 198};
static const casadi_int casadi_s19[12] = 
  {1, 8, 0, 0, 0, 0, 1, 1,
  1, 1, 1, 0};
static const casadi_int casadi_s20[5] = {12, 1, 0, 1, 3};
static const casadi_int casadi_s21[16] = 
  {1, 12, 0, 0, 0, 0, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 0};
static const casadi_int casadi_s22[20] = 
  {24, 25, 26, 27, 28, 29, 30, 31,
  100, 101, 102, 103, 104, 105, 106, 107,
  108, 109, 110, 111};
static const casadi_int casadi_s23[20] = 
  {3, 11, 19, 27, 35, 43, 51, 59,
  67, 79, 91, 103, 115, 127, 139, 151,
  163, 175, 187, 199};
static const casadi_int casadi_s24[12] = 
  {1, 8, 0, 0, 0, 0, 0, 1,
  1, 1, 1, 0};
static const casadi_int casadi_s25[5] = {12, 1, 0, 1, 4};
static const casadi_int casadi_s26[16] = 
  {1, 12, 0, 0, 0, 0, 0, 1,
  1, 1, 1, 1, 1, 1, 1, 0};
static const casadi_int casadi_s27[20] = 
  {32, 33, 34, 35, 36, 37, 38, 39,
  112, 113, 114, 115, 116, 117, 118, 119,
  120, 121, 122, 123};
static const casadi_int casadi_s28[20] = 
  {4, 12, 20, 28, 36, 44, 52, 60,
  68, 80, 92, 104, 116, 128, 140, 152,
  164, 176, 188, 200};
static const casadi_int casadi_s29[12] = 
  {1, 8, 0, 0, 0, 0, 0, 0,
  1, 1, 1, 0};
static const casadi_int casadi_s30[5] = {12, 1, 0, 1, 5};
static const casadi_int casadi_s31[16] = 
  {1, 12, 0, 0, 0, 0, 0, 0,
  1, 1, 1, 1, 1, 1, 1, 0};
static const casadi_int casadi_s32[20] = 
  {40, 41, 42, 43, 44, 45, 46, 47,
  124, 125, 126, 127, 128, 129, 130, 131,
  132, 133, 134, 135};
static const casadi_int casadi_s33[20] = 
  {5, 13, 21, 29, 37, 45, 53, 61,
  69, 81, 93, 105, 117, 129, 141, 153,
  165, 177, 189, 201};
static const casadi_int casadi_s34[12] = 
  {1, 8, 0, 0, 0, 0, 0, 0,
  0, 1, 1, 0};
static const casadi_int casadi_s35[5] = {12, 1, 0, 1, 6};
static const casadi_int casadi_s36[16] = 
  {1, 12, 0, 0, 0, 0, 0, 0,
  0, 1, 1, 1, 1, 1, 1, 0};
static const casadi_int casadi_s37[20] = 
  {48, 49, 50, 51, 52, 53, 54, 55,
  136, 137, 138, 139, 140, 141, 142, 143,
  144, 145, 146, 147};
static const casadi_int casadi_s38[20] = 
  {6, 14, 22, 30, 38, 46, 54, 62,
  70, 82, 94, 106, 118, 130, 142, 154,
  166, 178, 190, 202};
static const casadi_int casadi_s39[12] = 
  {1, 8, 0, 0, 0, 0, 0, 0,
  0, 0, 1, 0};
static const casadi_int casadi_s40[5] = {12, 1, 0, 1, 7};
static const casadi_int casadi_s41[16] = 
  {1, 12, 0, 0, 0, 0, 0, 0,
  0, 0, 1, 1, 1, 1, 1, 0};
static const casadi_int casadi_s42[20] = 
  {56, 57, 58, 59, 60, 61, 62, 63,
  148, 149, 150, 151, 152, 153, 154, 155,
  156, 157, 158, 159};
static const casadi_int casadi_s43[20] = 
  {7, 15, 23, 31, 39, 47, 55, 63,
  71, 83, 95, 107, 119, 131, 143, 155,
  167, 179, 191, 203};
static const casadi_int casadi_s44[5] = {12, 1, 0, 1, 8};
static const casadi_int casadi_s45[16] = 
  {1, 12, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s46[5] = {12, 1, 0, 1, 9};
static const casadi_int casadi_s47[16] = 
  {1, 12, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s48[5] = {12, 1, 0, 1, 10};
static const casadi_int casadi_s49[16] = 
  {1, 12, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s50[5] = {12, 1, 0, 1, 11};
static const casadi_int casadi_s51[16] = 
  {1, 12, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s52[231] = 
  {20, 20, 0, 8, 16, 24, 32, 40,
  48, 56, 64, 76, 88, 100, 112, 124,
  136, 148, 160, 172, 184, 196, 208, 0,
  1, 2, 3, 4, 5, 6, 7, 0,
  1, 2, 3, 4, 5, 6, 7, 0,
  1, 2, 3, 4, 5, 6, 7, 0,
  1, 2, 3, 4, 5, 6, 7, 0,
  1, 2, 3, 4, 5, 6, 7, 0,
  1, 2, 3, 4, 5, 6, 7, 0,
  1, 2, 3, 4, 5, 6, 7, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 12, 13, 14, 15, 16,
  17, 18, 19, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 17, 18, 19, 8,
  9, 10, 11, 12, 13, 14, 15, 16,
  17, 18, 19, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 17, 18, 19, 8,
  9, 10, 11, 12, 13, 14, 15, 16,
  17, 18, 19, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 17, 18, 19, 8,
  9, 10, 11, 12, 13, 14, 15, 16,
  17, 18, 19, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 17, 18, 19, 8,
  9, 10, 11, 12, 13, 14, 15, 16,
  17, 18, 19, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 17, 18, 19, 8,
  9, 10, 11, 12, 13, 14, 15, 16,
  17, 18, 19, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 17, 18, 19};
static const casadi_int casadi_s53[3] = {12, 1, 1};
static const casadi_int casadi_s54[3] = {8, 1, 1};
static const casadi_int casadi_s55[3] = {0, 1, 1};
static const casadi_int casadi_s56[3] = {10, 1, 1};
static const casadi_int casadi_s57[3] = {1, 1, 1};
static const casadi_int casadi_s58[3] = {20, 1, 1};
static const casadi_int casadi_s59[3] = {0, 0, 1};
static const casadi_int casadi_s60[3] = {0, 20, 1};

static const casadi_real casadi_c0[12] = 
  {100., 100., 100., 1., 1., 1., 1., 1.,
  1., 1., 1., 1.};
static const casadi_real casadi_c1[144] = 
  {1000., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 1000., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 1000., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 10.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 10., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 10., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 40., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 40., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  40., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 50., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 50., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 50.};
static const casadi_real casadi_c2[64] = 
  {10., 0., 0., 0., 0., 0., 0., 0.,
  0., 10., 0., 0., 0., 0., 0., 0.,
  0., 0., 10., 0., 0., 0., 0., 0.,
  0., 0., 0., 10., 0., 0., 0., 0.,
  0., 0., 0., 0., 10., 0., 0., 0.,
  0., 0., 0., 0., 0., 10., 0., 0.,
  0., 0., 0., 0., 0., 0., 10., 0.,
  0., 0., 0., 0., 0., 0., 0., 10.};

static const casadi_real casadi_zeros[12] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0.};

/* satellite_full_cost_ext_cost_fun_jac_hess:(i0[12],i1[8],i2[0],i3[10])->(o0,o1[20],o2[20x20,208nz],o3[],o4[0x20]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+2, *w02=w+14, *w03=w+26, *w04=w+29, *w05=w+35, *w06=w+38, *w07=w+41, *w09=w+56, *w11=w+212, w12;
  casadi_real *w13=w+225, *w14=w+233, *w17=w+313, *w18=w+321, *w19=w+385, *w20=w+529, *w21=w+541, *w22=w+749, w23, *w25=w+752, *w26=w+772;
  const casadi_int *cii;
  const casadi_real *cr, *cs, *ct, *wr02, *wr03, *wr05, *wr06, *wr07, *wr08, *wr10, *wr14, *wr15;
  const casadi_real *wr16;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x12) */
  casadi_clear(w01, 12);
  /* #2: @2 = input[0][0] */
  wr02 = arg[0] ? arg[0] : casadi_zeros;
  /* #3: @3 = @2[:3] */
  wr03 = wr02+0;
  /* #4: @4 = input[3][0] */
  casadi_copy(arg[3], 6, w04);
  /* #5: @5 = @4[:3] */
  for (rr=w05, cs=w04+0; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #6: @3 = (@3-@5) */
  for (i=0, rr=w03, cr=wr03, cs=w05; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #7: @5 = @2[3:6] */
  wr05 = wr02+3;
  /* #8: @6 = @2[6:9] */
  wr06 = wr02+6;
  /* #9: @7 = @2[9:12] */
  wr07 = wr02+9;
  /* #10: @2 = vertcat(@3, @5, @6, @7) */
  rr=w02;
  for (i=0, cs=w03; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=wr05; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=wr06; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=wr07; i<3; ++i) *rr++ = *cs++;
  /* #11: @8 = [100, 100, 100, 1, 1, 1, 1, 1, 1, 1, 1, 1] */
  wr08 = casadi_c0;
  /* #12: @2 = (@2/@8) */
  for (i=0, rr=w02, cs=wr08; i<12; ++i) (*rr++) /= (*cs++);
  /* #13: @9 = @2' */
  casadi_copy(w02, 12, w09);
  /* #14: @10 = 
  [[1000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 40, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 40, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0, 40, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0, 0, 50, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 50, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 50]] */
  wr10 = casadi_c1;
  /* #15: @11 = mac(@9,@10,@1) */
  casadi_copy(w01, 12, w11);
  for (i=0, rr=w11; i<12; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w09+j, ct=wr10+i*12; k<12; ++k) *rr += cs[k*1]**ct++;
  /* #16: @12 = mac(@11,@2,@0) */
  casadi_copy((&w00), 1, (&w12));
  for (i=0, rr=(&w12); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w11+j, ct=w02+i*12; k<12; ++k) *rr += cs[k*1]**ct++;
  /* #17: @13 = zeros(1x8) */
  casadi_clear(w13, 8);
  /* #18: @14 = input[1][0] */
  wr14 = arg[1] ? arg[1] : casadi_zeros;
  /* #19: @15 = @14' */
  wr15 = wr14;
  /* #20: @16 = 
  [[10, 0, 0, 0, 0, 0, 0, 0], 
   [0, 10, 0, 0, 0, 0, 0, 0], 
   [0, 0, 10, 0, 0, 0, 0, 0], 
   [0, 0, 0, 10, 0, 0, 0, 0], 
   [0, 0, 0, 0, 10, 0, 0, 0], 
   [0, 0, 0, 0, 0, 10, 0, 0], 
   [0, 0, 0, 0, 0, 0, 10, 0], 
   [0, 0, 0, 0, 0, 0, 0, 10]] */
  wr16 = casadi_c2;
  /* #21: @17 = mac(@15,@16,@13) */
  casadi_copy(w13, 8, w17);
  for (i=0, rr=w17; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=wr15+j, ct=wr16+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #22: @0 = mac(@17,@14,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w17+j, ct=wr14+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #23: @12 = (@12+@0) */
  w12 += w00;
  /* #24: output[0][0] = @12 */
  if (res[0]) res[0][0] = w12;
  /* #25: @17 = @17' */
  /* #26: @18 = @16' */
  for (i=0, rr=w18, cs=wr16; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #27: @14 = mac(@15,@18,@13) */
  casadi_copy(w13, 8, w14);
  for (i=0, rr=w14; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=wr15+j, ct=w18+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #28: @14 = @14' */
  /* #29: @17 = (@17+@14) */
  for (i=0, rr=w17, cs=w14; i<8; ++i) (*rr++) += (*cs++);
  /* #30: output[1][0] = @17 */
  casadi_copy(w17, 8, res[1]);
  /* #31: @2 = zeros(12x1) */
  casadi_clear(w02, 12);
  /* #32: @11 = @11' */
  /* #33: @19 = @10' */
  for (i=0, rr=w19, cs=wr10; i<12; ++i) for (j=0; j<12; ++j) rr[i+j*12] = *cs++;
  /* #34: @20 = mac(@9,@19,@1) */
  casadi_copy(w01, 12, w20);
  for (i=0, rr=w20; i<12; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w09+j, ct=w19+i*12; k<12; ++k) *rr += cs[k*1]**ct++;
  /* #35: @20 = @20' */
  /* #36: @11 = (@11+@20) */
  for (i=0, rr=w11, cs=w20; i<12; ++i) (*rr++) += (*cs++);
  /* #37: @11 = (@11/@8) */
  for (i=0, rr=w11, cs=wr08; i<12; ++i) (*rr++) /= (*cs++);
  /* #38: {@3, @5, @6, @7} = vertsplit(@11) */
  casadi_copy(w11, 3, w03);
  casadi_copy(w11+3, 3, w05);
  casadi_copy(w11+6, 3, w06);
  casadi_copy(w11+9, 3, w07);
  /* #39: @11 = @2; (@11[9:12] += @7) */
  casadi_copy(w02, 12, w11);
  for (rr=w11+9, cs=w07; rr!=w11+12; rr+=1) *rr += *cs++;
  /* #40: (@11[6:9] += @6) */
  for (rr=w11+6, cs=w06; rr!=w11+9; rr+=1) *rr += *cs++;
  /* #41: (@11[3:6] += @5) */
  for (rr=w11+3, cs=w05; rr!=w11+6; rr+=1) *rr += *cs++;
  /* #42: (@11[:3] += @3) */
  for (rr=w11+0, cs=w03; rr!=w11+3; rr+=1) *rr += *cs++;
  /* #43: output[1][1] = @11 */
  if (res[1]) casadi_copy(w11, 12, res[1]+8);
  /* #44: @21 = zeros(20x20,208nz) */
  casadi_clear(w21, 208);
  /* #45: @22 = ones(20x1,2nz) */
  casadi_fill(w22, 2, 1.);
  /* #46: {@12, @0} = vertsplit(@22) */
  w12 = w22[0];
  w00 = w22[1];
  /* #47: @12 = @12' */
  /* #48: @17 = mac(@12,@16,@13) */
  casadi_copy(w13, 8, w17);
  casadi_mtimes((&w12), casadi_s2, wr16, casadi_s1, w17, casadi_s0, w, 0);
  /* #49: @17 = @17' */
  /* #50: @14 = mac(@12,@18,@13) */
  casadi_copy(w13, 8, w14);
  casadi_mtimes((&w12), casadi_s2, w18, casadi_s1, w14, casadi_s0, w, 0);
  /* #51: @14 = @14' */
  /* #52: @17 = (@17+@14) */
  for (i=0, rr=w17, cs=w14; i<8; ++i) (*rr++) += (*cs++);
  /* #53: @11 = (1./@8) */
  for (i=0, rr=w11, cs=wr08; i<12; ++i) *rr++ = (1./ *cs++ );
  /* #54: @12 = project(@11) */
  casadi_sparsify(w11, (&w12), casadi_s3, 0);
  /* #55: @23 = @0[0] */
  for (rr=(&w23), cs=(&w00)+0; cs!=(&w00)+1; cs+=1) *rr++ = *cs;
  /* #56: @24 = zeros(3x1,0nz) */
  /* #57: @0 = vertcat(@23, @24, @24, @24) */
  rr=(&w00);
  *rr++ = w23;
  /* #58: @12 = (@12*@0) */
  w12 *= w00;
  /* #59: @12 = @12' */
  /* #60: @20 = mac(@12,@10,@1) */
  casadi_copy(w01, 12, w20);
  casadi_mtimes((&w12), casadi_s6, wr10, casadi_s5, w20, casadi_s4, w, 0);
  /* #61: @20 = @20' */
  /* #62: @9 = mac(@12,@19,@1) */
  casadi_copy(w01, 12, w09);
  casadi_mtimes((&w12), casadi_s6, w19, casadi_s5, w09, casadi_s4, w, 0);
  /* #63: @9 = @9' */
  /* #64: @20 = (@20+@9) */
  for (i=0, rr=w20, cs=w09; i<12; ++i) (*rr++) += (*cs++);
  /* #65: @20 = (@20/@8) */
  for (i=0, rr=w20, cs=wr08; i<12; ++i) (*rr++) /= (*cs++);
  /* #66: {@3, @5, @6, @7} = vertsplit(@20) */
  casadi_copy(w20, 3, w03);
  casadi_copy(w20+3, 3, w05);
  casadi_copy(w20+6, 3, w06);
  casadi_copy(w20+9, 3, w07);
  /* #67: @20 = @2; (@20[9:12] += @7) */
  casadi_copy(w02, 12, w20);
  for (rr=w20+9, cs=w07; rr!=w20+12; rr+=1) *rr += *cs++;
  /* #68: (@20[6:9] += @6) */
  for (rr=w20+6, cs=w06; rr!=w20+9; rr+=1) *rr += *cs++;
  /* #69: (@20[3:6] += @5) */
  for (rr=w20+3, cs=w05; rr!=w20+6; rr+=1) *rr += *cs++;
  /* #70: (@20[:3] += @3) */
  for (rr=w20+0, cs=w03; rr!=w20+3; rr+=1) *rr += *cs++;
  /* #71: @25 = vertcat(@17, @20) */
  rr=w25;
  for (i=0, cs=w17; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<12; ++i) *rr++ = *cs++;
  /* #72: (@21[0, 1, 2, 3, 4, 5, 6, 7, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75] = @25) */
  for (cii=casadi_s7, rr=w21, cs=w25; cii!=casadi_s7+20; ++cii, ++cs) rr[*cii] = *cs;
  /* #73: (@21[0, 8, 16, 24, 32, 40, 48, 56, 64, 76, 88, 100, 112, 124, 136, 148, 160, 172, 184, 196] = @25) */
  for (cii=casadi_s8, rr=w21, cs=w25; cii!=casadi_s8+20; ++cii, ++cs) rr[*cii] = *cs;
  /* #74: @22 = ones(20x1,2nz) */
  casadi_fill(w22, 2, 1.);
  /* #75: {@12, @0} = vertsplit(@22) */
  w12 = w22[0];
  w00 = w22[1];
  /* #76: @12 = @12' */
  /* #77: @17 = mac(@12,@16,@13) */
  casadi_copy(w13, 8, w17);
  casadi_mtimes((&w12), casadi_s9, wr16, casadi_s1, w17, casadi_s0, w, 0);
  /* #78: @17 = @17' */
  /* #79: @14 = mac(@12,@18,@13) */
  casadi_copy(w13, 8, w14);
  casadi_mtimes((&w12), casadi_s9, w18, casadi_s1, w14, casadi_s0, w, 0);
  /* #80: @14 = @14' */
  /* #81: @17 = (@17+@14) */
  for (i=0, rr=w17, cs=w14; i<8; ++i) (*rr++) += (*cs++);
  /* #82: @12 = project(@11) */
  casadi_sparsify(w11, (&w12), casadi_s10, 0);
  /* #83: @23 = @0[0] */
  for (rr=(&w23), cs=(&w00)+0; cs!=(&w00)+1; cs+=1) *rr++ = *cs;
  /* #84: @0 = vertcat(@23, @24, @24, @24) */
  rr=(&w00);
  *rr++ = w23;
  /* #85: @12 = (@12*@0) */
  w12 *= w00;
  /* #86: @12 = @12' */
  /* #87: @20 = mac(@12,@10,@1) */
  casadi_copy(w01, 12, w20);
  casadi_mtimes((&w12), casadi_s11, wr10, casadi_s5, w20, casadi_s4, w, 0);
  /* #88: @20 = @20' */
  /* #89: @9 = mac(@12,@19,@1) */
  casadi_copy(w01, 12, w09);
  casadi_mtimes((&w12), casadi_s11, w19, casadi_s5, w09, casadi_s4, w, 0);
  /* #90: @9 = @9' */
  /* #91: @20 = (@20+@9) */
  for (i=0, rr=w20, cs=w09; i<12; ++i) (*rr++) += (*cs++);
  /* #92: @20 = (@20/@8) */
  for (i=0, rr=w20, cs=wr08; i<12; ++i) (*rr++) /= (*cs++);
  /* #93: {@3, @5, @6, @7} = vertsplit(@20) */
  casadi_copy(w20, 3, w03);
  casadi_copy(w20+3, 3, w05);
  casadi_copy(w20+6, 3, w06);
  casadi_copy(w20+9, 3, w07);
  /* #94: @20 = @2; (@20[9:12] += @7) */
  casadi_copy(w02, 12, w20);
  for (rr=w20+9, cs=w07; rr!=w20+12; rr+=1) *rr += *cs++;
  /* #95: (@20[6:9] += @6) */
  for (rr=w20+6, cs=w06; rr!=w20+9; rr+=1) *rr += *cs++;
  /* #96: (@20[3:6] += @5) */
  for (rr=w20+3, cs=w05; rr!=w20+6; rr+=1) *rr += *cs++;
  /* #97: (@20[:3] += @3) */
  for (rr=w20+0, cs=w03; rr!=w20+3; rr+=1) *rr += *cs++;
  /* #98: @25 = vertcat(@17, @20) */
  rr=w25;
  for (i=0, cs=w17; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<12; ++i) *rr++ = *cs++;
  /* #99: (@21[8, 9, 10, 11, 12, 13, 14, 15, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87] = @25) */
  for (cii=casadi_s12, rr=w21, cs=w25; cii!=casadi_s12+20; ++cii, ++cs) rr[*cii] = *cs;
  /* #100: (@21[1, 9, 17, 25, 33, 41, 49, 57, 65, 77, 89, 101, 113, 125, 137, 149, 161, 173, 185, 197] = @25) */
  for (cii=casadi_s13, rr=w21, cs=w25; cii!=casadi_s13+20; ++cii, ++cs) rr[*cii] = *cs;
  /* #101: @22 = ones(20x1,2nz) */
  casadi_fill(w22, 2, 1.);
  /* #102: {@12, @0} = vertsplit(@22) */
  w12 = w22[0];
  w00 = w22[1];
  /* #103: @12 = @12' */
  /* #104: @17 = mac(@12,@16,@13) */
  casadi_copy(w13, 8, w17);
  casadi_mtimes((&w12), casadi_s14, wr16, casadi_s1, w17, casadi_s0, w, 0);
  /* #105: @17 = @17' */
  /* #106: @14 = mac(@12,@18,@13) */
  casadi_copy(w13, 8, w14);
  casadi_mtimes((&w12), casadi_s14, w18, casadi_s1, w14, casadi_s0, w, 0);
  /* #107: @14 = @14' */
  /* #108: @17 = (@17+@14) */
  for (i=0, rr=w17, cs=w14; i<8; ++i) (*rr++) += (*cs++);
  /* #109: @12 = project(@11) */
  casadi_sparsify(w11, (&w12), casadi_s15, 0);
  /* #110: @23 = @0[0] */
  for (rr=(&w23), cs=(&w00)+0; cs!=(&w00)+1; cs+=1) *rr++ = *cs;
  /* #111: @0 = vertcat(@23, @24, @24, @24) */
  rr=(&w00);
  *rr++ = w23;
  /* #112: @12 = (@12*@0) */
  w12 *= w00;
  /* #113: @12 = @12' */
  /* #114: @20 = mac(@12,@10,@1) */
  casadi_copy(w01, 12, w20);
  casadi_mtimes((&w12), casadi_s16, wr10, casadi_s5, w20, casadi_s4, w, 0);
  /* #115: @20 = @20' */
  /* #116: @9 = mac(@12,@19,@1) */
  casadi_copy(w01, 12, w09);
  casadi_mtimes((&w12), casadi_s16, w19, casadi_s5, w09, casadi_s4, w, 0);
  /* #117: @9 = @9' */
  /* #118: @20 = (@20+@9) */
  for (i=0, rr=w20, cs=w09; i<12; ++i) (*rr++) += (*cs++);
  /* #119: @20 = (@20/@8) */
  for (i=0, rr=w20, cs=wr08; i<12; ++i) (*rr++) /= (*cs++);
  /* #120: {@3, @5, @6, @7} = vertsplit(@20) */
  casadi_copy(w20, 3, w03);
  casadi_copy(w20+3, 3, w05);
  casadi_copy(w20+6, 3, w06);
  casadi_copy(w20+9, 3, w07);
  /* #121: @20 = @2; (@20[9:12] += @7) */
  casadi_copy(w02, 12, w20);
  for (rr=w20+9, cs=w07; rr!=w20+12; rr+=1) *rr += *cs++;
  /* #122: (@20[6:9] += @6) */
  for (rr=w20+6, cs=w06; rr!=w20+9; rr+=1) *rr += *cs++;
  /* #123: (@20[3:6] += @5) */
  for (rr=w20+3, cs=w05; rr!=w20+6; rr+=1) *rr += *cs++;
  /* #124: (@20[:3] += @3) */
  for (rr=w20+0, cs=w03; rr!=w20+3; rr+=1) *rr += *cs++;
  /* #125: @25 = vertcat(@17, @20) */
  rr=w25;
  for (i=0, cs=w17; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<12; ++i) *rr++ = *cs++;
  /* #126: (@21[16, 17, 18, 19, 20, 21, 22, 23, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99] = @25) */
  for (cii=casadi_s17, rr=w21, cs=w25; cii!=casadi_s17+20; ++cii, ++cs) rr[*cii] = *cs;
  /* #127: (@21[2, 10, 18, 26, 34, 42, 50, 58, 66, 78, 90, 102, 114, 126, 138, 150, 162, 174, 186, 198] = @25) */
  for (cii=casadi_s18, rr=w21, cs=w25; cii!=casadi_s18+20; ++cii, ++cs) rr[*cii] = *cs;
  /* #128: @22 = ones(20x1,2nz) */
  casadi_fill(w22, 2, 1.);
  /* #129: {@12, @0} = vertsplit(@22) */
  w12 = w22[0];
  w00 = w22[1];
  /* #130: @12 = @12' */
  /* #131: @17 = mac(@12,@16,@13) */
  casadi_copy(w13, 8, w17);
  casadi_mtimes((&w12), casadi_s19, wr16, casadi_s1, w17, casadi_s0, w, 0);
  /* #132: @17 = @17' */
  /* #133: @14 = mac(@12,@18,@13) */
  casadi_copy(w13, 8, w14);
  casadi_mtimes((&w12), casadi_s19, w18, casadi_s1, w14, casadi_s0, w, 0);
  /* #134: @14 = @14' */
  /* #135: @17 = (@17+@14) */
  for (i=0, rr=w17, cs=w14; i<8; ++i) (*rr++) += (*cs++);
  /* #136: @12 = project(@11) */
  casadi_sparsify(w11, (&w12), casadi_s20, 0);
  /* #137: @23 = @0[0] */
  for (rr=(&w23), cs=(&w00)+0; cs!=(&w00)+1; cs+=1) *rr++ = *cs;
  /* #138: @0 = vertcat(@24, @23, @24, @24) */
  rr=(&w00);
  *rr++ = w23;
  /* #139: @12 = (@12*@0) */
  w12 *= w00;
  /* #140: @12 = @12' */
  /* #141: @20 = mac(@12,@10,@1) */
  casadi_copy(w01, 12, w20);
  casadi_mtimes((&w12), casadi_s21, wr10, casadi_s5, w20, casadi_s4, w, 0);
  /* #142: @20 = @20' */
  /* #143: @9 = mac(@12,@19,@1) */
  casadi_copy(w01, 12, w09);
  casadi_mtimes((&w12), casadi_s21, w19, casadi_s5, w09, casadi_s4, w, 0);
  /* #144: @9 = @9' */
  /* #145: @20 = (@20+@9) */
  for (i=0, rr=w20, cs=w09; i<12; ++i) (*rr++) += (*cs++);
  /* #146: @20 = (@20/@8) */
  for (i=0, rr=w20, cs=wr08; i<12; ++i) (*rr++) /= (*cs++);
  /* #147: {@3, @5, @6, @7} = vertsplit(@20) */
  casadi_copy(w20, 3, w03);
  casadi_copy(w20+3, 3, w05);
  casadi_copy(w20+6, 3, w06);
  casadi_copy(w20+9, 3, w07);
  /* #148: @20 = @2; (@20[9:12] += @7) */
  casadi_copy(w02, 12, w20);
  for (rr=w20+9, cs=w07; rr!=w20+12; rr+=1) *rr += *cs++;
  /* #149: (@20[6:9] += @6) */
  for (rr=w20+6, cs=w06; rr!=w20+9; rr+=1) *rr += *cs++;
  /* #150: (@20[3:6] += @5) */
  for (rr=w20+3, cs=w05; rr!=w20+6; rr+=1) *rr += *cs++;
  /* #151: (@20[:3] += @3) */
  for (rr=w20+0, cs=w03; rr!=w20+3; rr+=1) *rr += *cs++;
  /* #152: @25 = vertcat(@17, @20) */
  rr=w25;
  for (i=0, cs=w17; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<12; ++i) *rr++ = *cs++;
  /* #153: (@21[24, 25, 26, 27, 28, 29, 30, 31, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111] = @25) */
  for (cii=casadi_s22, rr=w21, cs=w25; cii!=casadi_s22+20; ++cii, ++cs) rr[*cii] = *cs;
  /* #154: (@21[3, 11, 19, 27, 35, 43, 51, 59, 67, 79, 91, 103, 115, 127, 139, 151, 163, 175, 187, 199] = @25) */
  for (cii=casadi_s23, rr=w21, cs=w25; cii!=casadi_s23+20; ++cii, ++cs) rr[*cii] = *cs;
  /* #155: @22 = ones(20x1,2nz) */
  casadi_fill(w22, 2, 1.);
  /* #156: {@12, @0} = vertsplit(@22) */
  w12 = w22[0];
  w00 = w22[1];
  /* #157: @12 = @12' */
  /* #158: @17 = mac(@12,@16,@13) */
  casadi_copy(w13, 8, w17);
  casadi_mtimes((&w12), casadi_s24, wr16, casadi_s1, w17, casadi_s0, w, 0);
  /* #159: @17 = @17' */
  /* #160: @14 = mac(@12,@18,@13) */
  casadi_copy(w13, 8, w14);
  casadi_mtimes((&w12), casadi_s24, w18, casadi_s1, w14, casadi_s0, w, 0);
  /* #161: @14 = @14' */
  /* #162: @17 = (@17+@14) */
  for (i=0, rr=w17, cs=w14; i<8; ++i) (*rr++) += (*cs++);
  /* #163: @12 = project(@11) */
  casadi_sparsify(w11, (&w12), casadi_s25, 0);
  /* #164: @23 = @0[0] */
  for (rr=(&w23), cs=(&w00)+0; cs!=(&w00)+1; cs+=1) *rr++ = *cs;
  /* #165: @0 = vertcat(@24, @23, @24, @24) */
  rr=(&w00);
  *rr++ = w23;
  /* #166: @12 = (@12*@0) */
  w12 *= w00;
  /* #167: @12 = @12' */
  /* #168: @20 = mac(@12,@10,@1) */
  casadi_copy(w01, 12, w20);
  casadi_mtimes((&w12), casadi_s26, wr10, casadi_s5, w20, casadi_s4, w, 0);
  /* #169: @20 = @20' */
  /* #170: @9 = mac(@12,@19,@1) */
  casadi_copy(w01, 12, w09);
  casadi_mtimes((&w12), casadi_s26, w19, casadi_s5, w09, casadi_s4, w, 0);
  /* #171: @9 = @9' */
  /* #172: @20 = (@20+@9) */
  for (i=0, rr=w20, cs=w09; i<12; ++i) (*rr++) += (*cs++);
  /* #173: @20 = (@20/@8) */
  for (i=0, rr=w20, cs=wr08; i<12; ++i) (*rr++) /= (*cs++);
  /* #174: {@3, @5, @6, @7} = vertsplit(@20) */
  casadi_copy(w20, 3, w03);
  casadi_copy(w20+3, 3, w05);
  casadi_copy(w20+6, 3, w06);
  casadi_copy(w20+9, 3, w07);
  /* #175: @20 = @2; (@20[9:12] += @7) */
  casadi_copy(w02, 12, w20);
  for (rr=w20+9, cs=w07; rr!=w20+12; rr+=1) *rr += *cs++;
  /* #176: (@20[6:9] += @6) */
  for (rr=w20+6, cs=w06; rr!=w20+9; rr+=1) *rr += *cs++;
  /* #177: (@20[3:6] += @5) */
  for (rr=w20+3, cs=w05; rr!=w20+6; rr+=1) *rr += *cs++;
  /* #178: (@20[:3] += @3) */
  for (rr=w20+0, cs=w03; rr!=w20+3; rr+=1) *rr += *cs++;
  /* #179: @25 = vertcat(@17, @20) */
  rr=w25;
  for (i=0, cs=w17; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<12; ++i) *rr++ = *cs++;
  /* #180: (@21[32, 33, 34, 35, 36, 37, 38, 39, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123] = @25) */
  for (cii=casadi_s27, rr=w21, cs=w25; cii!=casadi_s27+20; ++cii, ++cs) rr[*cii] = *cs;
  /* #181: (@21[4, 12, 20, 28, 36, 44, 52, 60, 68, 80, 92, 104, 116, 128, 140, 152, 164, 176, 188, 200] = @25) */
  for (cii=casadi_s28, rr=w21, cs=w25; cii!=casadi_s28+20; ++cii, ++cs) rr[*cii] = *cs;
  /* #182: @22 = ones(20x1,2nz) */
  casadi_fill(w22, 2, 1.);
  /* #183: {@12, @0} = vertsplit(@22) */
  w12 = w22[0];
  w00 = w22[1];
  /* #184: @12 = @12' */
  /* #185: @17 = mac(@12,@16,@13) */
  casadi_copy(w13, 8, w17);
  casadi_mtimes((&w12), casadi_s29, wr16, casadi_s1, w17, casadi_s0, w, 0);
  /* #186: @17 = @17' */
  /* #187: @14 = mac(@12,@18,@13) */
  casadi_copy(w13, 8, w14);
  casadi_mtimes((&w12), casadi_s29, w18, casadi_s1, w14, casadi_s0, w, 0);
  /* #188: @14 = @14' */
  /* #189: @17 = (@17+@14) */
  for (i=0, rr=w17, cs=w14; i<8; ++i) (*rr++) += (*cs++);
  /* #190: @12 = project(@11) */
  casadi_sparsify(w11, (&w12), casadi_s30, 0);
  /* #191: @23 = @0[0] */
  for (rr=(&w23), cs=(&w00)+0; cs!=(&w00)+1; cs+=1) *rr++ = *cs;
  /* #192: @0 = vertcat(@24, @23, @24, @24) */
  rr=(&w00);
  *rr++ = w23;
  /* #193: @12 = (@12*@0) */
  w12 *= w00;
  /* #194: @12 = @12' */
  /* #195: @20 = mac(@12,@10,@1) */
  casadi_copy(w01, 12, w20);
  casadi_mtimes((&w12), casadi_s31, wr10, casadi_s5, w20, casadi_s4, w, 0);
  /* #196: @20 = @20' */
  /* #197: @9 = mac(@12,@19,@1) */
  casadi_copy(w01, 12, w09);
  casadi_mtimes((&w12), casadi_s31, w19, casadi_s5, w09, casadi_s4, w, 0);
  /* #198: @9 = @9' */
  /* #199: @20 = (@20+@9) */
  for (i=0, rr=w20, cs=w09; i<12; ++i) (*rr++) += (*cs++);
  /* #200: @20 = (@20/@8) */
  for (i=0, rr=w20, cs=wr08; i<12; ++i) (*rr++) /= (*cs++);
  /* #201: {@3, @5, @6, @7} = vertsplit(@20) */
  casadi_copy(w20, 3, w03);
  casadi_copy(w20+3, 3, w05);
  casadi_copy(w20+6, 3, w06);
  casadi_copy(w20+9, 3, w07);
  /* #202: @20 = @2; (@20[9:12] += @7) */
  casadi_copy(w02, 12, w20);
  for (rr=w20+9, cs=w07; rr!=w20+12; rr+=1) *rr += *cs++;
  /* #203: (@20[6:9] += @6) */
  for (rr=w20+6, cs=w06; rr!=w20+9; rr+=1) *rr += *cs++;
  /* #204: (@20[3:6] += @5) */
  for (rr=w20+3, cs=w05; rr!=w20+6; rr+=1) *rr += *cs++;
  /* #205: (@20[:3] += @3) */
  for (rr=w20+0, cs=w03; rr!=w20+3; rr+=1) *rr += *cs++;
  /* #206: @25 = vertcat(@17, @20) */
  rr=w25;
  for (i=0, cs=w17; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<12; ++i) *rr++ = *cs++;
  /* #207: (@21[40, 41, 42, 43, 44, 45, 46, 47, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135] = @25) */
  for (cii=casadi_s32, rr=w21, cs=w25; cii!=casadi_s32+20; ++cii, ++cs) rr[*cii] = *cs;
  /* #208: (@21[5, 13, 21, 29, 37, 45, 53, 61, 69, 81, 93, 105, 117, 129, 141, 153, 165, 177, 189, 201] = @25) */
  for (cii=casadi_s33, rr=w21, cs=w25; cii!=casadi_s33+20; ++cii, ++cs) rr[*cii] = *cs;
  /* #209: @22 = ones(20x1,2nz) */
  casadi_fill(w22, 2, 1.);
  /* #210: {@12, @0} = vertsplit(@22) */
  w12 = w22[0];
  w00 = w22[1];
  /* #211: @12 = @12' */
  /* #212: @17 = mac(@12,@16,@13) */
  casadi_copy(w13, 8, w17);
  casadi_mtimes((&w12), casadi_s34, wr16, casadi_s1, w17, casadi_s0, w, 0);
  /* #213: @17 = @17' */
  /* #214: @14 = mac(@12,@18,@13) */
  casadi_copy(w13, 8, w14);
  casadi_mtimes((&w12), casadi_s34, w18, casadi_s1, w14, casadi_s0, w, 0);
  /* #215: @14 = @14' */
  /* #216: @17 = (@17+@14) */
  for (i=0, rr=w17, cs=w14; i<8; ++i) (*rr++) += (*cs++);
  /* #217: @12 = project(@11) */
  casadi_sparsify(w11, (&w12), casadi_s35, 0);
  /* #218: @23 = @0[0] */
  for (rr=(&w23), cs=(&w00)+0; cs!=(&w00)+1; cs+=1) *rr++ = *cs;
  /* #219: @0 = vertcat(@24, @24, @23, @24) */
  rr=(&w00);
  *rr++ = w23;
  /* #220: @12 = (@12*@0) */
  w12 *= w00;
  /* #221: @12 = @12' */
  /* #222: @20 = mac(@12,@10,@1) */
  casadi_copy(w01, 12, w20);
  casadi_mtimes((&w12), casadi_s36, wr10, casadi_s5, w20, casadi_s4, w, 0);
  /* #223: @20 = @20' */
  /* #224: @9 = mac(@12,@19,@1) */
  casadi_copy(w01, 12, w09);
  casadi_mtimes((&w12), casadi_s36, w19, casadi_s5, w09, casadi_s4, w, 0);
  /* #225: @9 = @9' */
  /* #226: @20 = (@20+@9) */
  for (i=0, rr=w20, cs=w09; i<12; ++i) (*rr++) += (*cs++);
  /* #227: @20 = (@20/@8) */
  for (i=0, rr=w20, cs=wr08; i<12; ++i) (*rr++) /= (*cs++);
  /* #228: {@3, @5, @6, @7} = vertsplit(@20) */
  casadi_copy(w20, 3, w03);
  casadi_copy(w20+3, 3, w05);
  casadi_copy(w20+6, 3, w06);
  casadi_copy(w20+9, 3, w07);
  /* #229: @20 = @2; (@20[9:12] += @7) */
  casadi_copy(w02, 12, w20);
  for (rr=w20+9, cs=w07; rr!=w20+12; rr+=1) *rr += *cs++;
  /* #230: (@20[6:9] += @6) */
  for (rr=w20+6, cs=w06; rr!=w20+9; rr+=1) *rr += *cs++;
  /* #231: (@20[3:6] += @5) */
  for (rr=w20+3, cs=w05; rr!=w20+6; rr+=1) *rr += *cs++;
  /* #232: (@20[:3] += @3) */
  for (rr=w20+0, cs=w03; rr!=w20+3; rr+=1) *rr += *cs++;
  /* #233: @25 = vertcat(@17, @20) */
  rr=w25;
  for (i=0, cs=w17; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<12; ++i) *rr++ = *cs++;
  /* #234: (@21[48, 49, 50, 51, 52, 53, 54, 55, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147] = @25) */
  for (cii=casadi_s37, rr=w21, cs=w25; cii!=casadi_s37+20; ++cii, ++cs) rr[*cii] = *cs;
  /* #235: (@21[6, 14, 22, 30, 38, 46, 54, 62, 70, 82, 94, 106, 118, 130, 142, 154, 166, 178, 190, 202] = @25) */
  for (cii=casadi_s38, rr=w21, cs=w25; cii!=casadi_s38+20; ++cii, ++cs) rr[*cii] = *cs;
  /* #236: @22 = ones(20x1,2nz) */
  casadi_fill(w22, 2, 1.);
  /* #237: {@12, @0} = vertsplit(@22) */
  w12 = w22[0];
  w00 = w22[1];
  /* #238: @12 = @12' */
  /* #239: @17 = mac(@12,@16,@13) */
  casadi_copy(w13, 8, w17);
  casadi_mtimes((&w12), casadi_s39, wr16, casadi_s1, w17, casadi_s0, w, 0);
  /* #240: @17 = @17' */
  /* #241: @13 = mac(@12,@18,@13) */
  casadi_mtimes((&w12), casadi_s39, w18, casadi_s1, w13, casadi_s0, w, 0);
  /* #242: @13 = @13' */
  /* #243: @17 = (@17+@13) */
  for (i=0, rr=w17, cs=w13; i<8; ++i) (*rr++) += (*cs++);
  /* #244: @12 = project(@11) */
  casadi_sparsify(w11, (&w12), casadi_s40, 0);
  /* #245: @23 = @0[0] */
  for (rr=(&w23), cs=(&w00)+0; cs!=(&w00)+1; cs+=1) *rr++ = *cs;
  /* #246: @0 = vertcat(@24, @24, @23, @24) */
  rr=(&w00);
  *rr++ = w23;
  /* #247: @12 = (@12*@0) */
  w12 *= w00;
  /* #248: @12 = @12' */
  /* #249: @20 = mac(@12,@10,@1) */
  casadi_copy(w01, 12, w20);
  casadi_mtimes((&w12), casadi_s41, wr10, casadi_s5, w20, casadi_s4, w, 0);
  /* #250: @20 = @20' */
  /* #251: @9 = mac(@12,@19,@1) */
  casadi_copy(w01, 12, w09);
  casadi_mtimes((&w12), casadi_s41, w19, casadi_s5, w09, casadi_s4, w, 0);
  /* #252: @9 = @9' */
  /* #253: @20 = (@20+@9) */
  for (i=0, rr=w20, cs=w09; i<12; ++i) (*rr++) += (*cs++);
  /* #254: @20 = (@20/@8) */
  for (i=0, rr=w20, cs=wr08; i<12; ++i) (*rr++) /= (*cs++);
  /* #255: {@3, @5, @6, @7} = vertsplit(@20) */
  casadi_copy(w20, 3, w03);
  casadi_copy(w20+3, 3, w05);
  casadi_copy(w20+6, 3, w06);
  casadi_copy(w20+9, 3, w07);
  /* #256: @20 = @2; (@20[9:12] += @7) */
  casadi_copy(w02, 12, w20);
  for (rr=w20+9, cs=w07; rr!=w20+12; rr+=1) *rr += *cs++;
  /* #257: (@20[6:9] += @6) */
  for (rr=w20+6, cs=w06; rr!=w20+9; rr+=1) *rr += *cs++;
  /* #258: (@20[3:6] += @5) */
  for (rr=w20+3, cs=w05; rr!=w20+6; rr+=1) *rr += *cs++;
  /* #259: (@20[:3] += @3) */
  for (rr=w20+0, cs=w03; rr!=w20+3; rr+=1) *rr += *cs++;
  /* #260: @25 = vertcat(@17, @20) */
  rr=w25;
  for (i=0, cs=w17; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<12; ++i) *rr++ = *cs++;
  /* #261: (@21[56, 57, 58, 59, 60, 61, 62, 63, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159] = @25) */
  for (cii=casadi_s42, rr=w21, cs=w25; cii!=casadi_s42+20; ++cii, ++cs) rr[*cii] = *cs;
  /* #262: (@21[7, 15, 23, 31, 39, 47, 55, 63, 71, 83, 95, 107, 119, 131, 143, 155, 167, 179, 191, 203] = @25) */
  for (cii=casadi_s43, rr=w21, cs=w25; cii!=casadi_s43+20; ++cii, ++cs) rr[*cii] = *cs;
  /* #263: @12 = project(@11) */
  casadi_sparsify(w11, (&w12), casadi_s44, 0);
  /* #264: @0 = ones(20x1,1nz) */
  w00 = 1.;
  /* #265: {NULL, @23} = vertsplit(@0) */
  w23 = w00;
  /* #266: @0 = @23[0] */
  for (rr=(&w00), cs=(&w23)+0; cs!=(&w23)+1; cs+=1) *rr++ = *cs;
  /* #267: @23 = vertcat(@24, @24, @0, @24) */
  rr=(&w23);
  *rr++ = w00;
  /* #268: @12 = (@12*@23) */
  w12 *= w23;
  /* #269: @12 = @12' */
  /* #270: @20 = mac(@12,@10,@1) */
  casadi_copy(w01, 12, w20);
  casadi_mtimes((&w12), casadi_s45, wr10, casadi_s5, w20, casadi_s4, w, 0);
  /* #271: @20 = @20' */
  /* #272: @9 = mac(@12,@19,@1) */
  casadi_copy(w01, 12, w09);
  casadi_mtimes((&w12), casadi_s45, w19, casadi_s5, w09, casadi_s4, w, 0);
  /* #273: @9 = @9' */
  /* #274: @20 = (@20+@9) */
  for (i=0, rr=w20, cs=w09; i<12; ++i) (*rr++) += (*cs++);
  /* #275: @20 = (@20/@8) */
  for (i=0, rr=w20, cs=wr08; i<12; ++i) (*rr++) /= (*cs++);
  /* #276: {@3, @5, @6, @7} = vertsplit(@20) */
  casadi_copy(w20, 3, w03);
  casadi_copy(w20+3, 3, w05);
  casadi_copy(w20+6, 3, w06);
  casadi_copy(w20+9, 3, w07);
  /* #277: @20 = @2; (@20[9:12] += @7) */
  casadi_copy(w02, 12, w20);
  for (rr=w20+9, cs=w07; rr!=w20+12; rr+=1) *rr += *cs++;
  /* #278: (@20[6:9] += @6) */
  for (rr=w20+6, cs=w06; rr!=w20+9; rr+=1) *rr += *cs++;
  /* #279: (@20[3:6] += @5) */
  for (rr=w20+3, cs=w05; rr!=w20+6; rr+=1) *rr += *cs++;
  /* #280: (@20[:3] += @3) */
  for (rr=w20+0, cs=w03; rr!=w20+3; rr+=1) *rr += *cs++;
  /* #281: (@21[160:172] = @20) */
  for (rr=w21+160, cs=w20; rr!=w21+172; rr+=1) *rr = *cs++;
  /* #282: (@21[72:216:12] = @20) */
  for (rr=w21+72, cs=w20; rr!=w21+216; rr+=12) *rr = *cs++;
  /* #283: @12 = project(@11) */
  casadi_sparsify(w11, (&w12), casadi_s46, 0);
  /* #284: @23 = ones(20x1,1nz) */
  w23 = 1.;
  /* #285: {NULL, @0} = vertsplit(@23) */
  w00 = w23;
  /* #286: @23 = @0[0] */
  for (rr=(&w23), cs=(&w00)+0; cs!=(&w00)+1; cs+=1) *rr++ = *cs;
  /* #287: @0 = vertcat(@24, @24, @24, @23) */
  rr=(&w00);
  *rr++ = w23;
  /* #288: @12 = (@12*@0) */
  w12 *= w00;
  /* #289: @12 = @12' */
  /* #290: @20 = mac(@12,@10,@1) */
  casadi_copy(w01, 12, w20);
  casadi_mtimes((&w12), casadi_s47, wr10, casadi_s5, w20, casadi_s4, w, 0);
  /* #291: @20 = @20' */
  /* #292: @9 = mac(@12,@19,@1) */
  casadi_copy(w01, 12, w09);
  casadi_mtimes((&w12), casadi_s47, w19, casadi_s5, w09, casadi_s4, w, 0);
  /* #293: @9 = @9' */
  /* #294: @20 = (@20+@9) */
  for (i=0, rr=w20, cs=w09; i<12; ++i) (*rr++) += (*cs++);
  /* #295: @20 = (@20/@8) */
  for (i=0, rr=w20, cs=wr08; i<12; ++i) (*rr++) /= (*cs++);
  /* #296: {@3, @5, @6, @7} = vertsplit(@20) */
  casadi_copy(w20, 3, w03);
  casadi_copy(w20+3, 3, w05);
  casadi_copy(w20+6, 3, w06);
  casadi_copy(w20+9, 3, w07);
  /* #297: @20 = @2; (@20[9:12] += @7) */
  casadi_copy(w02, 12, w20);
  for (rr=w20+9, cs=w07; rr!=w20+12; rr+=1) *rr += *cs++;
  /* #298: (@20[6:9] += @6) */
  for (rr=w20+6, cs=w06; rr!=w20+9; rr+=1) *rr += *cs++;
  /* #299: (@20[3:6] += @5) */
  for (rr=w20+3, cs=w05; rr!=w20+6; rr+=1) *rr += *cs++;
  /* #300: (@20[:3] += @3) */
  for (rr=w20+0, cs=w03; rr!=w20+3; rr+=1) *rr += *cs++;
  /* #301: (@21[172:184] = @20) */
  for (rr=w21+172, cs=w20; rr!=w21+184; rr+=1) *rr = *cs++;
  /* #302: (@21[73:217:12] = @20) */
  for (rr=w21+73, cs=w20; rr!=w21+217; rr+=12) *rr = *cs++;
  /* #303: @12 = project(@11) */
  casadi_sparsify(w11, (&w12), casadi_s48, 0);
  /* #304: @0 = ones(20x1,1nz) */
  w00 = 1.;
  /* #305: {NULL, @23} = vertsplit(@0) */
  w23 = w00;
  /* #306: @0 = @23[0] */
  for (rr=(&w00), cs=(&w23)+0; cs!=(&w23)+1; cs+=1) *rr++ = *cs;
  /* #307: @23 = vertcat(@24, @24, @24, @0) */
  rr=(&w23);
  *rr++ = w00;
  /* #308: @12 = (@12*@23) */
  w12 *= w23;
  /* #309: @12 = @12' */
  /* #310: @20 = mac(@12,@10,@1) */
  casadi_copy(w01, 12, w20);
  casadi_mtimes((&w12), casadi_s49, wr10, casadi_s5, w20, casadi_s4, w, 0);
  /* #311: @20 = @20' */
  /* #312: @9 = mac(@12,@19,@1) */
  casadi_copy(w01, 12, w09);
  casadi_mtimes((&w12), casadi_s49, w19, casadi_s5, w09, casadi_s4, w, 0);
  /* #313: @9 = @9' */
  /* #314: @20 = (@20+@9) */
  for (i=0, rr=w20, cs=w09; i<12; ++i) (*rr++) += (*cs++);
  /* #315: @20 = (@20/@8) */
  for (i=0, rr=w20, cs=wr08; i<12; ++i) (*rr++) /= (*cs++);
  /* #316: {@3, @5, @6, @7} = vertsplit(@20) */
  casadi_copy(w20, 3, w03);
  casadi_copy(w20+3, 3, w05);
  casadi_copy(w20+6, 3, w06);
  casadi_copy(w20+9, 3, w07);
  /* #317: @20 = @2; (@20[9:12] += @7) */
  casadi_copy(w02, 12, w20);
  for (rr=w20+9, cs=w07; rr!=w20+12; rr+=1) *rr += *cs++;
  /* #318: (@20[6:9] += @6) */
  for (rr=w20+6, cs=w06; rr!=w20+9; rr+=1) *rr += *cs++;
  /* #319: (@20[3:6] += @5) */
  for (rr=w20+3, cs=w05; rr!=w20+6; rr+=1) *rr += *cs++;
  /* #320: (@20[:3] += @3) */
  for (rr=w20+0, cs=w03; rr!=w20+3; rr+=1) *rr += *cs++;
  /* #321: (@21[184:196] = @20) */
  for (rr=w21+184, cs=w20; rr!=w21+196; rr+=1) *rr = *cs++;
  /* #322: (@21[74:218:12] = @20) */
  for (rr=w21+74, cs=w20; rr!=w21+218; rr+=12) *rr = *cs++;
  /* #323: @12 = project(@11) */
  casadi_sparsify(w11, (&w12), casadi_s50, 0);
  /* #324: @23 = ones(20x1,1nz) */
  w23 = 1.;
  /* #325: {NULL, @0} = vertsplit(@23) */
  w00 = w23;
  /* #326: @23 = @0[0] */
  for (rr=(&w23), cs=(&w00)+0; cs!=(&w00)+1; cs+=1) *rr++ = *cs;
  /* #327: @0 = vertcat(@24, @24, @24, @23) */
  rr=(&w00);
  *rr++ = w23;
  /* #328: @12 = (@12*@0) */
  w12 *= w00;
  /* #329: @12 = @12' */
  /* #330: @11 = mac(@12,@10,@1) */
  casadi_copy(w01, 12, w11);
  casadi_mtimes((&w12), casadi_s51, wr10, casadi_s5, w11, casadi_s4, w, 0);
  /* #331: @11 = @11' */
  /* #332: @1 = mac(@12,@19,@1) */
  casadi_mtimes((&w12), casadi_s51, w19, casadi_s5, w01, casadi_s4, w, 0);
  /* #333: @1 = @1' */
  /* #334: @11 = (@11+@1) */
  for (i=0, rr=w11, cs=w01; i<12; ++i) (*rr++) += (*cs++);
  /* #335: @11 = (@11/@8) */
  for (i=0, rr=w11, cs=wr08; i<12; ++i) (*rr++) /= (*cs++);
  /* #336: {@3, @5, @6, @7} = vertsplit(@11) */
  casadi_copy(w11, 3, w03);
  casadi_copy(w11+3, 3, w05);
  casadi_copy(w11+6, 3, w06);
  casadi_copy(w11+9, 3, w07);
  /* #337: (@2[9:12] += @7) */
  for (rr=w02+9, cs=w07; rr!=w02+12; rr+=1) *rr += *cs++;
  /* #338: (@2[6:9] += @6) */
  for (rr=w02+6, cs=w06; rr!=w02+9; rr+=1) *rr += *cs++;
  /* #339: (@2[3:6] += @5) */
  for (rr=w02+3, cs=w05; rr!=w02+6; rr+=1) *rr += *cs++;
  /* #340: (@2[:3] += @3) */
  for (rr=w02+0, cs=w03; rr!=w02+3; rr+=1) *rr += *cs++;
  /* #341: (@21[196:208] = @2) */
  for (rr=w21+196, cs=w02; rr!=w21+208; rr+=1) *rr = *cs++;
  /* #342: (@21[75:219:12] = @2) */
  for (rr=w21+75, cs=w02; rr!=w21+219; rr+=12) *rr = *cs++;
  /* #343: @26 = @21' */
  casadi_trans(w21,casadi_s52, w26, casadi_s52, iw);
  /* #344: output[2][0] = @26 */
  casadi_copy(w26, 208, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int satellite_full_cost_ext_cost_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int satellite_full_cost_ext_cost_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int satellite_full_cost_ext_cost_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void satellite_full_cost_ext_cost_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int satellite_full_cost_ext_cost_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void satellite_full_cost_ext_cost_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void satellite_full_cost_ext_cost_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void satellite_full_cost_ext_cost_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int satellite_full_cost_ext_cost_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int satellite_full_cost_ext_cost_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real satellite_full_cost_ext_cost_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* satellite_full_cost_ext_cost_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* satellite_full_cost_ext_cost_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* satellite_full_cost_ext_cost_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s53;
    case 1: return casadi_s54;
    case 2: return casadi_s55;
    case 3: return casadi_s56;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* satellite_full_cost_ext_cost_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s57;
    case 1: return casadi_s58;
    case 2: return casadi_s52;
    case 3: return casadi_s59;
    case 4: return casadi_s60;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int satellite_full_cost_ext_cost_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 21;
  if (sz_w) *sz_w = 980;
  return 0;
}

CASADI_SYMBOL_EXPORT int satellite_full_cost_ext_cost_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 9*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 21*sizeof(casadi_int);
  if (sz_w) *sz_w = 980*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
