on:
    pull_request:
        types:
            - closed
        branches:
            - develop

jobs:
    if_merged:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
        - name: Pull repo
          uses: actions/checkout@v3
          with:
            ref: develop
            fetch-depth: 0 
            token: ${{ secrets.BOT_ACCESS_TOKEN }}
        - name: Bump version
          run: ./.github/workflows/version-bumper.sh ./docs/source/bskVersion.txt
        - name: Commit and push
          run: |
              git config user.name "AVSlabBot"
              git config user.email "cuavslab@gmail.com"
              git commit -a -m "[AUTO] Bump version number"
              git push
